### ISSUE TITLE
PAM50_cord should be equal to a binary version of PAM50_levels

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#1192]
currently there are some discrepancies, because PAM50_cord was generated by create_atlas routine (and PAM50_levels has not been updated).

**Comment by joshuacwnewton** [comment]
I'm closing this issue, but mainly because of https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3952.

If our plan for v6.0.0 is to update the PAM50 spinal level files, then it would imply that we would also have to update `PAM50_cord` too (which would render this issue moot?).

If my understanding here is wrong, though, then we can reopen.

**Comment by jcohenadad** [comment]
> If our plan for v6.0.0 is to update the PAM50 spinal level files, then it would imply that we would also have to update PAM50_cord too (which would render this issue moot?).

I don't think so https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3952#issuecomment-1383282448

**Comment by jcohenadad** [comment]
However! I see this issue is old and it is very likely that it has already been solved-- easy to check: open PAM50_cord and PAM50_levels and see if these two images match.

or to do it algorithmically:
- binarize PAM50_levels
- run: `sct_maths -i PAM50_cord -sub PAM_levels_binarized -o cord_minus_levels
- run: `sct_image -i cord_minus_levels -display` --> should be empty

**Comment by mguaypaq** [comment]
The two images **almost** match:
* Every nonzero voxel in `PAM50_levels.nii.gz` is also nonzero in  `PAM50_cord.nii.gz`.
* The nonzero voxels with z-coordinate >=964 in `PAM50_cord.nii.gz` are **not** nonzero in `PAM50_levels.nii.gz`.

But it looks like maybe we use 0 as one of the label values in `PAM50_levels.nii.gz`, which would explain the difference?

**Comment by jcohenadad** [comment]
> But it looks like maybe we use 0 as one of the label values in PAM50_levels.nii.gz, which would explain the difference?

0 would not be an acceptable label value (because almost ALL voxels have zero value)

**Comment by jcohenadad** [comment]
> The nonzero voxels with z-coordinate >=964 in PAM50_cord.nii.gz are not nonzero in PAM50_levels.nii.gz.

so that's probably a glitch we need to fix

**Comment by mguaypaq** [comment]
I'll need to figure out more context before attempting a fix:
* If the fix is to "bump" the existing labels up by 1, so that the spinal cord 0-voxels can become 1-voxels, I'd need to very carefully check whether that's a breaking change only for our code, or for user code as well.
* If the fix is to just extend of region of 1-voxels to cover the rest of the spinal cord, that may be less breaking.
* I'm not sure yet how to decide which fix needs to happen.

Also, is this the same issue as #3997?

**Comment by jcohenadad** [comment]
ah! ok i see what's happening here. The cord seg is extending more rostrally compared to the vert level mask for >=964 as reported by @mguaypaq (i misinterpreted your comment Mathieu-- I thought there was only ONE voxel that mismatched):

color: vert level; white: cord seg.
![image](https://user-images.githubusercontent.com/2482071/213271068-06f0a2c4-afc1-405a-aa48-c02f253a2f27.png)

So, this is all fine, and expected. No bug here. 

However, in order to fix #3997 we will need to extend the vert level mask. But this issue can be considered solved.
