### ISSUE TITLE
show picture of where to do the labeling

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#1261]
example:
![screen shot 2017-04-19 at 08 18 04](https://cloud.githubusercontent.com/assets/2482071/25179659/d86981f6-24d8-11e7-8011-c960ccc1c57c.png)

**Comment by joshuacwnewton** [comment]
I think when this issue was first created, it was referring to the SourceForge documentation, where there were dedicated pages for each SCT script.

We no longer have dedicated per-script pages (see https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3095). But, we do have the tutorials/SCT course. In particular, [this page](https://spinalcordtoolbox.com/user_section/tutorials/registration-to-template/vertebral-labeling/manual-labeling-c2c3.html) provides an overview of manual labeling of the C2-C3 disc, complete with a nice and shiny figure:

![image](https://user-images.githubusercontent.com/16181459/212500957-19d58433-065a-47ed-83db-f4a2010c9ea3.png)

So, I think we can consider this issue resolved for now.

(When https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3095 is implemented, we can certainly make an effort to add diagrams like the one in this issue.)
