### ISSUE TITLE
Allow `sct_maths` to run multiple sequential operations in one command

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#1447]
Example:
~~~
sct_maths -i target.nii -mul 7 -add b0_moco_T0006.nii -div 7 -o target.nii
~~~

**Comment by jcohenadad** [comment]
Removed priority low on this one-- it would be a very useful feature to have 😊 

Eg: another thing I was trying to do, and all it did was 'thr' and 'uthr', but it missed 'bin':

~~~
sct_maths -i sub-05_acq-anatCP_TB1TFL_seg_labeled.nii.gz -thr 3 -uthr 9 -bin 1 -o sub-05_acq-anatCP_TB1TFL_mask-shimming.nii.gz
~~~

**Comment by joshuacwnewton** [comment]
Some notes:

- Thankfully, most `sct_maths` options are written such that there is 1 input image and 1 output image (compared to `sct_image` which has more complicated I/O)
    - The exception to this is the `compute_similarity` functionality (`-mi`, `-minorm`, `-corr`), which takes in a second input image and outputs a text file rather than an image. 
- `sct_maths`'s `main` function is one big `if`/`elif`/`else` block without any superfluous steps, meaning that we should be able to isolate the "single-image" logic, then iterate over the input arguments to chain operations.
- Because we've written our parser such that we explicitly work with a list of unparsed input arguments (as opposed to letting `argparse` infer from `sys.argv`), we should be able to preserve the order of the arguments and apply them in order (should that matter).
   - Note that trying to get the order of arguments from argparse itself [seems challenging](https://stackoverflow.com/questions/9027028/argparse-argument-order), so I think we're lucky that we have access to the unparsed arguments. 

I think this should be very doable, given the above? 

I'd be happy to self-assign, though I may triage it below the bugfixes in my backlog at the moment. :)

**Comment by jcohenadad** [comment]
> we should be able to preserve the order of the arguments and apply them in order (should that matter).

Yes, that does matter a lot indeed. Good call! Thank you for looking into this 🙏

**Comment by mguaypaq** [comment]
> * Note that trying to get the order of arguments from argparse itself [seems challenging](https://stackoverflow.com/questions/9027028/argparse-argument-order), so I think we're lucky that we have access to the unparsed arguments.

For something like this, I think we should be using argparse actions? That way, we should be able to build up a list of operations to perform, in the order that they appear. (At first I thought we could even _do_ the image operations inside the argparse actions, but it's better to wait until the end of parsing, in case there's a syntax error later on.)
