### ISSUE TITLE
The field absolutepath in misleading

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#1670]
### Prerequisites

* [x] Did you check past issues for similar issue(s) ?
* [ ] Can you reproduce the issue with any of the files found in `sct_testing_data` ?
* [ ] If you are using a development environment, is your environment updated ?

### Description

In `msct_image`, the field `absolutepath` is assigned the value `path` in `loadFromPath()`. The problem is that the variable `path` could be a relative path, and hence the name of the field `absolutepath` introduces confusion in the code when later used. 

My suggestion would be to refactor `msct_image:loadFromPath()` such that `absolutepath` is indeed an absolute path.

### State of spinalcordtoolbox

sct v3.1.0

**Comment by zougloub** [comment]
Whenever something receives a path and stores it, it better immediately become absolute because that something doesn't know the context in which the path was provided. Especially in SCT with all the crazy `chdir()` going on (which I hope will go away in the future), not storing absolute paths could be a source of errors for API users.
I don't think there's a need for the path to be called `absolute` even if it *should* be absolute.

Also, talking about `msct_image`, the `path`, `file_name`, `ext` naming is so-so and its storage as public attributes is redundant with `absolutepath`...
- often they are modified and `absolutepath` becomes stale
- on naming, the standard terms are `directory`or `parent`, `stem` and `extension`; suggested class attributes could be `path_dir/path_stem/path_ext` if these ever need to be stored.
- `extract_fname` is relatively easy to call in callers code and since there is a common pattern of transforming `x.nii.gz` to `x_bin.nii.gz`, a helper function could deal with that throughout the code

**Comment by joshuacwnewton** [comment]
This was fixed in https://github.com/spinalcordtoolbox/spinalcordtoolbox/commit/e0201251ce4d7c99c330e95177a48719f3e97a22 but never closed. 

We currently use a setter method to ensure that `.absolutepath` is indeed the absolutepath:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/a685d7f0d8032f9df685a08d22947947ac416e71/spinalcordtoolbox/image.py#L341-L350
