### ISSUE TITLE
Use `algo=slicereg` instead of `algo=rigid` in `batch_processing.sh` for mt0-mt1 reg

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#1804]
https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/1b5c49c3904dffe63546adbadc47759a53fbc8ca/batch_processing.sh#L163-L166

**Comment by joshuacwnewton** [comment]
Slicereg was already switched in for mt0/mt1 registration in the tutorials/SCT course: https://spinalcordtoolbox.com/user_section/tutorials/multimodal-registration/mtr-computation/coregistering-mt0-mt1.html

So, this should be a really easy swap, since it's just unifying `batch_processing.sh` and `batch_single_subject.sh`:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/1b5c49c3904dffe63546adbadc47759a53fbc8ca/batch_processing.sh#L163-L166

**Comment by joshuacwnewton** [comment]
I've closed this issue with a direct commit to `master`, since the fix is so simple and straightforward.

**Comment by joshuacwnewton** [comment]
Reopening this issue and reverting the commit because there were changes to the results of batch_processing.sh that I didn't anticipate.
