### ISSUE TITLE
Refactor SCT to make it more compatible with FSLeyes' "Open Notebooks" Jupyter functionality

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#1860]
(from @perone): FSLEyes has integrated Jupyter Notebooks, so there is now an option called "Open Notebooks" where you can interact with FSLEyes from this environment.
It seems to me, that it is even more important to have a proper refactoring of the scripts to the spinalcordtoolbox as a means to expose the Python API that can be used. In future, we can provide Jupyter notebooks with many examples on how to use SCT with the FSLEyes, where the FSLEyes can become more and more an interface to work together with SCT that could make a lot of things easier for the SCT tools, especially when some user feedback is required, like for instance selecting key points to drive some other task, etc.

**Comment by joshuacwnewton** [comment]
> It seems to me, that it is even more important to have a proper refactoring of the scripts to the spinalcordtoolbox as a means to expose the Python API that can be used

On reflection, I don't think this is a feasible idea for 2 main reasons:

1. SCT is mainly used via its CLI, not via its Python API. (And, the API likely won't be made available to users any time soon -- see point 7. in [#1526 (comment)](https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/1526#issuecomment-1148981501)).
2. SCT already has a FSLeyes integration that integrates the SCT CLI with FSLeyes.

> FSLEyes can become more and more an interface to work together with SCT that could make a lot of things easier for the SCT tools

I think we can achieve this goal via further development of the existing FSLeyes integration script, rather than the "Open Notebooks" functionality of FSLeyes.

I would suggest to close this issue, then?

**Comment by joshuacwnewton** [comment]
Given the two thumbs up above, I'm going to close this issue.
