### ISSUE TITLE
Fix broken integrity test for sct_label_utils

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#2133]
i deactivated it for emergency reasons (need to create release, test was not passing on travis due to precision issue, etc.)

**Comment by joshuacwnewton** [comment]
I've tried reactivating it, and the test is still broken, but for a seemingly different reason.

https://github.com/neuropoly/spinalcordtoolbox/blob/f497c2f4cf512d184e07761f712631016d3e0454/testing/test_sct_label_utils.py#L57

This call to `sct_label_utils` returns `None` instead of the expected output, so I believe this call is broken/outdated.

**Comment by jcohenadad** [comment]
@joshuacwnewton now that we have a proper API, you can bypass the system call in the integrity test, and just get the coordinates of the output file, and verify that they match with the [hard-coded coordinates](https://github.com/neuropoly/spinalcordtoolbox/blob/f497c2f4cf512d184e07761f712631016d3e0454/testing/test_sct_label_utils.py#L36).

This is what i've tried on my terminal:
```bash
cd sct_testing_data/t2
# run function to test
sct_label_utils -i t2_seg-manual.nii.gz -cubic-to-point -o test_centerofmass.nii.gz
# interrogate output
sct_label_utils -i test_centerofmass.nii.gz -display
# and this is the output:
--
Spinal Cord Toolbox (git-master-f497c2f4cf512d184e07761f712631016d3e0454)

Position=(31,28,25) -- Value= 1
All labels (useful syntax):
31,28,25,1   --> looks good 🎉
```
