### ISSUE TITLE
Clearer usage needed for backward warping field

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#2156]
more info: https://sourceforge.net/p/spinalcordtoolbox/help/18/

**Comment by joshuacwnewton** [comment]
Looking at the context of this issue: 

> When I input `-owarp diff2atlas_warp.nii.gz`, I was expecting the inverse transform to have some name similar to this. The algorithm chose an inverse warp name using the actual names of the input and destination images and I just didn't notice that this was actually output (too many similarly named files in my directory!).

At the time of this issue, there was no `-owarpinv` option, which would explain the user's assumption about the `-owarpinv` name being automatically chosen (since they couldn't choose it themselves).

Given that there now _is_ an `-owarpinv` option right beside `-owarp` (thanks to #3507), I think this unclear usage situation is addressed?

![image](https://user-images.githubusercontent.com/16181459/213005635-df6de625-ff15-476b-b473-02c36b7a9953.png)

If the user already knows about `-owarp`, they will probably know about `-owarpinv` too, which will avoid the situation this user found themselves in.
