### ISSUE TITLE
Specify what angle_RL and angle_AP refer to

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#2224]
Refers to https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/2219#issuecomment-482716199

**Comment by joshuacwnewton** [comment]
The current help description of `sct_process_segmentation` states:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/377bfb88a9845bb8348e760aea5d70bb4f4bcb42/spinalcordtoolbox/scripts/sct_process_segmentation.py#L68-L69

It looks like this was added in https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/2200. Maybe the fix got slipped into the PR, but this issue was never linked?

Closing this issue as resolved.
