### ISSUE TITLE
Very slow download from miniconda from china

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#2403]
So slow that the download drops at some point (had to manually change the "delay-timeout" time to 1000s or so). We should redirect to mirrors. I think @zougloub was working on it.

**Comment by zougloub** [comment]
Would be worth it to try and get rid of miniconda, as we're probably pulling all the packages from pip.

The only thing I could do when there are network issues is a security nightmare: it was adding a MITM proxy that would cache the HTTPS downloads.
Mirroring *conda or *pip also takes more complex infra than eg. a simple CDN.

Note: Alibaba has an authorized mirror of *conda stuff, that could be tried also with an option to the installer. But there are many other network issues that can pop up in these parts of the world..

**Comment by jcohenadad** [comment]
> Would be worth it to try and get rid of miniconda, as we're probably pulling all the packages from pip.

that assumes people already have Python installed (and the proper version), which is not always the case. If it is not the case, some won't know how to install it. So far miniconda has proven useful for us to control the environment. I'm afraid trusting every user's python will open a pandora's box.

**Comment by joshuacwnewton** [comment]
I'm not sure if this issue is referring to the download of the Miniconda installer itself, or the download of packages during the installation of SCT.

But, either way, we've run into speed issues re: China in the time since this issue (see https://forum.spinalcordmri.org/t/installation-failed-problem-with-anaconda/748/4), and the solution was to use [TUNA](http://mirrors.tuna.tsinghua.edu.cn/), the open source mirror of TsingHua University (China). 

TUNA also offers Miniconda installers: https://mirrors.bfsu.edu.cn/anaconda/miniconda/?C=M&O=A

![image](https://user-images.githubusercontent.com/16181459/213313294-55de3c1f-d47f-486c-bd5b-deec724d52f1.png)

Similar solutions were echoed in this issue: https://github.com/pytorch/pytorch/issues/990

I think we can marked this as solved. (At least until we get a chance to try these solutions with future users.)
