### ISSUE TITLE
Find a reliable way to copy and paste commands for the SCT Course

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#2407]
> **Note:** Edited 2023-09-12 by @joshuacwnewton to provide more details.

The SCT Course slides come from an [Apple Keynote presentation](https://www.icloud.com/keynote/null#SCT%5FCourse%5F2021-11-16) exported to PDF (stored in [NeuroPoly's Google Drive](https://drive.google.com/drive/u/1/folders/0Bx3A13n3Q_EARGxKTHE2MC1iSVk?resourcekey=0---RcqAsD725SZ_C1zL-f1w)). 

The course is typically taught using the following layout:

![image](https://github.com/spinalcordtoolbox/spinalcordtoolbox/assets/16181459/647ccca2-3544-439e-b0c5-50e8a3c94712)

The course Keynote and a terminal window are both open at the same time, and we switch back and forth to enter commands from the slides into the terminal. (Note: There is also a web browser open for QC reports, which can make things a little more complicated, since there are 3 windows to juggle.)

-----

Copying and pasting works perfectly when inside Keynote. You can triple-click, and entire lines will be highlighted exactly as they were written. So, there isn't much problem on the presenter side.

![ezgif com-gif-maker(1)](https://github.com/spinalcordtoolbox/spinalcordtoolbox/assets/16181459/11124b3f-e11f-4918-9193-5f6e1a5c9e34)

----

However, course participants typically use the exported PDF file, and will try to copy and paste commands from the PDF into their terminal. But, depending on the OS/browser/PDF viewer, there are a number of issues:

- Spaces can sometimes be inserted into the command, causing errors when copied directly into the terminal.
- Triple-click will usually not work, only highlighting part of the command (demonstrated below in Firefox + Ubuntu 22.04).

![ezgif com-gif-maker(2)](https://github.com/spinalcordtoolbox/spinalcordtoolbox/assets/16181459/0e840f39-4e64-44ac-975d-99ede6ac3e61)

These issues make it harder for participants to keep up with the slides in real-time. They may try to manually input the commands, but because of the length/complexity, they may make errors. The result is that many participants fall behind and get lost during the course. 

----

Text extraction from PDFs is notoriously unreliable ([article](https://archive.ph/FBtFb), [discussion](https://news.ycombinator.com/item?id=22473263)). Each PDF viewer will handle text extraction differently. So, it would be good if we could provide a more reliable way for people to execute commands and follow along with the course.

**Comment by joshuacwnewton** [comment]
As a small progress update, in the most recent SCT Course, we tried to fix this issue by instructing users to copy and paste commands from the [`batch_single_subject.sh` ](https://github.com/spinalcordtoolbox/sct_tutorial_data/blob/master/single_subject/batch_single_subject.sh) script instead, which avoids this issue (since it's plaintext).

However, the script has its own issue:

* https://github.com/spinalcordtoolbox/sct_tutorial_data/issues/7

There are some suggestions in that issue to make the process easier. So... perhaps after some iteration, a plaintext source for commands will be easiest, and we can consider this issue resolved?

**Comment by joshuacwnewton** [comment]
Here is a tl;dr summary of everything we've thought of so far:

## Past attempted solutions

1. Asking participants to use the Keynote directly
   - Hard to set up (iCloud account, granting permissions to participants)
2. Exporting Keynote to Powerpoint/Google Sheets for better sharing
   - Formatting gets messed up (font, font size, layout) 
3. Copying and pasting directly from the `batch_single_subject.sh` bash script
   - Plain text → No copy-paste issues.
   - Used in 2021 SCT Course. The feedback we got was:
   - [Too complicated](https://github.com/spinalcordtoolbox/sct_tutorial_data/issues/7) (too many windows to keep open, hard to stay in sync with the course)
4. Using SCT's [web tutorials](https://spinalcordtoolbox.com/user_section/tutorials.html) instead of the slides
   - Plain text → No copy-paste issues. But...
   - Too much information (slides are simpler, web tutorials have extra details meant for "offline use")
   - Layout is worse for presentations (small text, dense paragraphs, small images, etc.)
   - Organization into sub-tutorials is more complicated to follow compared to the simple organization of the slides.

## New brainstormed ideas

5. Embed PDF in website (i.e. try to get a "standardized" PDF viewer that will copy-paste correctly, which would avoid the platform-specific issues)
6. Generate a webpage that contains the slides from the PDF interspersed with the commands in text form. (This would have all of the benefits of using a PDF of the slides, while also providing the commands in plain text, all in a single window.) [`pypdf`](https://github.com/py-pdf/pypdf)
7. Instruct participants to run the `batch_single_subject.sh` script in "debug mode" ([1](https://stackoverflow.com/a/9080645), [2](https://selivan.github.io/2022/05/21/bash-debug.html)), which lets them run the commands one-by-one (no need to type out commands).
8. Create a Python script (e.g. `sct_course`) that provides a text user interface to walk participants through each step (no need to type out commands).

I'm going to try and create some demos for these newly-brainstormed ideas. I am especially interested in idea 6.

**Comment by jcohenadad** [comment]
We could also re-consider option 2 (Exporting from Keynote to Gslide) and manually fixing the Gslide. 
- pros: having the slides on Gslide make it easier for SCT team member without Keynote to edit the slides
- cons: Gslide might not be easily accessible in some countries (eg China)

**Comment by joshuacwnewton** [comment]
I agree!! 

While I do worry that there is quite a lot of text that is affected, the good news is that the formatting issues seem to only affect certain styles of text. And, since Keynote allows you to modify text styles throughout the entire document (e.g. I remember we had a "code" text style in our Keynote), then it may just be a matter of tweaking the problematic text styles in Keynote (e.g. changing font/font size) and then exporting.

**Comment by joshuacwnewton** [comment]
>  We could also re-consider option 2 (Exporting from Keynote to Gslide) and manually fixing the Gslide.

I've been playing with the SCT course PDF in Google Slides, and I think it might be the best option. It's simple and doesn't require any complicated technical solutions like my other brainstormed ideas.

Turning on Sharing -> "Anyone with the link can view" works perfectly. Copying and pasting works as expected, and there's no need to even be logged into a Google Account (completely accessible in a new private window).

There is some work that needs to be done with formatting, but I have a better understanding of what needs to be fixed (and how to do it in an efficient way using Google Slides' "Theme Builder"), and so I'd be happy to take this on. :)

I will try to get a complete Google Slides for the next meeting, so that I can share it (and so we have a centralized place to make changes for the 2023 version of the SCT course slides.)

**Comment by jcohenadad** [comment]
Amazing. Thank you soooo much @joshuacwnewton for looking into this!

**Comment by joshuacwnewton** [comment]
It took a little while to set up a macOS virtual machine and access the desktop version of Keynote, but once I did, fixing the formatting became much easier:

- Titles --> Handled in Keynote's Slide Layout editor
- Bullet points --> Handled in Keynote's Slide Layout editor
- Unexpected wrapping text boxes (SCT URL, citations, etc.) --> Handled in Keynote's Slide Layout editor

This lessened the amount of things I had to manually fix throughout the slides (with the remaining needed fixes being [italics/bold font size](https://gist.github.com/joshuacwnewton/ae6d2e5a548c684fb8cd670041f5c602#4-special-formatting-italic-bold-monospace-links), [link wrapping](https://gist.github.com/joshuacwnewton/ae6d2e5a548c684fb8cd670041f5c602#5-link-text-wrapping), [transparent Outline overlay](https://gist.github.com/joshuacwnewton/ae6d2e5a548c684fb8cd670041f5c602#6-transparent-overlay-on-outline-slides), and [table text wrapping](https://gist.github.com/joshuacwnewton/ae6d2e5a548c684fb8cd670041f5c602#7-table-text-wrapping).

There is now a properly formatted `.pptx` file in the [SCT Courses Google Drive folder](https://drive.google.com/drive/folders/1UbcNtZAWrfYsdKykKqirfumRiVPgAWTP?usp=drive_link) that can be opened in Google Slides, and accessed via the following sharing link: https://docs.google.com/presentation/d/1ODmN2lBCkghLNbG_hrXWWCdsoTJ0KyRR/edit?usp=sharing&ouid=107697289023552898198&rtpof=true&sd=true. This link can be opened in a private/incognito tab, and copying and pasting should work okay using triple-click. :slightly_smiling_face:

**Comment by jcohenadad** [comment]
This is great, thank you @joshuacwnewton. Few comments:
- is the idea to share the pptx (in view-only mode) or to generate a pdf and share the pdf? I guess the former?
- please note that the generated presentation is still a pptx, not a 'proper' google slide. I don't think it is a big issue to have it as pptx, but given that we are relying on the gslide ecosystem, i'm thinking it might be better to not rely on the microsoft format (pptx) and have the presentation as a proper google slide, if the conversion does not produce weird issues

**Comment by jcohenadad** [comment]
> So, I think we can distribute this link directly to participants, rather than distributing a PDF. 🙂

ah sorry you already answered my first point

**Comment by joshuacwnewton** [comment]
> * please note that the generated presentation is still a pptx, not a 'proper' google slide. I don't think it is a big issue to have it as pptx, but given that we are relying on the gslide ecosystem, i'm thinking it might be better to not rely on the microsoft format (pptx) and have the presentation as a proper google slide, if the conversion does not produce weird issues

Thankfully this is a 2s fix:

![image](https://github.com/spinalcordtoolbox/spinalcordtoolbox/assets/16181459/70febfbb-38c0-4f7e-bc13-6aae82280bcc)

![image](https://github.com/spinalcordtoolbox/spinalcordtoolbox/assets/16181459/0f8f0918-7aa0-419c-9ed0-869e6776e326)

There are no issues with pptx -> slides conversion. What we saw with the pptx in Google Slides is the exact same as the gslide in Google Slides. :smile:

**Comment by joshuacwnewton** [comment]
> is the idea to share the pptx (in view-only mode) or to generate a pdf and share the pdf? I guess the former?

One thing we can do is share the link ahead of time, and then provide instructions for participants to export to PDF on their own (e.g. if they need to print it). Even from a logged out/incognito window, it's still very easy to download the slides from the link:

![image](https://github.com/spinalcordtoolbox/spinalcordtoolbox/assets/16181459/29173f23-d2db-41ba-a033-eb18d2783fcc)

**Comment by joshuacwnewton** [comment]
Closing as completed -- Google Slides seems like a good solution for now. :)
