### ISSUE TITLE
`sct_deepseg_sc` performs poorly on images with spinal cord compression

### ISSUE THREAD

**Issue by lrouhier** [spinalcordtoolbox/spinalcordtoolbox#2470]
**Feature justification: Is your feature request related to a problem? Please describe.**
sct_deepseg_sc is not functioning really well on patients with compression of the spinal cord. 

**Describe the solution you'd like**
Further training on new images from patients suffering from spinal cord compression might help make the model more robust.

example:
only 3 slices were segmented on this image.
*path to image* : /duke/projects/ml_sci_prognosis/issue/issue_deepseg_\#2470
*version of sct*: Spinal Cord Toolbox (git-master-3da4b2697093d45969691fd3e48d1a2f85ddc197)
*command run*: sct_deepseg_sc -i axial_t2_ANU-004.nii -c t2 

![Screen Shot 2019-10-02 at 4 51 42 PM](https://user-images.githubusercontent.com/22171999/66080891-fa2faf80-e534-11e9-84ba-1468eee2e56d.png)

**Comment by jcohenadad** [comment]
Will be tackled by https://github.com/sct-pipeline/contrast-agnostic-softseg-spinalcord

**Comment by joshuacwnewton** [comment]
> Further training on new images from patients suffering from spinal cord compression might help make the model more robust.

As worded, I think this issue is a WONTFIX.

My reasoning is that we are unlikely to ever retrain the `sct_deepseg_sc` model specifically, because the underlying Keras code has been retired to `spinalcordtoolbox-dev`, and the current models have been fixed in the ONNX format. So, we're kind of stuck with the current performance of `sct_deepseg-sc`.

Plus, as far as I understand, any efforts towards improving spinal cord segmentation will likely involve separate efforts to train entirely new models (such as the softseg mentioned above).

(We could still have a separate issue for training a new model specifically tuned to images with spinal cord compression?  But, it might be better to wait and see how softseg performs first: https://github.com/sct-pipeline/contrast-agnostic-softseg-spinalcord/issues/47)

**Comment by jcohenadad** [comment]
> (We could still have a separate issue for training a new model specifically tuned to images with spinal cord compression? But, it might be better to wait and see how softseg performs first: https://github.com/sct-pipeline/contrast-agnostic-softseg-spinalcord/issues/47)

Exactly-- we will incorporate data with compression in our new model
