### ISSUE TITLE
Populate deepseg models and fill metadata fields

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#2695]
After introducing #2639, models need to be created with appropriate json metadata, notably the field `threshold` needs to be adjusted for each model.

**Comment by jcohenadad** [comment]
As discussed [here](https://github.com/neuropoly/ivado-medical-imaging/issues/193#issuecomment-613737279), a proposed solution is to separate json files depending on the task: inference, training, etc.

**Comment by joshuacwnewton** [comment]
If I'm understanding correctly, this is issue has been resolved, as we've been using `sct_deepseg` for several years at this point, and all available models come packaged with a `.json` file that describes postprocessing, etc.:

![image](https://user-images.githubusercontent.com/16181459/213549803-b91ccc19-cb11-45c0-9e6e-8a6288ecc47a.png)

I'm not sure that there's anything left to do here, since the ivadomed -> SCT pipeline is already fairly well-established at this point.

(I would assume we can also close the associated ivadomed issue? https://github.com/ivadomed/ivadomed/issues/193)
