### ISSUE TITLE
Update documentation for developers to package dependencies

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#2815]
here is the procedure: https://github.com/neuropoly/spinalcordtoolbox/issues/2669#issuecomment-665153804

**Comment by kousu** [comment]
I never documented it fully because I expected to quickly move through to having everything automated, with no need for documentation (beyond the build scripts themselves and comments therein). But I dropped the ball on this.

When the manual steps are documented I want to make sure there's a backlink to #2669 explaining the broader plan and that it's a temporary milestone.

**Comment by joshuacwnewton** [comment]
Oh! [I did this.](https://github.com/spinalcordtoolbox/spinalcordtoolbox/wiki/Packaging%3A-How-to-compile-C---binaries-(ANTs,-isct)) Closing! :smile:
