### ISSUE TITLE
Improvements to `sct_download_data`

### ISSUE THREAD

**Issue by Drulex** [spinalcordtoolbox/spinalcordtoolbox#2959]
Related to #2957, maybe #2788

This is an open discussion. Dumping ideas and thoughts below:

- Implement some kind of caching mechanism to avoid re-downloading the same data.
   - Should verify that data exists locally.
   - Should verify that local data integrity is ok.
   - This means that the data integrity should be published somewhere. Possibly in a manifest alongside the actual data. Alternatively on official website, github repo.
   - Don't really care about security.
- Some questions about current architecture:
   - Is there a reason for users to run `sct_download_data` manually or is usage only required by software? I am questioning if the user script should exist or if an API-only design is ok. Currently `pytest` would need it and in the future possibly `setup.py` as well.
   - Mirrors are currently in the application level (user script). This effectively prevents a piece of code from calling the API directly since it doesn't have access to the list of mirrors.

**Comment by Drulex** [comment]
Comments/ideas welcome @cfhammill @kousu @jcohenadad @joshuacwnewton.

I think that having some kind of manifest file listing the contents of the data package and associated versions and checksums (or similar) is a good idea.

If the data is already in git we could maybe get away without using a manifest depending on how it's packaged/released.

The manifest would definitely facilitate other processes that require some type of version tracking.

**Comment by kousu** [comment]
I prefer not maintaining an ad-hoc package manager. [This project](https://erpnext.com/) wrote [this package manager](https://github.com/frappe/bench) which is based on git and has some clever ideas, but it *only* integrates with [their web framework](https://github.com/frappe/frappe) meaning it's completely non-reusable, and installing their software is a very picky process -- it basically demands an Ubuntu VM, nothing else will do. I think that approach is annoying, and not very FLOSS-friendly (the key point of FLOSS, to me, is that you can readapt work without too many barriers), but I can live with it if we're upfront about it.

Better than that, I think we should make everything in the list [1] into packages under a more common package manager. I think our options in that direction are:

0. package ourselves as [nix packages](https://github.com/NixOS/nixpkgs/)
1. get packaged in [neurodebian](https://salsa.debian.org/neurodebian-team)
2. get packaged as a [conda feedstock](https://conda-forge.org/feedstocks/)
3. make everything into pip wheels

My lazy assumption has been that we're a python project so we should use pip, but there's some weaknesses to it: pip (/setuptools/distutils/whatever they're calling the suite of software that is python packaging now) doesn't specify enough of the system to reliably bind to and/or build the right extension modules, that's why everyone is always fighting with virtualenvs, and why conda was initially written.

On the other hand, by standardizing on a very widely used system like pip, we get to benefit from translator projects like [pip2nix](https://pypi.org/project/pip2nix/) that wraps a pip package into a nix environment (there's some [vaguer but similar tooling(https://docs.brew.sh/Homebrew-and-Python) for brew).

These are ordered from most stable to least stable platform. Neurodebian provides are very reliable platform, but at the cost of being very slow to upgrade software. pip is easy to update, but does. Nix, I think, combines the best of both, but at the cost of still being relatively obscure to users. conda is somewhere in the middle. I know if we chose to be conda-first we will make life difficult for deployment on HPC systems ([long, derailed, thread here](https://github.com/spine-generic/data-multi-subject/issues/5#issuecomment-675737552)).

[1]
https://github.com/neuropoly/spinalcordtoolbox/blob/2cf7545ba5f9f8756743b09fc68fe2b614c07111/scripts/sct_download_data.py#L71-L145

**Comment by kousu** [comment]
About integrity checking: pip (technically, pypi) has security mechanisms to limit uploading to someone on the original team, supports optional checksums (https://pip.pypa.io/en/stable/reference/pip_hash/) but you have to publish a checksum *per binary package* (per each wheel) which, and even supports package signing though [not](https://kushaldas.in/posts/pypi-and-gpg-signed-packages.html) [very well](https://dzone.com/articles/package-signing-in-pip-it-works-in-a-roundabout-so).

**Comment by Drulex** [comment]
Perhaps I should have scoped this issue better. I was focusing on the "unit test data download" aspect of `sct_download_data` while ignoring the others (in fact I hadn't really looked in details to see all that it was doing).

Maybe it makes sense to version track the test data inside `spinalcordtoolbox`. It is compact enough and we can easily check the integrity with `git`, thus removing one layer of complexity from the whole "data/package management" discussion.

I don't see any other dependency to "large" datasets for running the unit tests. What do you think @kousu ?

**Comment by Drulex** [comment]
As for the other use cases, let us take a step back and analyze if what is done is actually required. From what I can gather:

1. Download small datasets for unit testing -> See comment above, could be handled outside `sct_download_data` and be bundled with the repo directly.
2. Download binaries for Linux and OSX -> This sounds to me like an installation specific requirement. Do we ever need to "download platform specific binaries" during runtime? If not I suggest we remove this and handle this in the installation layer.
3. Download datasets/models for processing (large or not, basically optional datasets) -> Correct me if I'm wrong, but this is essentially downloading an archive, extracting it and checking the checksum (no need to resolve dependencies or perform platform specific stuff). We could:
    1. Shift the responsibility to the user: "Please download `x` from `dataset.com/x` and extract it into `/path/to/x`"
    2. Simple logic to check if it exists locally, otherwise `GET /path/to/dataset` + check integrity + extract to `/path/to/install`.

Do we need to do anything more complicated than this that would require us to move to proper package management?

**Comment by kousu** [comment]
>       * Is there a reason for users to run `sct_download_data` manually or is usage only required by software? I am questioning if the user script should exist or if an API-only design is ok. Currently `pytest` would need it and in the future possibly `setup.py` as well.

It's for example data! Stata's built in [package manager](https://www.stata.com/manuals/rnet.pdf) features a concept of "ancillary files", ones which get downloaded when you say `. net get ` instead of `. net install`. I've [used this](https://git.uwaterloo.ca/nguenthe/statasvm/-/blob/master/COMPILE.md#deployment) to share optional example scripts and datasets. My guess (@jcohenadad ?) is that that's how `sct_download_data` started out.

> Perhaps I should have scoped this issue better. I was focusing on the "unit test data download" aspect of `sct_download_data` while ignoring the others (in fact I hadn't really looked in details to see all that it was doing).

It's  `sct_download_data` that had some scope creep! It's now both a binary software package manager, a neural network image manager (which is..sort of like binary software? except it's a binary that run on a neural network emulator instead of x86), and a way to download sample data and it's confused for it.

**Comment by jcohenadad** [comment]
>  My guess (@jcohenadad ?) is that that's how sct_download_data started out.

`sct_download_data` started because we needed a way to control all the downloads: platform-specific binaries, testing/example data, and now deep learning models. 

what i like with the current approach (data managed in standalone repository) is that it is easier for contributors (usually students) to isolate a potentially-new dataset, without breaking SCT's flow. When the dataset is ready for production, we simply add an entry to `sct_download_data`. And the dataset keeps being version-tracked on a separate GH repository. I understand things could get better with a package manager, but I'm wondering if this is priority for now, given that `sct_download_data` works well and users got used to it?  If there is an "easy and more elegant" alternative, i'm happy to consider it (maybe in a prototype branch), but I could anticipate that things wouldn't go as smoothly. We could discuss that in a meeting (pls add to the agenda).

**Comment by kousu** [comment]
> As for the other use cases, let us take a step back and analyze if what is done is actually required. From what I can gather:
> 
>     1. Download small datasets for unit testing -> See comment above, could be handled outside `sct_download_data` and be bundled with the repo directly.

I'd be worried about creeping repo size. The bigger we make the repo the slower every installation, whether in CI or by user.  A submodule would be okay though.

>     2. Download binaries for Linux and OSX -> This sounds to me like an installation specific requirement. Do we ever need to "download platform specific binaries" during runtime? If not I suggest we remove this and handle this in the installation layer.

Agreed!

>     3. Download datasets/models for processing (large or not, basically optional datasets) -> Correct me if I'm wrong, but this is essentially downloading an archive, extracting it and checking the checksum (no need to resolve dependencies or perform platform specific stuff). We could:
>        
>        1. Shift the responsibility to the user: "Please download `x` from `dataset.com/x` and extract it into `/path/to/x`"
>        2. Simple logic to check if it exists locally, otherwise `GET /path/to/dataset` + check integrity + extract to `/path/to/install`.
> 
>     4. Download course content -> This should be done by the user. Provide link and let him download.

We might as well do 3 and 4 with some sort of tool too. Again, we could use submodules, or standardize on `datalad` as the dataset management tool.

I think the special thing about datasets is that they are independent and platform-agnostic, so they can be handled independently. The software in `bin/` is different because it needs to be  it needs to go through a compilation (and ideally, testing) step, and potentially has it own dependencies, and that all has to happen per platform. It's that extra metadata that we're struggling with.

**Comment by jcohenadad** [comment]
>    1. Shift the responsibility to the user: "Please download `x` from `dataset.com/x` and extract it into `/path/to/x`"

I would avoid that. I can already imagine a user installing SCT version X, then 6 months later a new model which only works with version X+1, and us trying to figure out what the problem is. So we need to "automatize" the installation of all dependencies when user installs SCT.

**Comment by kousu** [comment]
> > My guess (@jcohenadad ?) is that that's how sct_download_data started out.
> 
> `sct_download_data` started because we needed a way to control all the downloads: platform-specific binaries, testing/example data, and now deep learning models.

I vote separate tools for separate cases.

Deep learning models are a funny case. They're a *lot* like compiled software, but they're software whose interpreter is a particular network of tensors instead of a load-store machine. For now, they are "platform independent" because every platform we support has the same tensorflow (the interpreter) available. I think we could package them as if they were python.

I propose: `pip` for ANTS and ctrDetect, and neural network models, and `datalad` for datasets. Can we get `datalad`/`git-annex` installed in CI? Is that going to be a headache?

**Comment by joshuacwnewton** [comment]
Hmm.... this discussion started out with a [relatively small problem](https://github.com/neuropoly/spinalcordtoolbox/issues/2957#issuecomment-712139435) **("How can we preserve test data integrity without redownloading _every_ time?")** but we've arrived at a pretty big solution **("Scrap `sct_download_data` entirely and use other tools in its place.")** I do agree that `sct_download_data` does a lot, but... I think it might be good to step back, reel in the scope, and focus on just on solving the initial problem.

Here are the proposals I see in this thread: 

1. Create a manifest file listing the contents of `sct_testing_data` and associated versions and checksums. Initial download handled by `sct_download_data`. Integrity checking handled by a new function (I presume?).
2. Publish `sct_testing_data` as part of the `spinalcordtoolbox` repo. Initial download handled at installation. Integrity checking handled by `git`. (Q: How would we check integrity with git as part of pytest?)
3. Publish `sct_testing_data` using `datalad`/`git-annex`. Initial download handled by (?). Integrity checking handled by (?).
4. Publish `sct_testing_data` through pip/conda/nix/neurodebian. Initial download handled by (?). Integrity checking handled by (?).

My preference is towards smaller, incremental changes, and to only consider rebuilding from scratch if there was a big enough need (lest we bite off more than we can chew). @jcohenadad's https://github.com/neuropoly/spinalcordtoolbox/issues/2959#issuecomment-712389662 echoes my thoughts. Specifically:

> I understand things could get better with a package manager, but I'm wondering if this is priority for now, given that `sct_download_data` works well and users got used to it? 

Proposal 1 seems nice to me. Are there any big downsides/reservations with it?

**Comment by Drulex** [comment]
I think everyone here is making valid points. I understand that touching `sct_download_data` may have impacts on current functionalities and future ones as well. I propose to move this discussion to today's dev meeting for efficiency reasons.

We should at least aim to agree on the following:
- What are the true requirements?
- What is the urgency/priority of each requirement?

I'll update the meeting notes.

**Comment by Drulex** [comment]
Folowing Tuesday's meeting and some discussions with @kousu I started to explore the scope of effort required to package `sct` in a more conventional/standard way. See below my findings on the subject.

### Objectives (meeting recap): 
- To have a pip-installable package for `spinalcordtoolbox`.
- Should provide both `.whl` (pre-built wheel) and `sdist` (source build) options to adapt to different user needs. 
     - Motivation for `.whl`: wheels install faster, wheels are smaller than source distribution, wheels provide consistency -> regular users
     - Motivation for `sdist`: some users may want to use the source distribution to repackage for their platform, redistribute somewhere else than `pypi` or simply care about building from source -> users like Compute Canada
- The main package (`spinalcordtoolbox`) should not be bundled with external binaries or data (data for processing, models, test data).
     - Motivation: don't want to couple the update of external data to the update of the main package.
- External data should be packaged separately, but declared as a dependency of `spinalcordtoolbox`. 
     - Motivation: allows independent management of the external data while enforcing the dependency requirement and version compatibility (e.g `sct v5.1` works with `sct_example_data v2.1` and higher)
- The project code should be compatible with both the pip-installable method AND the self-contained install (`install_sct`) for users who don't want to bother with `pip`.

### Initial proposed solution:
- `spinalcordtoolbox` pip package providing wheel and sdist support. This includes only the core functionality (API code + scripts, no external binary or data).
- External data and binaries to be packaged separately and declared as dependencies to `sct`.
- Main package should be a pure python3 wheel (platform independent, python3-only)
- Only relevant dependencies (binaries) should be platform wheels (if we go this way), since they are the only platform dependent components.

### Challenges discovered:
- SCT distributes some platform-specific binaries as "dependencies", but they are in fact separate full-fledged applications that have simply been renamed. This non-standard approach causes some problems:
    - Problems with packaging: `setuptools` supports platform-dependent extensions using `ext_modules`, but that expects source code and not pre-compiled binaries.
         - Binaries can be bundled in a wheels package and installed using `data_files`, but that doesn't enforce platform specificity.
		 - Binaries can be built properly using `ext_modules` and packaged (as both sdist and wheel) in a platform-specific way, but that is not an ideal approach.
		      - It is not SCT's responsability to build, package and distribute someone else's application.
		      - Users normally install external application separately using the means provided by their environment package manager (e.g `apt`, `dnf`, `pacman`). Why should someone who already has `Ants` be forced to install it again and use the "repackaged" `sct` version?
		      - SCT should use external applications in a standard way (by calling the original application), not by calling a renamed bundled version. 
			  - Ideally, SCT should use external functionality via a provided interface (library) if it exists (e.g AntsPy)
- Packaging pure external data as wheels may or may not be the best way to approach this (it's convenient, but data is not python code).
- SCT has custom URLs for some dependencies (torch+cpu). These dependencie can only be installed if the user runs `pip install spinalcordtoolbox --upgrade -f https://download.pytorch.org/whl/cpu/torch_stable.html` vs the standard `pip install spinalcordtoolbox`.
- Once external data is decoupled from code, code needs to be refactored to remove assumptions (e.g some data paths are assumed using `sct_local_dir` where in reality the user should install the external data wherever he wants. External binaries are assumed to be in `$SCT_DIR/bin`, in reality they should just be used from the `$PATH`)
- Dependency to python3.6 because of `tensorflow==1.5.0`? -> `setuptools` does allow to specify interpreter compatibility via `python_requires`, but this is not convenient for a user. This requirement should be relaxed if possible.

### Final thoughts:
- Using the conventional standard approach is certainly feasible, but some changes will need to be made to stay compatible with the current "self-contained" installation method.
- Are there better ways to offer a "self-contained" no hassle install for users who just want the thing to work? Maybe:
   - Distro specific packaging
   - Docker image
   - SCT as a service where we control the environment (cloud)? -> semi-joking

@kousu feel free to correct if you think I messed up somewhere.

**Comment by jcohenadad** [comment]
Thank you for the nice and clear summary @Drulex! A few comments:

>It is not SCT's responsability to build, package and distribute someone else's application.
Users normally install external application separately using the means provided by their environment package manager (e.g apt, dnf, pacman). Why should someone who already has Ants be forced to install it again and use the "repackaged" sct version?

I see two pros:
- knowing our users, asking them to install ANTs will result in us spending time addressing ANTs installation issues (and given the small critical mass of our users and how precious they are, i obviously don't want to redirect them to the ANTs forum)
- we are 100% sure they are using the correct ANTs version

> Are there better ways to offer a "self-contained" no hassle install for users who just want the thing to work? Maybe:
Distro specific packaging
Docker image

I don't have a strong opinion on this. It would obviously be nice to be able to test prototypes of these packaging across various platforms.

**Comment by Drulex** [comment]
Thanks for the feedback @jcohenadad. Obviously we wouldn't want to sacrifice user experience. I gather that this whole packaging initiative may not add a lot of value to the current user base who are happy with what is there.

Perhaps a small improvement to `sct_download` can be done in parallel as exploring other potential solutions.

**Comment by kousu** [comment]
@mguaypaq and @joshuacwnewton and I had a brainstorming session. @joshuacwnewton wrote a very useful summary of the issues (is it okay if I share [the link](https://gist.github.com/joshuacwnewton/0bba9aeb69c00d54e57b189fcd081b8b) here)?

We are going to split into sub-issues:

1. Provide a download API to clean up the code: https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3902
2. Provenance tracing: moved to https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/2788
3. Integrity checking: moved to https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3901
4. Deprecating `sct_download_data` entirely: https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/2669
