### ISSUE TITLE
Use subparsers for sct_deepseg tasks

### ISSUE THREAD

**Issue by andreanne-lemay** [spinalcordtoolbox/spinalcordtoolbox#3054]
In this PR #3041, a new flag was introduced `-c` to indicate the modality of the input images. This is only required for multichannel.

Another option would be to use subparsers, one parser per task. This way we can have different flags depending on the task: 
`sct_deepseg <task> <task-specific options>`

Most flags are currently common to all tasks. In the future, if we have more tasks with specific needs, this option might be handy.

**Comment by joshuacwnewton** [comment]
> Most flags are currently common to all tasks. In the future, if we have more tasks with specific needs, this option might be handy.

It has been more than two years since this issue has been opened, and several new models have been added to `sct_deepseg`. However, so far, none have added additional complexity/options. Given that this was a speculative suggestion, and one that doesn't really apply to the current state of`sct_deepseg`, I'd like to close this for now?

But, with the caveat that we should definitely reconsider this approach should we ever introduce additional tasks with specific needs.

**Comment by jcohenadad** [comment]
> I'd like to close this for now?

👍
