### ISSUE TITLE
QC report for vertebral labeling is ridiculously small

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#3055]
When running a QC report based on an existing output labels for a T2*w data, the visual QC shows a very small image:
![Screen Shot 2020-11-20 at 10 25 15 AM](https://user-images.githubusercontent.com/2482071/99817372-d35a8100-2b1a-11eb-99a0-7f13324e1d6b.png)

In comparison, the T2w QC report looks good:
![Screen Shot 2020-11-20 at 10 25 23 AM](https://user-images.githubusercontent.com/2482071/99817418-e3726080-2b1a-11eb-95a1-7c48eb8a0894.png)

This problem might be due to the T2*w slice thickness being 4.5mm (instead of 0.8 for the T2w image).

### To reproduce
Data: [Archive.zip](https://github.com/neuropoly/spinalcordtoolbox/files/5574435/Archive.zip)

Syntax:
~~~
julien-macbook:~/Desktop/attachments $ sct_qc -i t2s_subj14.nii.gz -s t2_subj14_crop_r_seg_labeled_reg.nii.gz -p sct_label_vertebrae -qc qc 

--
Spinal Cord Toolbox (git-jca/3044-ants-sampling-770e37f8b25f3283ede65eb171501f55bf5416e5)

sct_qc -i t2s_subj14.nii.gz -s t2_subj14_crop_r_seg_labeled_reg.nii.gz -p sct_label_vertebrae -qc qc
--


*** Generate Quality Control (QC) html report ***
Resample images to NonexNone mm
QcImage: layout with Sagittal slice
Successfully generated the QC results in qc/_json/qc_2020_11_20_102454.385665.json
Use the following command to see the results in a browser:
open "qc/index.html"
~~~

**Comment by valosekj** [comment]
I came across the same issue with my T2*w image with 2.5mm slice thickness:

```
sct_qc -i sub-001_T2star.nii.gz -s label_t2star/template/PAM50_levels.nii.gz -p sct_label_vertebrae -qc ./results/qc -qc-subject sub-001
```

<img width="700" alt="Screenshot 2022-09-15 at 9 26 38" src="https://user-images.githubusercontent.com/39456460/191951288-09fffa00-dce1-4f0e-bd0e-b1d421b15537.png">


It looks that the issue is related to the plane setting `plane = 'Sagittal'` for the `sct_label_vertebrae` process:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/eb80678f970330214204d40ed14c59f5637c9977/spinalcordtoolbox/reports/qc.py#L805-L806

This in turn results in the following `size_fig` setting for .png figures:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/eb80678f970330214204d40ed14c59f5637c9977/spinalcordtoolbox/reports/qc.py#L334-L335

This is fine if the input image has a sagitall orientation (and thus `img.shape[0]` is same (or similar) to `img.shape[1]`, e.g. 896x896):

![sagittal](https://user-images.githubusercontent.com/39456460/191951387-a6d2425f-64cf-486b-ad29-4dd29e186f1e.png)

However, here we are creating QC for T2*w image, which has **axial** orientation (and thus `img.shape[0]` and `img.shape[1]` are far from being similar, e.g. 42x512):

![axial](https://user-images.githubusercontent.com/39456460/191951435-3ff59b1c-7f87-4578-9256-71a0f2142cb8.png)

Since `img.shape[1] / img.shape[0]` fraction for sagittally oriented images results in value close to `1`, a quick fix working for me is removal of this fraction:

```
# if sagittal orientation restrict height
elif slice_orientation == 'Sagittal':
    size_fig = [5, 5]
```

QC without the fraction looks much better. But still, there is a small bug with label annotation (the color labels are shifted relative to the black labels):

<img width="700" alt="Screenshot 2022-09-15 at 9 29 28" src="https://user-images.githubusercontent.com/39456460/191951453-7cc86a79-1258-425a-ad7e-09caf5c9e782.png">


This shift is caused by:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/eb80678f970330214204d40ed14c59f5637c9977/spinalcordtoolbox/reports/qc.py#L213-L214

A quick fix for me is commenting out these two lines or the usage of relative numbers derived from the image shape, like:

```
x -= y/500
y -= y/500
```

Resulting in:

<img width="700" alt="Screenshot 2022-09-23 at 13 28 24" src="https://user-images.githubusercontent.com/39456460/191951498-f10de364-be63-456d-814e-8c1419587476.png">

I tested this workaround also on the data provided in [the previous comment](https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3055#issue-747579095) resulting in:

![Screenshot 2022-09-23 at 13 39 25](https://user-images.githubusercontent.com/39456460/191952733-71a74ced-f850-44ab-8746-99b3d9388542.png)

**Comment by jcohenadad** [comment]
thank you for the investigation @valosekj ! could you please push your fix in a PR?
