### ISSUE TITLE
Lazy-load CLI scripts to reduce script execution time

### ISSUE THREAD

**Issue by joshuacwnewton** [spinalcordtoolbox/spinalcordtoolbox#3077]
>  **Note**: This issue has been created to document an old WIP pull request that had become stale. No issue had been opened for that PR, so this issue is to discuss whether it's worth starting fresh and continuing that work.

Before it was closed, PR #1913 had aimed to reduce script execution time by lazy-loading modules (i.e. by importing them in the middle of the script, rather than at the top). 

_(That PR also included some refactoring that turned some scripts into API modules, but I don't quite understand why those changes were included given the purpose of that PR.)_

Is this an idea worth pursuing again?

**Comment by jcohenadad** [comment]
> Is this an idea worth pursuing again?

I don't know... @zougloub @kousu @Drulex any insights?

**Comment by kousu** [comment]
It sounds like a nice idea. But would you be up to running profiling on it before diving in?

https://docs.python.org/3/library/profile.html#instant-user-s-manual

```
python -m cProfile -s cumulative scripts/sct_run_whatever.py
```

This line might not work as-is because of the weird way we install and import certain parts but I think you can probably get around that.

My rule of thumb is that python startup time is dominated by

1. the interpreter itself
2. large extension modules like matplotlib and scipy

**Comment by Drulex** [comment]
Relevant: https://github.com/ivadomed/ivadomed/issues/510
