### ISSUE TITLE
Command is "None" for QC report of sct_label_utils

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#3130]
### Description

When running `sct_label_utils -create-viewer` with qc flag, the generated report does not show the command parameter used:
![Screen Shot 2020-12-26 at 3 05 28 PM](https://user-images.githubusercontent.com/2482071/103158453-02a08580-478c-11eb-9682-2a5fa6cf792e.png)

To reproduce:
~~~
sct_label_utils -i sct_example_data/t1/t1.nii.gz -create-viewer 2,3 -o label.nii.gz -qc qc
~~~

**Comment by joshuacwnewton** [comment]
This issue was fixed at some point. 

![image](https://user-images.githubusercontent.com/16181459/212430998-5a540c40-7f44-4f15-abdc-47854a6c468a.png)

I can't identify the exact commit that fixed it, but I do know that these these types of bugs were double-checked in https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/3863/.
