### ISSUE TITLE
Single dash for arguments clashes with typical argparse usage

### ISSUE THREAD

**Issue by joshuacwnewton** [spinalcordtoolbox/spinalcordtoolbox#3159]
Historically (for both `msct_parser` and `argparse`), SCT has used  a single dash for all arguments (`sct_script -arg`), regardless of whether the argument is mandatory or optional. 

This goes against argparse's typical approach of _"mandatory -> positional arguments"_ and _"optional -> named arguments"_. Because of this, we've had to employ a number of separate workarounds:
* Using manual argument groups to denote `MANDATORY` and `OPTIONAL` argument groups.
* Removing the help then manually re-adding it to the optional/misc argument group.
* Our use of single-dash arguments also has an effect on subcommands, see: https://github.com/neuropoly/spinalcordtoolbox/issues/3154#issuecomment-758106788.

Moving away from single dash would be a nontrivial API change, however, so discussion is needed.

**Comment by Drulex** [comment]
Also relevant: https://github.com/neuropoly/spinalcordtoolbox/issues/2939

**Comment by Drulex** [comment]
Another topic that is related to this issue is the use (or lack thereof in this case) of sub-commands via argument sub-parsers (https://docs.python.org/3/library/argparse.html#argparse.ArgumentParser.add_subparsers). This would definitely benefit some scripts that have unconventional interfaces (using combinations of options) and unnecessary code to verify usage of the funky interface.

Mentioning it here, because sub-parsers aren't meant to be used with options so we would need to break the CLI interface and use positional arguments. Something to keep in mind.

**Comment by joshuacwnewton** [comment]
I think we can safely close this. SCT's single dash argument usage is deeply ingrained in documentation, user scripts, etc. And while it has its downsides, those downsides are well-understood. In truth, I don't believe this effort will ever be worth the effort.
