### ISSUE TITLE
Morphometric values are reported in slices that are not segmented

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#3402]
### Description

When using `sct_process_segmentation` on the segmentation attached below, the metrics are reported in the output CSV file for slices where no segmentation is present (ie: the slice is empty). 

Image of the segmentation showing that slice 3 is empty (ie: no segmentation):
![Screen Shot 2021-05-26 at 9 59 46 AM](https://user-images.githubusercontent.com/2482071/119673209-2e8e6880-be09-11eb-8b43-8b29470a1473.png)

And the output CSV, showing a morphometric value at slice 3:

Slice (I-&gt;S) | VertLevel | MEAN(area) | STD(area) | MEAN(angle_AP)
-- | -- | -- | -- | --
0 | &nbsp; | None | None | None
1 | &nbsp; | None | None | None
2 | &nbsp; | None | None | None
3 | &nbsp; | 45.49999186396620 | 0.0 | 0.0
4 | &nbsp; | 45.49999186396620 | 0.0 | 0.0
5 | &nbsp; | 55.81249001994760 | 0.0 | 0.0
6 | &nbsp; | 60.499989181757300 | 0.0 | 0.0

Interestingly, values for slices 3 and 4 are the same, which suggests a bug.

### Steps to Reproduce

0. Install SCT 77d4b7ddc716e69b1dc223536a7c026ff12abad8 (bug should appear with recent versions)

1. Download this data: [simple_avg_medic_oben_P06_month00_seg_corr.nii.gz](https://github.com/spinalcordtoolbox/spinalcordtoolbox/files/6547252/simple_avg_medic_oben_P06_month00_seg_corr.nii.gz)

2. Run:
   ```console
   sct_process_segmentation -i simple_avg_medic_oben_P06_month00_seg_corr.nii.gz -perslice 1 -angle-corr 0 -o csa_seg_gz_anglecorr0.csv 
   ```

**Expected behavior:** 
`MEAN(area)=None` at row=3

**Actual behavior:** <What actually happens>
`MEAN(area)=45.49999186396620`

**Comment by joshuacwnewton** [comment]
This is (at least partially) due to resampling done here:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/77d4b7ddc716e69b1dc223536a7c026ff12abad8/spinalcordtoolbox/process_seg.py#L48

After the resampling, slice z=3 has a very tiny nonzero value:

![Screenshot from 2021-05-26 11-15-05](https://user-images.githubusercontent.com/16181459/119685785-abbedb00-be13-11eb-9997-b1b90ca64683.png)

Even though the slice is ~0, the two checks we do for empty slices will interpret 4e-16 as non-empty:

1. In `compute_shape()` we use `nonzero()` to select slices.

    https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/77d4b7ddc716e69b1dc223536a7c026ff12abad8/spinalcordtoolbox/process_seg.py#L53-L56

2. And then, later on, in `_properties2d()` we use `any()` to check for empty slices.

    https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/77d4b7ddc716e69b1dc223536a7c026ff12abad8/spinalcordtoolbox/process_seg.py#L144-L147

So, metrics are computed for slice 3. And because we normalize the image to 0-1, the fact that the slice is ~0 doesn't matter for the actual metric calculation. :laughing: 

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/77d4b7ddc716e69b1dc223536a7c026ff12abad8/spinalcordtoolbox/process_seg.py#L148-L149
