### ISSUE TITLE
Unnecessary scary message about overwriting input file

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#3469]
### Description

When running `sct_detect_pmj`, the script copies the file to a temp directory, and then overwrite the image with the message:
~~~
File sub-100_ses-01_acq-middlespace_FLAIR.nii.gz already exists. Will overwrite it.
~~~

While the source image is _not_ overwritten, this message is scary for the user and it should be avoided. My suggestion is:
- we should check if the overwriting is really necessary
- if it is, we don't show the message to not unnecessarily scare the user (because the image is copied to a temp directory anyway, so nothing important gets overwitten).

<details><summary>Terminal output</summary>

```console
julien-macbook:~/data.neuro/msseg_challenge_2021/sub-100/ses-01/anat $ sct_detect_pmj -i sub-100_ses-01_acq-middlespace_FLAIR.nii.gz -c t1 -qc ~/qc-pmj -o pmj-master.nii.gz

--
Spinal Cord Toolbox (git-master-4f311bdd04c2ed76316cc5bd93ab9440b4dae598)

sct_detect_pmj -i sub-100_ses-01_acq-middlespace_FLAIR.nii.gz -c t1 -qc /Users/julien/qc-pmj -o pmj-master.nii.gz
--

Creating temporary folder (/var/folders/s8/4qnm5q1n261ch35b5kkclsb00000gn/T/sct-20210716164828.849839-o18m7oif)
cp sub-100_ses-01_acq-middlespace_FLAIR.nii.gz /var/folders/s8/4qnm5q1n261ch35b5kkclsb00000gn/T/sct-20210716164828.849839-o18m7oif
File sub-100_ses-01_acq-middlespace_FLAIR.nii.gz already exists. Will overwrite it.
sct_crop_image -i sub-100_ses-01_acq-middlespace_FLAIR.nii.gz -zmin 182 -zmax 183 -o sub-100_ses-01_acq-middlespace_FLAIR_midSag.nii # in /private/var/folders/s8/4qnm5q1n261ch35b5kkclsb00000gn/T/sct-20210716164828.849839-o18m7oif

Run PMJ detector
['isct_spine_detect', '/Users/julien/code/sct/data/pmj_models/t1_model', 'sub-100_ses-01_acq-middlespace_FLAIR_midSag', 'sub-100_ses-01_acq-middlespace_FLAIR_map_pmj']

Ponto-Medullary Junction detected
	x_pmj = 182
	y_pmj = 122
	z_pmj = 118

Save resulting file...
cp /var/folders/s8/4qnm5q1n261ch35b5kkclsb00000gn/T/sct-20210716164828.849839-o18m7oif/pmj-master.nii.gz /Users/julien/data.neuro/msseg_challenge_2021/sub-100/ses-01/anat/pmj-master.nii.gz
rm -rf /var/folders/s8/4qnm5q1n261ch35b5kkclsb00000gn/T/sct-20210716164828.849839-o18m7oif
```

</details>

**Comment by santoshdvc** [comment]
Hi, 
I get the idea that the following function call from `sct_detect_pmj` is causing the scary error message.
 https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/4f311bdd04c2ed76316cc5bd93ab9440b4dae598/spinalcordtoolbox/scripts/sct_detect_pmj.py#L236-L242

From the function call, the save function is being called at `image.py`  and exact lines are:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/9e642d0531d04ff59dd545351670229e3bb4075f/spinalcordtoolbox/image.py#L502-L505

But as their are only two conditions, either the file exist and need to be overwritten, or file doesn't exist. I could not understand what it means by "if the overwriting is really necessary". Am I missing something?

**Comment by jcohenadad** [comment]
maybe the call to "change orientation and save" could include "verbose=0" in the input param

**Comment by santoshdvc** [comment]
Hi @jcohenadad ,
Please check the pull request I created.

**Comment by joshuacwnewton** [comment]
> But as their are only two conditions, either the file exist and need to be overwritten, or file doesn't exist. I could not understand what it means by "if the overwriting is really necessary". Am I missing something?

My understanding was that the question means: "Why are we saving the image to the same filename twice? Is that really necessary?"

So, in this line:

 https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/4f311bdd04c2ed76316cc5bd93ab9440b4dae598/spinalcordtoolbox/scripts/sct_detect_pmj.py#L238-L239

The question is: "Would we be able to instead use this `PIR`-oriented image in later steps without having to save and reload the image?" 

I think the answer is "yes", but it would require some refactoring of the `DetectPMJ` class. Right now, my gut feeling is that the benefits of refactoring wouldn't be worth the effort. Especially considering that setting `verbose=0` is an quick solution. 

(But, maybe we could keep this in mind for #3457 and the idea in https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/3468#discussion_r671706822, since we would already be making changes to the class.)
