### ISSUE TITLE
Usage description does not properly wrap words

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#3485]
When displaying usage of a script, the description section shows cut words on the right edge of the Terminal window (red ellipse), while further down, in the list of arguments, the words are uncut (green ellipse):

![Screen Shot 2021-07-27 at 12 15 58 PM](https://user-images.githubusercontent.com/2482071/127190437-341cc333-a5ed-43e8-bff0-5d8cec825d0b.png)

I vaguely remember we are using a special parser class that deals with words wrapping, so we might want to tweak it so it can also apply to the usage description.

**Comment by joshuacwnewton** [comment]
Super easy fix. We just need to add `R|` to `sct_label_vertebrae`'s help description. 

![Screenshot from 2021-07-27 12-25-32](https://user-images.githubusercontent.com/16181459/127191393-d098b0a8-64e6-42a3-93e5-6d0bce5b1099.png)

**Comment by joshuacwnewton** [comment]
Ah! It turns out this was automatically fixed by the combination of #3361 and #3604, because `argparse.RawTextHelpFormatter` is now used by default on all descriptions:

![Screenshot from 2021-12-07 12-24-06](https://user-images.githubusercontent.com/16181459/145076818-6202a056-85c0-4b9a-bdfe-658007e70312.png)
