### ISSUE TITLE
Edit on GH button

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#3490]
before the change on the website we could conveniently edit on GH:

![Screen Shot 2021-07-30 at 8 43 36 AM](https://user-images.githubusercontent.com/2482071/127658686-abe1b7f2-25fe-4446-8e1b-f1e842868ad8.png)

it would be nice to have that option again

**Comment by ahill187** [comment]
I think it's a feature they're working on implementing in this theme: https://github.com/pradyunsg/furo/discussions/114

**Comment by ahill187** [comment]
Not as convenient, but you can get the link to edit on GitHub from the "On GitHub: View" option:

<img width="330" alt="rtd-edit-on-github" src="https://user-images.githubusercontent.com/23019211/127690228-b025f670-aec2-401c-a802-3d407c0f190d.png">

**Comment by joshuacwnewton** [comment]
Ah! @kousu came up with a solution for this in a separate context: [`_templates/topbar/repobutton.html`](https://github.com/neuropoly/neuro.polymtl.ca/blob/master/_templates/topbar/repobuttons.html)

I'm not sure if that file is theme-specific, or if we can just drop this page into our [`documentation/source`](https://github.com/spinalcordtoolbox/spinalcordtoolbox/tree/master/documentation/source) folder like magic, but it could just be an easy solution.

**Comment by kousu** [comment]
sphinx-book-theme came with that button built in. But I overrode it in order to make it one-click instead of two-clicks.

![2021-12-07-124012_1373x169_scrot](https://user-images.githubusercontent.com/987487/145079204-9a72afcf-0eb4-460f-97cb-9f9e4205eaa4.png)

Files in `_templates` *are* theme-specific: they override or extend specific files in a specific theme. So to adapt you'd have to dig around in [furo's src](https://github.com/pradyunsg/furo/tree/main/src/furo/theme/furo) to find where the topbar comes from and see what parts you can override, then copy-paste the existing file. `furo` doesn't have a [`repository_url` option like `sphinx-book-theme`](https://github.com/neuropoly/neuro.polymtl.ca/blob/e15bd0752738c45524233d0689c763e272e38e9b/conf.py#L74), so you'd have to hard-code the URL; but I bet there's a way to extend theme options.

I would love to see this figured out for `furo` because that button is the only blocker to https://github.com/neuropoly/neuro.polymtl.ca/issues/33, https://github.com/neuropoly/intranet.neuro.polymtl.ca/issues/22
