### ISSUE TITLE
`libgcc_s.so.1 must be installed for pthread_cancel to work` during SCT's post-install validation

### ISSUE THREAD

**Issue by gaspardcereza** [spinalcordtoolbox/spinalcordtoolbox#3511]
### Description

When submitting our `Shimming-Toolbox` Pull Request to the CI, we get an error that seems to be related to the installation of `SCT`. These tests were passing a few days ago and we have not modified our PR since then, so it seems to come from `SCT`'s end.

This happens with [this PR](https://github.com/shimming-toolbox/shimming-toolbox/pull/295/checks?check_run_id=3499425571) and [this one](https://github.com/shimming-toolbox/shimming-toolbox/actions/runs/1191672436). 

The bug happens when testing under `Ubuntu-18.04 3.8`.

<details>
  <summary>See error output</summary>
  
```
Spinal Cord Toolbox (git-master-666237aeb31246ff163905c7f3cf6cbe8d696e44)

sct_check_dependencies 
--

SCT info:
- version: git-master-666237aeb31246ff163905c7f3cf6cbe8d696e44
- path: /home/runner/work/spinalcordtoolbox
OS: linux (Linux-5.4.0-1056-azure-x86_64-with-debian-buster-sid)
CPU cores: Available: 2, Used by ITK functions: 2
RAM: Total: 6954MB, Used: 495MB, Available: 6128MB
Check Python executable.............................[OK]
  Using bundled python 3.6.13 |Anaconda, Inc.| (default, Jun  4 2021, 14:25:59) 
[GCC 7.5.0] at /home/runner/work/spinalcordtoolbox/python/envs/venv_sct/bin/python
Check if data are installed.........................[OK]
Check if colored is installed.......................[OK] (1.4.2)
Check if dipy is installed..........................[OK] (1.4.1)
Check if futures is installed.......................[OK]
Check if h5py is installed..........................[OK] (2.10.0)
Check if Keras (2.1.5) is installed.................[OK] (2.1.5)
Check if ivadomed is installed......................[OK] (2.8.0)
Check if matplotlib is installed....................[OK] (3.3.4)
Check if nibabel is installed.......................[OK] (3.2.1)
Check if numpy is installed.........................[OK] (1.19.5)
Check if onnxruntime (1.4.0) is installed...........[OK] (1.4.0)
Check if pandas is installed........................[OK] (1.1.5)
Check if psutil is installed........................[OK] (5.8.0)
Check if pyqt5 (5.11.3) is installed................[OK] (5.11.3)
Check if pytest is installed........................[OK] (6.2.5)
Check if pytest-cov is installed....................[OK] (2.12.1)
Check if raven is installed.........................[OK]
Check if requests is installed......................[OK] (2.26.0)
Check if requirements-parser is installed...........[OK] (0.2.0)
Check if scipy is installed.........................[OK] (1.5.4)
Check if scikit-image is installed..................[OK] (0.17.2)
Check if scikit-learn is installed..................[OK] (0.24.2)
Check if tensorflow (1.5.0) is installed............[OK] (1.5.0)
Check if torch (1.5.0+cpu) is installed.............[OK] (1.5.0+cpu)
Check if torchvision (0.6.0+cpu) is installed.......[OK] (0.6.0+cpu)
Check if xlwt is installed..........................[OK] (1.3.0)
Check if tqdm is installed..........................[OK] (4.62.2)
Check if transforms3d is installed..................[OK] (0.3.1)
Check if urllib3 is installed.......................[OK] (1.26.6)
Check if pytest_console_scripts is installed........[OK]
Check if wquantiles is installed....................[OK] (0.4)
Check if spinalcordtoolbox is installed.............[OK]
Check ANTs compatibility with OS ...................[OK]
Check PropSeg compatibility with OS ................[OK]
Check if figure can be opened with matplotlib.......Generating new fontManager, this may take some time...
libgcc_s.so.1 must be installed for pthread_cancel to work
./install_sct: line 738:  3219 Aborted                 (core dumped) sct_check_dependencies

Installation validation Failed!


Installation failed!

Please copy the output of this Terminal (starting with the command install_sct) and upload it as a .txt attachment in a new topic on SCT's forum:

--> http://forum.spinalcordmri.org/c/sct

Error: Process completed with exit code 1.
```
</details>

### Steps to Reproduce

Follow [this link](https://github.com/shimming-toolbox/shimming-toolbox/actions/runs/1191672436) and hit the `Re-run jobs` button.

**Expected behavior:** 

All the tests should pass. 

**Actual behavior:**

The `Ubuntu-18.04 3.8` test fails and cancels the execution of all the other tests.

**Comment by joshuacwnewton** [comment]
Thanks for bringing this to our attention! It looks like this is affecting SCT's main test suite, too: https://github.com/spinalcordtoolbox/spinalcordtoolbox/actions/runs/1193916964

This also looks likes a recent change, as SCT's recurring cron job was fine prior to today: https://github.com/spinalcordtoolbox/spinalcordtoolbox/actions

Investigating further...

**Comment by joshuacwnewton** [comment]
[Diffing the install logs](https://www.diffchecker.com/VgTFwLAR), the biggest change I notice is an update from `ivadomed 2.7.4` to `ivadomed 2.8.0`. I presume this also lead to updates from ivadomed's dependencies, as well. Identifying this doesn't exactly get us closer to figuring out the precise cause, but at least I can try quickly running the test suite with `ivadomed==2.7.4` pinned just to see if that isolates the problem.

Apart from that, a cursory look into the error message yields many different reports across the internet (see: https://github.com/ContinuumIO/anaconda-issues/issues/9190), but these reports describe the problem as brittle, intermittent, and hard to reproduce. Again, not too helpful for getting to the root cause, but I'll continue to read up on the various reports.

**Comment by joshuacwnewton** [comment]
Apart from that, a cursory look into the error message yields many different reports across the internet (see: https://github.com/ContinuumIO/anaconda-issues/issues/9190), but these reports describe the problem as brittle, intermittent, and hard to reproduce. Again, not too helpful for getting to the root cause, but I'll continue to read up on the various reports.

**Comment by joshuacwnewton** [comment]
Curiously, I tried [skipping `sct_check_dependencies`](https://github.com/spinalcordtoolbox/spinalcordtoolbox/commit/3e1ed41683545f56dc6921e123c82dd47adc1a1f) and running the test suite as-is. [It passes!](https://github.com/spinalcordtoolbox/spinalcordtoolbox/runs/3501413679?check_suite_focus=true)

The good news, then, is that the actual installation of SCT doesn't appear to be broken. Instead, it seems to me that the problem is in some way connected to _the way we import `matplotlib` in `sct_check_dependencies`_. This is similar to what's described in https://github.com/ContinuumIO/anaconda-issues/issues/9190.

> importing
> 
> ```
> import PyQt5.Qt; import matplotlib.pyplot
> ```
> 
> raises,
> 
> ```
> libgcc_s.so.1 must be installed for pthread_cancel to work
> ```
> 
> Importing these packages **in orther order or separately** works fine.

This will be a finicky thing to nail down. The more I read reports on this error, the more I suspect we won't get a conclusive answer for what the cause is... But we can do our best to mitigate things. :slightly_smiling_face:

**Comment by joshuacwnewton** [comment]
> It seems to me that the problem might be in some way connected to _the way we import `matplotlib` in `sct_check_dependencies`_.

Aha! Currently, in `sct_check_dependendecies`, we...

1. [Import `PyQt` first](https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/666237aeb31246ff163905c7f3cf6cbe8d696e44/spinalcordtoolbox/scripts/sct_check_dependencies.py#L264-L272), then we...
2. [Import `matplotlib.pyplot` afterwards](https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/666237aeb31246ff163905c7f3cf6cbe8d696e44/spinalcordtoolbox/scripts/sct_check_dependencies.py#L325). 
 
This is the exact import order that was reported to cause this error in https://github.com/ContinuumIO/anaconda-issues/issues/9190. 

So, I tried importing `matplotlib.pyplot` _before_ PyQt in https://github.com/spinalcordtoolbox/spinalcordtoolbox/commit/8334247507478cbd616df98094d89255dd76edd0. As a result, the [error disappears completely](https://github.com/spinalcordtoolbox/spinalcordtoolbox/actions/runs/1196272210). So, in the short-term, hooray! We have a workaround. :tada:

**Comment by joshuacwnewton** [comment]
What I still don't understand:

* Why did [these specific package changes](https://www.diffchecker.com/16bXTM3T) trigger the issue in the first place?
* Why were the [Debian 9, Debian 10, Ubuntu 18.04, and CentOS 7](https://github.com/spinalcordtoolbox/spinalcordtoolbox/actions/runs/1193916964) GitHub Actions runners affected, but not the other runners?

Still, hopefully this provides some new data points for hopefully reproducing the issue.

**Comment by gaspardcereza** [comment]
Thanks for the investigation @joshuacwnewton ! I hope your PR will fix the problem because our CI is currently not very useful...  Let me know if you need any help with this matter.
