### ISSUE TITLE
Wrong behaviour of `fitseg` algorithm: the output centerline is not extrapolated

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#3531]
### Description

Usage says:

~~~
  -method {optic,viewer,fitseg}
                        Method used for extracting the centerline.
                          - optic: automatic spinal cord detection method
                          - viewer: manual selection a few points followed by interpolation
                          - fitseg: fit a regularized centerline on an already-existing cord segmentation. It will
                          interpolate if slices are missing and extrapolate beyond the segmentation boundaries (i.e., every
                          axial slice will exhibit a centerline pixel). (default: optic)
~~~

So, we expect the fitseg method to extrapolate the centerline _outside_ of the segmentation zmin/zmax, but it does not:

![image](https://user-images.githubusercontent.com/2482071/135947488-f596d04b-9994-4054-b4c1-8ebc8fa6e12e.png)

### Steps to Reproduce

0. Install SCT 666237aeb31246ff163905c7f3cf6cbe8d696e44

1. Download: [sag_cervical_seg.nii.gz](https://github.com/spinalcordtoolbox/spinalcordtoolbox/files/7282226/sag_cervical_seg.nii.gz)

2. Run:
   ~~~
   sct_get_centerline -i sag_cervical_seg.nii.gz -method fitseg -o sag_cervical_centerline
   ~~~

### Another minor issue

The usage should mention "(default: optic)" before the bullet point, not at the end of the fitseg description.

**Comment by joshuacwnewton** [comment]
A user on the forum recognized this issue, resulting in the following discussion between the user and @jcohenadad:
> > **[kuech](https://forum.spinalcordmri.org/u/kuech)**: This works quite well in the slices were I have the binary mask but I get empty slices for the last 1-2 slices where the cord ended. According to the help message of the function this should not happen:
> > ```
> > - fitseg: fit a regularized centerline on an already-existing cord segmentation. It will 
> >   interpolate if slices are missing and extrapolate beyond the segmentation boundaries 
> >   (i.e., every axial slice will exhibit a centerline pixel).
> > ```
> **[jcohenadad](https://forum.spinalcordmri.org/u/jcohenadad)**: You are absolutely correct, the help mentions extrapolation, but the fitseg algorithm only does interpolation (ie: find points between two points), not extrapolation (ie: find points outside of a range of points). In the past, the extrapolation was possible, but it caused other issues, so we decided to remove it and forgot to update the help message. Given the need for extrapolation, we will probably create a new flag “-extrapolate”, which will do what is explained in the help message (by default it will be turned off to not break retro-compatibility). Thank you for noticing this issue! For now, a quick fix for you is to add the segmentation at the edge slices.

Regarding the following quote:

> In the past, the extrapolation was possible, but it caused other issues, so we decided to remove it

- PR [#2646](https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/2646) (April 1, 2020): `-fitseg` is introduced, including its description that mentions "extrapolation".
- However, I can't find any PRs that _removed_ extrapolation from the centerline methods. I am wondering if this description has been inaccurate ever since it was introduced?

**Comment by joshuacwnewton** [comment]
Regardless, there are two main tasks here:

- [ ] Update the faulty description to remove any mention of "extrapolation". (Easy)
- [ ] Introduce extrapolation to the various `-fitseg` methods in the `get_centerline` function. (More involved)

**Comment by sandrinebedard** [comment]
I've tested changing the parameter `minmax`  to `False` `https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/7aef973ef9cc8908fd2114693245da822c5a0e80/spinalcordtoolbox/scripts/sct_get_centerline.py#L162

Here is the result for this segmentation provided in the issue:
[centerline_minmax.nii.gz](https://github.com/spinalcordtoolbox/spinalcordtoolbox/files/11063484/centerline_minmax.nii.gz)
Since it is bspline interpolation, this is why the extrapolation is super curved. 

With linear: 
[centerline_minmax_linear.nii.gz](https://github.com/spinalcordtoolbox/spinalcordtoolbox/files/11063552/centerline_minmax_linear.nii.gz)

With Polyfit: 
[centerline_minmax_polyfit.nii.gz](https://github.com/spinalcordtoolbox/spinalcordtoolbox/files/11063556/centerline_minmax_polyfit.nii.gz)



The main difference is that the `z_ref `will include all slices of the FOV instead of only the slices in the segmentation:
https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/7aef973ef9cc8908fd2114693245da822c5a0e80/spinalcordtoolbox/centerline/core.py#L136-L141

Afterwards, inside the interpolation:
`z_ref `(now called `x_ref`) is used, (for all fits, not just Bspine)
For Bspine:
https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/7aef973ef9cc8908fd2114693245da822c5a0e80/spinalcordtoolbox/centerline/curve_fitting.py#L53

From what I understand, it is just the prolongation of the fit that is mapped to the rest of the z_ref. I don't know if it is the behaviour we want. When we use a higher degree interpolation, such as bspline or polyfit, the extrapolation can vary a lot, dependent on the curvature of the cord, etc.

@mguaypaq do you want to take a look of the code?

**Comment by jcohenadad** [comment]
> From what I understand, it is just the prolongation of the fit that is mapped to the rest of the z_ref. I don't know if it is the behaviour we want. When we use a higher degree interpolation, such as bspline or polyfit, the extrapolation can vary a lot, dependent on the curvature of the cord, etc.

Thank you @sandrinebedard ! I think this is the behaviour we want. And as you rightfully noted, for high polynomial degrees, the fitted region "outside" of the control points might look crazy, which is probably why we turned off this feature. But it doesn't hurt to put it back via a flag
