### ISSUE TITLE
FSLeyes script doesn't work :-( 

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#3533]
### Description

I've tried running our sct_script on FSLeyes as a "script", but it failed:

<img width="532" alt="Screen Shot 2021-10-07 at 4 38 18 PM" src="https://user-images.githubusercontent.com/2482071/136461571-94ad00f2-d451-4a33-baad-bfac60815673.png">

### Steps to Reproduce

~~~
julien-macbook:~ $ which fsleyes
/Users/julien/opt/miniconda3/bin/fsleyes
julien-macbook:~ $ fsleyes --version
fsleyes/FSLeyes version 1.2.0
julien-macbook:~ $ sct_version
git-master-666237aeb31246ff163905c7f3cf6cbe8d696e44
~~~

**Comment by joshuacwnewton** [comment]
Aha! We've run into this issue before [on SourceForge](https://sourceforge.net/p/spinalcordtoolbox/discussion/help/thread/e1c8a8f6/), surprisingly enough. The conclusion from that issue was:

> It seems that you don't have a required image called `logo_sct.png` that is present inside the directory `/documentation/imgs` of SCT.

So, this error is thrown when the SCT logo image is missing. Currently, the image path points here:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/67221f3fce0327e3af99c1e522a1d0c26eb38ade/contrib/fsl_integration/sct_plugin.py#L272

But the image is stored in [`$SCT_DIR/documentation/source/_static/img/logo_sct_small.png`](https://github.com/spinalcordtoolbox/spinalcordtoolbox/tree/master/documentation/source/_static/img) instead.

----

What's odd to me is... if this _is_ the problem, then why didn't it fail for me? The logo seems to display clearly when I load the script, so... how is it being found? :thinking:

**Comment by joshuacwnewton** [comment]
Super weird... I just tried loading the script a second time and _now_ I can reproduce:

![Screenshot from 2021-10-10 13-52-43](https://user-images.githubusercontent.com/16181459/136707608-3d776bd2-2708-42bf-942a-c5adc94af2c9.png)

![Screenshot from 2021-10-10 13-52-54](https://user-images.githubusercontent.com/16181459/136707609-1685ff13-1a5d-4202-a5e8-c51c8db2cf9d.png)

**Comment by joshuacwnewton** [comment]
@jcohenadad One other small note -- for future FSLeyes errors, if you check the terminal where you ran `fsleyes`, the full traceback will be displayed:

```
 WARNING         runscript.py  107: __doAction      - Script (/home/joshua/repos/spinalcordtoolbox/contrib/fsl_integration/sct_plugin.py) could not be executed: C++ assertion ""image.IsOk()"" failed at /home/conda/feedstock_root/build_artifacts/wxpython_1616628590026/work/ext/wxWidgets/src/gtk/bitmap.cpp(640) in wxBitmap(): invalid image
Traceback (most recent call last):
  File "/home/joshua/miniconda3/lib/python3.9/site-packages/fsleyes/actions/runscript.py", line 101, in __doAction
    runScript(self.__frame,
  File "/home/joshua/miniconda3/lib/python3.9/site-packages/fsleyes/actions/runscript.py", line 169, in runScript
    exec(code, _globals)
  File "/home/joshua/repos/spinalcordtoolbox/contrib/fsl_integration/sct_plugin.py", line 789, in <module>
    run_main()
  File "/home/joshua/repos/spinalcordtoolbox/contrib/fsl_integration/sct_plugin.py", line 774, in run_main
    panel_propseg = TabPanelPropSeg(parent=notebook)
  File "/home/joshua/repos/spinalcordtoolbox/contrib/fsl_integration/sct_plugin.py", line 404, in __init__
    super(TabPanelPropSeg, self).__init__(parent=parent, id_=wx.ID_ANY)
  File "/home/joshua/repos/spinalcordtoolbox/contrib/fsl_integration/sct_plugin.py", line 287, in __init__
    sct_logo = self.get_logo()
  File "/home/joshua/repos/spinalcordtoolbox/contrib/fsl_integration/sct_plugin.py", line 331, in get_logo
    png = wx.Image(logo_file,
  File "/home/joshua/miniconda3/lib/python3.9/site-packages/wx/core.py", line 756, in _Image_ConvertToBitmap
    bmp = wx.Bitmap(self, depth)
wx._core.wxAssertionError: C++ assertion ""image.IsOk()"" failed at /home/conda/feedstock_root/build_artifacts/wxpython_1616628590026/work/ext/wxWidgets/src/gtk/bitmap.cpp(640) in wxBitmap(): invalid image
```
