### ISSUE TITLE
Provide a YouTube video demonstrating how to install SCT

### ISSUE THREAD

**Issue by joshuacwnewton** [spinalcordtoolbox/spinalcordtoolbox#3578]
Idea suggested by SCT Course participants who are currently having difficulty with the existing installation steps.

**Comment by RignonNoel** [comment]
@joshuacwnewton If you want I can work on that, I already did it for others projects and I have the tool to record the screen and video edit the output.

I could prepare a plan, review it with you, do the video and edition and after that we could put it on Youtube and mark the big steps so the video is easy to use and split for watcher.

That said, do you have an idea how we will maintain that in the future ? Does the sct-install change a lot latelly or in the near future ?

**Comment by joshuacwnewton** [comment]
> That said, do you have an idea how we will maintain that in the future ?

This is the biggest downside to creating videos for SCT, for sure! Video documentation is tricky to maintain. :sweat: 

As a developer, I would personally prefer not creating video tutorials for this reason, as I would much prefer sticking to text-only. But, my preferences are not necessarily our users' preferences, so it might be good to go along with it anyway? :thinking:

**Comment by joshuacwnewton** [comment]
As an aside, I'm realizing that this issue is a duplicate of https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/592.

**Comment by RignonNoel** [comment]
@joshuacwnewton Ahah, didn't saw ALL these duplicata! 😄 

The discussion you had on these issues seems to be always around the same problem: **keeping video up-to-date**.

I propose to put some real effort on the video conception phase in order to cut it into little section that we can replace individually in the future or re-edit with new little info when needed.

If the user's ask for it, we are better to be organized and find the best solution to solve it rather than refuse it. Especially since it is often the newcomers who are looking for videos to reassure them.

**Comment by joshuacwnewton** [comment]
> As an aside, I'm realizing that this issue is a duplicate of #592.

I'm not sure why I didn't close this as a duplicate at the time, but I'm doing this now.
