### ISSUE TITLE
Wrong measures for lesion length

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#3633]
### Description

Estimation of lesion length can be wrong. 

This issue was raised by a user on the forum: https://forum.spinalcordmri.org/t/negative-values-with-sct-analyze-lesion/794

### Steps to Reproduce

```console
sct_download_data -d sct_testing_data
cd sct_testing_data/t2
# create fake lesion spanning 4 voxels
sct_label_utils -i t2.nii.gz -create 29,27,25,1:29,28,25,1:29,29,25,1:29,30,25,1 -o lesion.nii.gz
# run morphometrics
sct_analyze_lesion -m lesion.nii.gz -s t2_seg-manual.nii.gz -i t2.nii.gz 
```

**Expected behavior:**
~~~
  Volume [mm^3] = 4.0+/-0.0
  (S-I) Length [mm] = 4.0
  Equivalent Diameter [mm] = 1
~~~

**Actual behavior:** <What actually happens>
~~~
  Volume [mm^3] = 4.0+/-0.0
  (S-I) Length [mm] = -0.93+/-0.0
  Equivalent Diameter [mm] = -0.0+/-0.0
~~~

### Possible issues

I suspect the issue is related to a wrong estimation of objects that are one voxel wide. Deeper investigations are warranted, and appropriate unit tests should be developed.

### Bonus changes

We could also take this opportunity to output CSV instead of XSL, and PKL

**Comment by mguaypaq** [comment]
The immediate cause seems to be [this line in the script](https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/f068452c43e19669faca45c222f3d6fca60ca743/spinalcordtoolbox/scripts/sct_analyze_lesion.py#L443), which wrongfully converts an angle from radians to degrees:
```python3
            self.angles[iz] = math.degrees(angle)
```
I'll investigate more to check that the computation is correct, but already just fixing this seems to give the right lesion length:
```
Averaged measures...
  Volume [mm^3] = 4.0+/-0.0
  (S-I) Length [mm] = 4.0+/-0.0
  Equivalent Diameter [mm] = 0.56+/-0.0

Total volume = 4.0 mm^3
Lesion count = 1
```
I haven't yet looked into the "Equivalent Diameter" computation, which says 0.56 instead of 1, as in the "expected behavior" in the issue description.

**Comment by mguaypaq** [comment]
As for changing the output from XSL and PKL to CSV:
- We could probably start outputting CSV as an additional format in the next minor release.
- We could stop outputting XSL and PKL in the next major release (since this is not backwards compatible).
- When supplying an atlas/template with the `-f` option, the script produces an XSL spreadsheet with multiple sheets, which isn't directly supported by CSV. Presumably in that case, we would output a separate CSV file for each sheet?

**Comment by mguaypaq** [comment]
Ok, for the equivalent diameter, there's one thing which is certainly an error, and a second thing which I need more context to see if it's an error:
- The output says it's computing diameter, but it's computing radius instead (so, half of the right value). This is certainly a mistake.
- The computation uses the centerline angle, which may or may not be correct, depending on what the number is supposed to mean. Is there a definition somewhere of what "Equivalent Diameter" is supposed to mean in the context of spinal cord lesion analysis?

**Comment by mguaypaq** [comment]
I'll note as well, that it's possible to get refactoring inspiration from the old attempt in #2682.

**Comment by joshuacwnewton** [comment]
> I'll note as well, that it's possible to get refactoring inspiration from the old attempt in #2682.

Oh! Of course, how could I forget. Thank you for catching that there was an existing PR for this. 

I wonder if that PR is too far out of date now to be salvageable. :thinking:

**Comment by joshuacwnewton** [comment]
For organizational purposes, I've created #3691 to avoid this issue representing 2 separate ideas.
