### ISSUE TITLE
Update versioning guidelines in Github PR template and wiki

### ISSUE THREAD

**Issue by mguaypaq** [spinalcordtoolbox/spinalcordtoolbox#3730]
Given [the nice discussion of versioning we recently had](https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/3700#discussion_r819869323), we should update the following line in the Github PR template (and the linked wiki page; currently the linked anchor doesn't exist):

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/2c2a662baf6eadc0c28711886ec354a4c8d14016/.github/PULL_REQUEST_TEMPLATE.md?plain=1#L11

**Comment by joshuacwnewton** [comment]
Done! :)  --> https://github.com/spinalcordtoolbox/spinalcordtoolbox/wiki/Misc%3A-Creating-a-new-release#convention-for-naming-releases

(Thanks for catching that broken link!)

I linked to the comment (rather than copying/pasting the reasons themselves) just for the sake of keeping things brief, but perhaps it would be better to inline that part too. 🤔
