### ISSUE TITLE
actions/checkout@v2 step is failing for Arch/DebianRR CI runners: "Error: fatal: unsafe repository"

### ISSUE THREAD

**Issue by joshuacwnewton** [spinalcordtoolbox/spinalcordtoolbox#3769]
I've re-run the failed jobs, yet I'm still seeing this error. But, oddly, only for [Arch](https://github.com/spinalcordtoolbox/spinalcordtoolbox/runs/6026411449?check_suite_focus=true) and [Debian Rolling Release](https://github.com/spinalcordtoolbox/spinalcordtoolbox/runs/6026411773?check_suite_focus=true)?

```
Initializing the repository
  /usr/bin/git init /__w/spinalcordtoolbox/spinalcordtoolbox
  hint: Using 'master' as the name for the initial branch. This default branch name
  hint: is subject to change. To configure the initial branch name to use in all
  hint: of your new repositories, which will suppress this warning, call:
  hint: 
  hint: 	git config --global init.defaultBranch <name>
  hint: 
  hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
  hint: 'development'. The just-created branch can be renamed via this command:
  hint: 
  hint: 	git branch -m <name>
  Initialized empty Git repository in /__w/spinalcordtoolbox/spinalcordtoolbox/.git/
  /usr/bin/git remote add origin https://github.com/spinalcordtoolbox/spinalcordtoolbox
  Error: fatal: unsafe repository ('/__w/spinalcordtoolbox/spinalcordtoolbox' is owned by someone else)
  To add an exception for this directory, call:
  
  	git config --global --add safe.directory /__w/spinalcordtoolbox/spinalcordtoolbox
   ::remove-matcher owner=checkout-git::
  ##[debug]Removed matchers: 'checkout-git'
  Error: The process '/usr/bin/git' failed with exit code 128
  ##[debug]Node Action run completed with exit code 1
  ##[debug]Finishing: Run actions/checkout@v2
```

I'm wondering if it has to do with the fact that we just merged a PR from the fork of an external contributor (https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/3766)? Either way, though, it's sort of fishy that it only failed for those two runners. 🤔

**Comment by joshuacwnewton** [comment]
I thought "hmm, maybe I should restart _all_ jobs instead of just the failed jobs, just in case it was a fluke that Arch/DebianRR were the only ones to fail"... but nope. Both of them are the only ones that are failing. So weird.

![image](https://user-images.githubusercontent.com/16181459/163423490-464268eb-4de0-4072-a65b-e190ae65448b.png)

**Comment by joshuacwnewton** [comment]
Maybe there was an upstream change to `git`, and the fact that both Arch and Debian RR use bleeding-edge versions of dependencies means they got the newest upstream `git` version, but not the other runners?

Time to go poke around `git`'s changelogs. :V

**Comment by joshuacwnewton** [comment]
Ah, the issue is widespread: https://github.com/actions/checkout/issues/760

**Comment by kousu** [comment]
Yeah I think it's gotta be an upstream git change. Looks like [this one](https://git.kernel.org/pub/scm/git/git.git/commit/?id=8959555cee7)

> setup_git_directory(): add an owner check for the top-level directory
It poses a security risk to search for a git directory outside of the
directories owned by the current user.
>
> For example, it is common e.g. in computer pools of educational
institutes to have a "scratch" space: a mounted disk with plenty of
space that is regularly swiped where any authenticated user can create
a directory to do their work. Merely navigating to such a space with a
Git-enabled `PS1` when there is a maliciously-crafted `/scratch/.git/`
can lead to a compromised account.
>
> The same holds true in multi-user setups running Windows, as `C:\` is
writable to every authenticated user by default.
>
> To plug this vulnerability, we stop Git from accepting top-level
directories owned by someone other than the current user. We avoid
looking at the ownership of each and every directories between the
current and the top-level one (if there are any between) to avoid
introducing a performance bottleneck.
>
> This new default behavior is obviously incompatible with the concept of
shared repositories, where we expect the top-level directory to be owned
by only one of its legitimate users. To re-enable that use case, we add
support for adding exceptions from the new default behavior via the
config setting `safe.directory`.

The other thing is that our Arch and Debian sid run *inside of Docker*. So that's an extra complication. I wonder if docker is spawning as one user and running the checkout as another?

**Comment by kousu** [comment]
of course, it's this: https://github.blog/2022-04-12-git-security-vulnerability-announced/

**Comment by joshuacwnewton** [comment]
Looks like the tests have begun [passing on `master` again.](https://github.com/spinalcordtoolbox/spinalcordtoolbox/runs/6064774974?check_suite_focus=true) :)
