### ISSUE TITLE
`sct_deepseg` colour-coding appears as grayscale on Command Prompt

### ISSUE THREAD

**Issue by joshuacwnewton** [spinalcordtoolbox/spinalcordtoolbox#3780]
The color-coding appears as two subtly different shades of gray:

![image](https://user-images.githubusercontent.com/16181459/164739063-ef608dbd-4eeb-412c-a32d-e32be0ca5c03.png)

Color works in other contexts on Windows, though. e.g. `sct_check_dependencies`:

![image](https://user-images.githubusercontent.com/16181459/164739157-54a4a331-ce8b-4917-8bf7-24c696381f9d.png)

**Comment by jcohenadad** [comment]
oh! good thing you're reporting that issue. The color coding is supposed to be green: installed, red: not installed.  In your case, the color coding is too subtle to be useful unfortunately, so that's something (minor) we need to fix.

Here's how it looks on my terminal:

<img width="1337" alt="image" src="https://user-images.githubusercontent.com/2482071/164759483-211dc956-7a5b-4b38-b262-b20c645dd8e9.png">

**Comment by joshuacwnewton** [comment]
It looks like the reason this fails is because of our use of the `colored` library, [which doesn't support Windows](https://gitlab.com/dslackw/colored/-/issues/11). 

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/0c4f3c1581cde784d3a9e2b2c3bfa9ffb639bbcf/spinalcordtoolbox/deepseg/models.py#L230-L231

Thankfully, for our purposes, using `colored` is a bit overkill (since we only need 2 colors, and are only ever stylizing the foreground colors). 

So, I think we can safely drop the `colored` module, and stick to hardcoding the color codes, which is what we do for `sct_check_dependencies` and elsewhere:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/0c4f3c1581cde784d3a9e2b2c3bfa9ffb639bbcf/spinalcordtoolbox/scripts/sct_check_dependencies.py#L141-L142

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/0c4f3c1581cde784d3a9e2b2c3bfa9ffb639bbcf/spinalcordtoolbox/scripts/sct_check_dependencies.py#L37
