### ISSUE TITLE
Extend `-create-viewer` to allow users to create compression disc labels (all `1` values)

### ISSUE THREAD

**Issue by valosekj** [spinalcordtoolbox/spinalcordtoolbox#3984]
## Feature justification

Within our `metric-normalization / automatic compression detection` [project](https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/3977), we are looking for an optimal way, how to store the information about the level/slice of the SC compression.
It would be great to have a nii file containing single point(s) (non-zero voxels) corresponding to individual compression(s) (one patient usually has more than one compression). It could be something similar as in case of `disc-labels`, where individual non-zero voxels corresponds to individual intervertebral discs.

Points for a discussion:
- voxel values - if more than one compression is presented, which voxel value to set? `1` for the first compression, `2` for the second compression, etc.? Or the same value (`1`) across all compressions.
- a single compression can cover several slices. In such cases, it will be necessary to label all affected slices. [Such approach we currently use in our draft](https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/983114df0692e8c237c39a3c6ff21af8fb2a7447/spinalcordtoolbox/scripts/sct_compute_mscc.py#L53-L58). But instead of nii file, we use txt file.
- how to effectively label the compressions across a large dataset? One possibility might be to extend the [current viewer](https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/6ee19076472c7e42da1e15b4483ff0720772df27/spinalcordtoolbox/scripts/sct_label_utils.py#L344) used for disc labeling.

**Comment by jcohenadad** [comment]
I like the voxel value approach because:
- it can be used later on to train models 
- xxx

However, we should not do '1', '2' , etc because the concept of "first/second compression" is relative. And there is no pros in distinguishing with different labels. So: we keep single voxel of value: '1' for each compression detected. So if there are two compressions: one voxel at each compression. --> we need feedback from Allan. 

in case a compression site spans multiple slices along the superior-inferior direction (which is often the case), the reported voxel will be that corresponding to the most compressed location. However, if there is a distal second compression (eg: at another level), another voxel will be done.

**Comment by valosekj** [comment]
> However, we should not do '1', '2' , etc because the concept of "first/second compression" is relative. And there is no pros in distinguishing with different labels. So: we keep single voxel of value: '1' for each compression detected. So if there are two compressions: one voxel at each compression.

What do you thing about something like this?

![sub-twh018](https://user-images.githubusercontent.com/39456460/210909852-a72b7463-192b-46b6-8447-cc20b8e9b0af.gif)

**Comment by joshuacwnewton** [comment]
Given that this issue is more of a brainstorming discussion pertaining to the compression detection project, and given that the discussion seems to have reached a conclusion, can we consider this resolved? (Then continue any further discussion in:)

- https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/3946
- https://github.com/neuropoly/idea-projects/issues/2
- https://github.com/neuropoly/idea-projects/issues/4

**Comment by valosekj** [comment]
> given that the discussion seems to have reached a conclusion, can we consider this resolved? 

Agree, thank you!

**Comment by joshuacwnewton** [comment]
I'm reopening this issue because I had skipped over what @valosekj had written here:

> * how to effectively label the compressions across a large dataset? One possibility might be to extend the [current viewer](https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/6ee19076472c7e42da1e15b4483ff0720772df27/spinalcordtoolbox/scripts/sct_label_utils.py#L344) used for disc labeling.

As far as I understand, there is not currently a way for users to use `sct_label_utils -create-viewer` to create compression labels (all 1s). 

I believe this feature would be necessary for users to try out `sct_compute_compression` in https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/4003?

**Comment by valosekj** [comment]
> As far as I understand, there is not currently a way for users to use `sct_label_utils -create-viewer` to create compression labels (all 1s).

Exactly, currently, `sct_label_utils -create-viewer` does not allow to create multiple labels with the same value (i.e., three labels with value `1`).

**Comment by joshuacwnewton** [comment]
It isn't perfect, but there's a workaround that I used in the context of #4003:

```bash
# Identify compression sites using labels
# NB: These steps are a workaround since -create-viewer can't create multiple labels with the same value 
sct_label_utils -create-viewer 1 -i sub-twh018_T2w.nii.gz -o labels1.nii.gz
sct_label_utils -create-viewer 1 -i sub-twh018_T2w.nii.gz -o labels2.nii.gz
sct_label_utils -create-viewer 1 -i sub-twh018_T2w.nii.gz -o labels3.nii.gz
sct_maths -i labels1.nii.gz -add labels2.nii.gz labels3.nii.gz -o sub-twh018_T2w_compression_labels.nii.gz
```

Also, @sandrinebedard mentioned to me that FSLeyes can also be used to create such labels.

So, perhaps this more of a low-priority feature, given that the internal needs of the lab are currently satisfied?

**Comment by valosekj** [comment]
A smart workaround, indeed!

> Also, @sandrinebedard mentioned to me that FSLeyes can also be used to create such labels.

Exactly. And sometimes, FSLeyes is even better for this purpose because it allows overlaying several contrasts/images (e.g., sagittal and axial), which helps in compression identification in complicated cases where compression is not apparent from a single image.

> So, perhaps this more of a low-priority feature, given that the internal needs of the lab are currently satisfied?

Agree.

**Comment by valosekj** [comment]
After a discussion during the 2023-03-23 SCT meeting, we concluded that it would be better to place the compression labels in the middle of the spinal cord like this:

https://user-images.githubusercontent.com/39456460/228329678-4ba5e8e1-8aed-4419-9cbb-84043ce635de.mov

The location of disc labels in the middle of the spinal cord eliminates the need for the projection of the labels to the SC centerline.

**Comment by joshuacwnewton** [comment]
Since the format for compression labels has been settled (repeated `1` labels, middle of the spinal cord), and we are no longer moving forward with the `-create-viewer` functionality for creating duplicate `1` labels, I'm closing this issue as resolved.
