### ISSUE TITLE
Output of `sct_image -header` does not match the output of `fslhd`

### ISSUE THREAD

**Issue by valosekj** [spinalcordtoolbox/spinalcordtoolbox#3991]
During the debug for https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3992, I found out that `sct_image -i <image> -header fslhd` (and also `sct_image -i <image> -header`) provides a different `qform` than `fslhd <image>`:

```console
$ sct_image -i sub-zurichDCM022_acq-cspineAxial_T2w.nii.gz -header fslhd >> sct_header
$ fslhd sub-zurichDCM022_acq-cspineAxial_T2w.nii.gz >> fsl_header
$ vim -d sct_header fsl_header    
```

![image](https://user-images.githubusercontent.com/39456460/211641117-5b05a37c-5b77-4ec0-840e-58fc99ceeb3b.png)

**Comment by jcohenadad** [comment]
@valosekj thank you for reporting this (these) issue. To me, there are two issues:
- INSPIRED data with unmatched sform/qform, causing labeling to crash --> this is not specific to SCT, but should be addressed in the context of the INSPIRED project. I suggest adding a step in the preprocessing where qform/sform are matched.
- sct_image doesn't provide the same result than fslhd --> this is highly problematic and is definitely an SCT issue. I suggest renaming this current issue to reflect the problem specifically.
- labeling crashing if qform/sform are not the same --> also an SCT issue. We could potentially provide a fix to it by adding a "copy qform to sform" before doing the labeling. I _think_ we already do that for our segmentation functions

**Comment by joshuacwnewton** [comment]
> * I suggest renaming this current issue to reflect the problem specifically.

Done! Other issues moved to #3992.

**Comment by joshuacwnewton** [comment]
I'll look into the header display mismatches promptly. :)

**Comment by joshuacwnewton** [comment]
The values of `qform` and `sform` come from the getter methods of nibabel's `Nifti1Header` objects;

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/a15070f635264ad05aae41db83ce31160600e930/contrib/fslhd.py#L190-L191

In this case, the direct output of these methods is:

<details>
<summary> sform </summary>

![image](https://user-images.githubusercontent.com/16181459/211847646-f3bffd73-da95-4617-a767-8a0204e7441e.png)

</details>

<details>
<summary> qform </summary>

![image](https://user-images.githubusercontent.com/16181459/211847688-8212b2b5-fb68-4d99-b349-f3bf0bc5e0f0.png)

</details>

Because the differences come directly from third party libraries (and not SCT), I would have to dig into how `nibabel` determines the `qform`, and how that method differs from how `fslhd` determines the `qform`.

**Comment by jcohenadad** [comment]
> Because the differences come directly from third party libraries (and not SCT), I would have to dig into how nibabel determines the qform, and see how that method differs from how fslhd determines the qform.

Maybe before digging we can simply report it on the [FSL mailing list](https://www.jiscmail.ac.uk/cgi-bin/webadmin?A0=FSL). maybe they are already aware of this problem (and if not they should)

**Comment by joshuacwnewton** [comment]
> Maybe before digging we can simply report it on the [FSL mailing list](https://www.jiscmail.ac.uk/cgi-bin/webadmin?A0=FSL). maybe they are already aware of this problem (and if not they should)

Good point. I could also ask on the nibabel side of things, too. :)

**Comment by joshuacwnewton** [comment]
Given the explanation from https://github.com/nipy/nibabel/issues/1181#issuecomment-1379182783:

> If we replace that value with 0 and run through the rest of get_qform(), we get the same values as fslhd.

I think we have just enough information to replicate FSL's behavior in `sct_image -header`.

(The only trouble is, right now we're inferring FSL's behavior -- we don't know the exact threshold that FSL uses. So, it would be good to get confirmation from FSL from the mailing list before implementing something new in `sct_image -header`.)

**Comment by joshuacwnewton** [comment]
It looks like `nibabel` will be shipping an upstream fix that will address this issue.

The only concern I have here is that nibabel just shipped v5.0.0 four days ago, meaning that it may be some time until they release a new version. (Will that version be released before our v6.0.0 in March? I'm unsure...)

That said, I think it's safe to leave this for now, then check in closer to March to see if the issue has resolved itself upstream.

**Comment by joshuacwnewton** [comment]
The nibabel PR https://github.com/nipy/nibabel/pull/1182 has been merged. This issue should be automatically fixed on SCT's end once `nibabel` releases a new version.

We can probably just close this issue as completed, but I think I'm going to leave this issue open, just so we're reminded to check in closer to the release of v6.0.

**Comment by joshuacwnewton** [comment]
Nibabel released v5.0.1 last week. However, the upstream fix is not included in this release, likely because it is a behavior change.

I am assuming, then, that the fix will be made available in the `5.1.x` series of releases... which will likely not be released in time for SCT v6.0.

Given the delay, I can take the upstream fix and put it directly into our `header.py` module, for us to later remove when nibabel v5.1 is released?

**Comment by mguaypaq** [comment]
After some offline discussion, it seems like temporarily patching nibabel's `header.py` module would be more trouble than it's worth, so we might as well just be patient and wait for nibabel 5.1 to be released.

**Comment by effigies** [comment]
FWIW I plan to release 5.1.0 next week.
