### ISSUE TITLE
`sct_get_centerline -method fitseg` - allow to output soft centerline

### ISSUE THREAD

**Issue by valosekj** [spinalcordtoolbox/spinalcordtoolbox#4012]
## Feature justification

Within the [centerline detection](https://github.com/neuropoly/idea-projects/issues/15) project, we use [`sct_get_centerline -method fitseg`](https://github.com/ivadomed/model_sc_centerline/blob/70f6e189fde93070e917bd96175266bf7c426d14/scripts/get_centerline_from_segmentation.sh#L90-L92) to obtain SC centerline from existing ground truth SC segmentations in order to train a DL model for centerline detection. 

Currently, `sct_get_centerline -method fitseg` outputs binarized centerline. But, for DL training, it would be beneficial to have a probabilistic (soft) centerline (i.e., values can lie between 0 and 1) as well.

Possibly related to https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/4006

**Comment by joshuacwnewton** [comment]
This issue was brought up in the [2023-01-26](https://docs.google.com/document/d/1ItApJQfajO2lRzOU2yenWbeRg6alfsdut3J4AVVdo78/edit#heading=h.2xefygcyqgee) SCT meeting, and it was suggested that this might be as simple as a one-line change (updating to linear interpolation). 

See the `-centerline-algo` parameter, which is applied to `-method fitseg`:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/2d09af3ee707ca166c3d1611295a7575ffdd4cd0/spinalcordtoolbox/scripts/sct_get_centerline.py#L61-L66

**Comment by naga-karthik** [comment]
Thanks @valosekj for digging into the code! Indeed these lines are the culprit for binarized outputs. 
```console

im_centerline.data[round_and_clip(x_centerline_fit, clip=[0, im_centerline.data.shape[0]]), 
                    round_and_clip(y_centerline_fit, clip=[0, im_centerline.data.shape[1]]), 
                    z_ref] = 1 
```

> If we used in this step the float centerline coordinates to set the intensity of the surrounding voxels to interval 0 to 1, we could obtain a soft segmentation.

Following up on this - there is the question of "how many" surrounding coordinates we should consider to get the soft segmentation. One suggestion is to use 3 voxels per extracted centerline coordinate - one would the `.floor()`, one would be the `.ceil()` and the third would be the original (un-rounded, float) coordinate whose intensity we set as 1. In code, this looks something like:

```python

# setting the floor value to 0.5
im_centerline.data[x_centerline_fit.floor(), y_centerline_fit.floor(), z_ref] = 0.5

# setting the actual centerline coordinate to 1
I’m_centerline.data[round(x_centerline_fit), round(y_centerline_fit), z_ref] = 1.0
# TODO: make sure that rounded centerline does not overlap with the ceil or floor 

# setting the ceil value to 0.5
im_centerline.data[x_centerline_fit.ceil(), y_centerline_fit.ceil(), z_ref] = 0.5

```

This is just one suggestion of how we can go about this. Again, I'm not sure if hardcoding the surrounding coordinates to 0.5 is reasonable but is better than outputting binarized centerlines as we currently do.

**Comment by jcohenadad** [comment]
Ah! I see the issue. I thought the algorithm was providing the value of the centerline in float (ie as a nx,ny,nz matrix form), but instead it gives the continuous coordinates for each z. So, it will take more than a line of code 😅.

A suggestion for an algorithm would be to fill up the value for each voxel around the coordinate, accounting for partial volume (which is what linear interpolation is). Example (for 1d only, can be easily generalized to 2d):

coordinate = 35.4 --> x=35, value=0.4 | x=36, value=0.6.

This is, of course, assuming that the coordinate of a voxel is at its center. Eg: a coordinate of 35.0 would yield x=35, value=1.0.

This needs to be verified, because I _think_ the NIfTI format considers the origin of a voxel to be at its corner.
