### ISSUE TITLE
Remove `-list-tasks` and display the available tasks in the argparse help

### ISSUE THREAD

**Issue by joshuacwnewton** [spinalcordtoolbox/spinalcordtoolbox#4047]
> _Originally posted by @jcohenadad in https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/4042#pullrequestreview-1308428736_

I suggest we display all tasks within the help, because most of the time we forget the name of the task, and we end up doing:

 * `sct_deepseg -h`
 * `sct_deepseg -list-tasks`
 * copy/paste the task in the Terminal
 * `sct_deepseg -task TASK`

**Comment by co-decode** [comment]
Hi @joshuacwnewton, I've been looking at the [argparse docs](https://docs.python.org/3/library/argparse.html) in relation to this issue and issue #4007 . 

It seems possible to adapt the `display_list_tasks()` function in `spinalcordtoolbox/deepseg/models.py` to return a string, rather than writing to the console. The returned string could then be used as the value for the [`epilog`](https://docs.python.org/3/library/argparse.html#epilog) argument of the SCTArgumentParser in `spinalcordtoolbox/scripts/sct_deepseg.py`. This would append the formatted table of tasks to the end of the argparse help.

Let me know if this could be an acceptable solution and I'd be happy to write it up.

**Comment by joshuacwnewton** [comment]
I think that your proposed addition makes perfect sense!

----

One thing to consider, though, is line length + wrapping. Currently, the output of `-list-tasks` is quite long, but the text isn't wrapped in any way, so the user can extend their terminal even after running `-list-tasks` and still see the output:

<details>

![image](https://github.com/spinalcordtoolbox/spinalcordtoolbox/assets/16181459/fcfcc066-74f4-44e4-ad10-ff6c839f83ac)

![image](https://github.com/spinalcordtoolbox/spinalcordtoolbox/assets/16181459/7fecea15-86bb-473a-b0cc-bb1000dd80bb)

</details>

However, I believe argparse applies some text wrapping / re-formatting, which may mess up the layout of the table.

If that happens, then I might suggest an additional change. Remove the "model" column from the output of `-list-tasks`, then move the "model" information into `-list-tasks-long`.

This will help greatly for condensing the table and making it more viewable as part of `epilog`. (Since, IMO, the model information is less critical, and can be viewed as part of the longer descriptions of the tasks.)

(In fact, we may even be able to remove the `contrast` column too, since the task name/description often contains the contrast information as well.)
