### ISSUE TITLE
`sct_register_multimodal` does not generate QC when no segmentation is provided

### ISSUE THREAD

**Issue by valosekj** [spinalcordtoolbox/spinalcordtoolbox#4076]
### Description

`sct_register_multimodal` does not generate a QC html report when no segmentation is provided

Commands:

```console
$ sct_download_data -d course_london20
$ cd $SCT_DIR/data/course_london20/multi_subject/data/sub-01/anat
$ sct_register_multimodal -i sub-01_acq-MToff_MTS.nii.gz -d sub-01_acq-MTon_MTS.nii.gz -qc qc -qc-subject sub-01
```

CLI output:

```
...
WARNING: Cannot generate QC because it requires destination segmentation.
...
```

It would be great if the QC was generated even when no segmentation was provided.
For example, for some datasets, we are co-registering two scans using `-identity 1` without specifying SC seg; example [here](https://github.com/sct-pipeline/dcm-metric-normalization/blob/04480b719e05b8a8c7ed7fc5710d1a062f074f05/scripts/process_data_dcm-zurich.sh#L148).

**Comment by joshuacwnewton** [comment]
AFAIK, the segmentation is  used to crop around the spinal cord so that the axial slice mosaic shows the correct part of the image. In fact, some scripts even include a `-qc-seg` argument to specifically provide a separate segmentation for cropping purposes. 

As you say, though, it would be nice if there was some way to avoid this requirement, e.g. by running a segmentation algorithm internally on the destination image then passing that to `generate_qc`.

At the very least, in the short term, it would be good to throw an error if `-qc` is provided without `-dseg` (to avoid running through the entire processing only to realize that no QC is produced).

**Comment by valosekj** [comment]
> At the very least, in the short term, it would be good to throw an error if `-qc` is provided without `-dseg` (to avoid running through the entire processing only to realize that no QC is produced).

This is an excellent point! I added such a feature in https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/4078.

---

I also realized that if I add `-dseg` to the [example](https://github.com/sct-pipeline/dcm-metric-normalization/blob/04480b719e05b8a8c7ed7fc5710d1a062f074f05/scripts/process_data_dcm-zurich.sh#L148) with `-identity 1` mentioned in the [first comment](https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/4076#issue-1639846670), the `-dseg` is used only for the QC report. Which is exactly what I need. Example:

```console
valosek@macbook-pro:~/data/data.neuro.polymtl.ca/dcm-zurich/sub-584531/anat$ sct_register_multimodal -i sub-584531_acq-sagittal_T2w.nii.gz  -d sub-584531_acq-axial_T2w.nii.gz -identity 1 -x nn -qc qc -qc-subject sub-294305 -dseg sub-584531_acq-axial_T2w_label-SC_mask-manual.nii.gz
```
