### ISSUE TITLE
`sct_resample -mm` might produce output image with different pixdim than specified

### ISSUE THREAD

**Issue by valosekj** [spinalcordtoolbox/spinalcordtoolbox#4077]
### Description

`sct_resample -mm` might produce an output image with a slightly different pixdim than specified by the `-mm` flag due to rounding.

### Example

Let's say we want to resample the following [PAM50_200um_Naxons.nii.gz](https://github.com/spinalcordtoolbox/PAM50/blob/master/histology/PAM50_200um_Naxons.nii.gz) image:

```console
$ sct_image -i PAM50_200um_Naxons.nii.gz -header | grep dim | head -2
dim		[3, 258, 198, 205, 1, 1, 1, 1]
pixdim		[-1.0, 0.083333, 0.083333, 0.5, 0.0, 0.0, 0.0, 0.0]
```

using `sct_resample -i PAM50_200um_Naxons.nii.gz -mm 0.2x0.2x0.5 -x linear`

When `sct_resample` is used with the `-mm` flag, a new image shape is computed by the following line:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/7aef973ef9cc8908fd2114693245da822c5a0e80/spinalcordtoolbox/resampling.py#L80

For `sct_resample -mm 0.2`, we get `107.5000344`:

$$ NewDim = {Dim * {PixDim \over NewPixDim}} $$

$$ NewDim = {258*{0.083333 \over 0.2}} $$

$$ NewDim = 107.5000344 $$

Which is consequently rounded by `np.round` to 108.

This then leads to shifting to `0.199074138` when `nibabel.processing.resample_from_to` is run:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/7aef973ef9cc8908fd2114693245da822c5a0e80/spinalcordtoolbox/resampling.py#L115-L116

$$ NewPixDim = {PixDim * {Dim \over NewDim}} $$

$$ NewPixDim = {0.083333 * {258 \over 108}} $$

$$ NewPixDim = 0.199074138 $$

**The new pixdim is `0.199074138` instead of desired `0.2`.**

Related to: https://github.com/spinalcordtoolbox/PAM50/issues/7#issuecomment-1483304937

**Comment by joshuacwnewton** [comment]
As far as I understand, this behavior is expected?

To be able to represent exactly 0.2mm resolution, the calculated image `x_dim` is `107.5`. But, since we are limited to a discrete voxel grid, the best we can do is either `108` or `107`. This means that we can only ever be slightly above or below 0.2mm resolution, but never exact.

(In other words, the bulk of the precision loss is introduced by the `np.round` call, but this call is necessary to ensure we are use integer voxel coordinates.)

**Comment by valosekj** [comment]
> As far as I understand, this behavior is expected? I don't think it's mathematically possible to get exactly 0.2mm resolution.

Exactly!

> Assuming my reasoning is correct here, then it might be good to add a note to the `-resample` help description, saying something like:
> 
> ```
> NB: Resampling can only approximate a desired `mm` resolution, given the limitations of discrete voxel data arrays.
> ```

Good idea!

**Comment by mguaypaq** [comment]
> I don't think it's mathematically possible to get exactly 0.2mm resolution.

It's certainly impossible to have all three of:
* the input size is an integer (e.g., 258 voxels),
* the output size is an integer (e.g., 107 or 108 voxels),
* the resampling ratio is exactly as asked (e.g., 0.083333mm / 0.2mm).

But, it's also possible to have a different trade-off, for example:
* keep the same input size, because that's fixed (e.g. 258 voxels),
* use the exact resampling ratio (e.g., 0.083333mm / 0.2mm),
* then the output size is _not_ an integer (e.g., 107.5), but we can _crop_ the fractional part.

That's the theory, but in practice I would have to dig into nibabel and scipy to see whether this is easily done with their APIs.

I imagine resampling is useful because people want to compare images from different sources, which might have both different sizes and different resolutions. I'm not sure whether people care more about having matching sizes or matching resolutions, but I wanted to point out that there's a choice here.

As a side point, with the current code, note that the output resolution can be pretty sensitive to the input size. For example, cropping or padding the input image by a few voxels would give the following output resolutions:
```
input voxels = 255: output resolution = 0.20047089622641512
input voxels = 256: output resolution = 0.1993761495327103
input voxels = 257: output resolution = 0.20015496261682245
input voxels = 258: output resolution = 0.2009337757009346
input voxels = 259: output resolution = 0.19984487962962963
input voxels = 260: output resolution = 0.20061648148148148
input voxels = 261: output resolution = 0.1995404862385321
```
