### ISSUE TITLE
Bug install via Docker Ubuntu Command Failed

### ISSUE THREAD

**Issue by tzebre** [spinalcordtoolbox/spinalcordtoolbox#4100]
When running `./install_sct` got this Error message: 

```
 non-interactive mode

[0;32m
*******************************
* Welcome to SCT installation *
*******************************
[0m


[0;32mChecking OS type and version...[0m

Linux 91d7437ddc81 5.15.49-linuxkit #1 SMP PREEMPT Tue Sep 13 07:51:32 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux

[0;32mChecking requirements...[0m


[0;32mOK![0m


SCT version ......... 6.0.dev0
Installation type ... in-place
Operating system .... linux (unknown)
Shell config ........ /root/.bashrc

[0;32mSCT will be installed here: [/sct][0m


[0;32mSkipping copy of source files (source and destination folders are the same)[0m


[0;32m--> Crash reports will not be sent.[0m


[0;32mDownloading Miniconda...[0m


[0;34mcurl -sS -o /tmp/tmp.DhNPouBGE2/miniconda.sh -L https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh[0m


[0;32mInstalling Miniconda...[0m


[0;34mbash /tmp/tmp.DhNPouBGE2/miniconda.sh -p /sct/python -b -f[0m

PREFIX=/sct/python
Unpacking payload ...
qemu-x86_64: Could not open '/lib64/ld-linux-x86-64.so.2': No such file or directory

[0;31mERROR: Command failed.[0m


[0;31mInstallation failed!

Please find the file "/sct/install_sct_log.txt",
then upload it as a .txt attachment in a new topic on SCT's forum:
--> http://forum.spinalcordmri.org/c/sct[0m


```

I solved this problem by running  `docker run -it --platform linux/amd64 ubuntu` instead of `docker run -it ubuntu`

**Comment by joshuacwnewton** [comment]
Thank you so much for reporting this issue! (Also, thank you so much for providing the solution you found! :heart:)

I have two main questions:

- Which device/OS are you using outside of the Docker container? (Is it a Mac M1 device?)
   - I ask because the `--platform linux/amd64` solution seems to be [tied to M1 macs](https://stackoverflow.com/questions/65612411/forcing-docker-to-use-linux-amd64-platform-by-default-on-macos). And, if that's the case, we will need to update our [Docker installation instructions for macOS](https://spinalcordtoolbox.com/user_section/installation/mac.html?highlight=docker#basic-installation-no-gui), which have gotten quite a bit out of date.
- Which Docker configuration did you use? (Did you simply `docker pull` the base Ubuntu image, run the container in interactive mode, then `git clone`+install SCT normally? Or, did you use a more complex Dockerfile?)

Thank you!
