### ISSUE TITLE
Change relative PATH for absolute PATH in example script

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#4146]
While helping a user (https://forum.spinalcordmri.org/t/multimodal-registration/1097), I noticed that our batch example script has relative PATH pointing to SCT installation:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/e740edf4c8408ffa44ef7ba23ad068c6d07e4b87/batch_processing.sh#L114

Obviously, if SCT PATH does not match this relative PATH, the file won't be found.

So, I suggest we replace the relative PATH with $SCT_DIR.

I am wondering how this has never been an issue before (ie: some users must have run into an issue?), and why this has been implemented in the first place 🤔

**Comment by joshuacwnewton** [comment]
This was implemented because the Windows-based installation does not set `$SCT_DIR`, and so the batch processing script fails on Windows. (It is trickier to set environment variables on Windows, requiring manual steps through the Windows GUI -- currently we only instruct users to update the $PATH. We could add additional instructions to add `$SCT_DIR`, too?)

You're right that the commands only work if they are run relative to the SCT dir. But, in the case of `batch_processing.sh`, I was only thinking of the context where the user runs the script in the SCT directory. I hadn't considered that a user may copy and paste the commands to run on their own data. Thank you for pointing this out.

**Comment by jcohenadad** [comment]
> We could add additional instructions to add $SCT_DIR, too?

Yes, I would much prefer using this approach.
