### ISSUE TITLE
Incorrect soft QC report 

### ISSUE THREAD

**Issue by naga-karthik** [spinalcordtoolbox/spinalcordtoolbox#4178]
### Description

I am the latest version of SCT (`git-master-fd7601612d924ef0cc9ffcbd2644f5d100fc8d3a`) and I notice that the soft QC results in an incorrect QC report.

### Steps to Reproduce

0. Install SCT version mentioned above. 

1. Download the soft segmentations - [Link](https://drive.google.com/drive/u/0/folders/1_rRsoPqcFXUF4KZ7VwdOBVE-NWryEWLY). The background image of this segmentation is coming from a private dataset which is on git-annex under the name `sci-colorado`

2. Download the subject `sub-5425` and Run `sct_qc -i sub-5425_T2w.nii.gz -s sub-5425_T2w_pred.nii.gz -p sct_deepseg_sc -qc qc`

**Expected behavior:** <What you expect to happen>

The soft segmentations should only be shown around the boundaries but they are shown for the whole slice (see screenshot below)

**Actual behavior:** <What actually happens>

<img width="435" alt="Screen Shot 2023-08-02 at 6 11 44 PM" src="https://github.com/spinalcordtoolbox/spinalcordtoolbox/assets/53445351/377a07b5-9d02-41c9-99d2-46700f1979c7">

Related to #3418 and #4133

**Comment by jcohenadad** [comment]
> The soft segmentations should only be shown around the boundaries but they are shown for the whole slice 

I'm not sure I understand what you mean by "only be shown around the boundaries". The boundaries of what? If the spinal cord, then yes, there is softness around the boundaries of the segmentation, which is what we observe on this QC report, so I'm not sure what's wrong with that QC report?

Also: be aware that the QC report resample images to 0.6mm (and I'm not sure if we use NN or linear for segmentations)

**Comment by joshuacwnewton** [comment]
I think the issue might be that the softseg is showing an opaque background (dark red) when it should be transparent and showing the anat image in the background instead.

This was a problem we encountered before, but it was supposed to have been fixed earlier. I can investigate further. :)

**Comment by naga-karthik** [comment]
Hello! Sorry for being unclear and causing some confusion. 

Yes, you're right @joshuacwnewton - my issue was that the softseg was using the whole thumbnail instead of being overlayed only on the part of the SC in the anat image in the background.

**Comment by jcohenadad** [comment]
ahhh! ok gotcha! thank you for the clarification @joshuacwnewton .

**Comment by joshuacwnewton** [comment]
Opaque/transparent backgrounds are dependent on thresholding after resampling, which occurs here:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/f5de501d3fe98c53861b54c60b9f5f5b96732772/spinalcordtoolbox/reports/slice.py#L305-L314

The last time we encountered this issue, thresholding wasn't being triggered because the image wasn't being considered a segmentation (https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/4125#issuecomment-1579208323). So, we added a new heuristic-based approach to detect segmentations (and soft segmentations), which will then cause thresholding to be applied when appropriate:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/f5de501d3fe98c53861b54c60b9f5f5b96732772/spinalcordtoolbox/reports/slice.py#L60-L72

In this case, the heuristic-based approach failed, because the bright parts of the softseg are very close to `1`, but not exactly `1`:

![image](https://github.com/spinalcordtoolbox/spinalcordtoolbox/assets/16181459/845c7ede-44cf-4c10-9545-8de2d68440f3)

![image](https://github.com/spinalcordtoolbox/spinalcordtoolbox/assets/16181459/1abab001-4be7-4358-8689-7e2118d50729)

We can fix this pretty easily by rounding to, say, 2 decimal places when performing our heuristic, causing `0` and `1` to be the 2 most common values by far:

![image](https://github.com/spinalcordtoolbox/spinalcordtoolbox/assets/16181459/ddc9fe9d-a4b6-4f85-8bb0-d2f5d590884c)
