### ISSUE TITLE
SCT Course: Weird bullet formatting when creating a new slide from the existing template

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#4270]
when creating a new slide using the template, the numbering font size is screwed up:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/assets/2482071/33ee4dd1-48ab-421d-807f-5f1157193fcd

and when matching the font size, the numbers are no more aligned with the textbox.

a good rule of thumb when working with pptx/keynote/gslide is to always make sure the template is working well and is not corrupted so we can easily update formatting things throughout the presentation (esp. if the presentation has many slides)

**Comment by joshuacwnewton** [comment]
Good catch! I'll try to fix this in the template. :)

**Comment by joshuacwnewton** [comment]
Fixed! You should be able to try again now and see the changes.

**Comment by jcohenadad** [comment]
Thanks! Weirdly, the alignment is still imperfect: 

![image](https://github.com/spinalcordtoolbox/spinalcordtoolbox/assets/2482071/f2ad12b3-fa22-4de0-b550-28a2c98185c6)

**Comment by joshuacwnewton** [comment]
Good catch!

I've been poking around various formatting menus, comparing the current slides to a brand new fresh slide deck. But, I can't find any settings that explain why the bullet points are shifted to the left.

Since this is a relatively minor issue, I might put this aside for now to focus on more urgent tasks. But, it is definitely curious. :thinking:

**Comment by joshuacwnewton** [comment]
> Thanks! Weirdly, the alignment is still imperfect

Okay, I've gotten to the bottom of why this is happening:

- The settings for the alignment/indentation can be found by right-clicking on the bullet point/numbered list, then clicking "Text Fitting"
- When I open up a completely new presentation, the alignment looks good:
  ![image](https://github.com/user-attachments/assets/43230ba0-879c-4547-b4cc-5490bb7b10ad)
  And the text-fitting values look like this:
  ![image](https://github.com/user-attachments/assets/5928efbd-6ba1-4574-8363-2e21d79d9628)
- However, even when I make sure to set the text-fitting settings to exactly the same settings as our template, the alignment still looks weird:
  ![image](https://github.com/user-attachments/assets/6e277699-2ada-44e0-805e-237bbe44d6e1)
- The only difference between the default template and our template is the text size (18pt vs. 36pt). So, out of curiosity, I tried increasing the text size to 36pt on the default template, and... aha!
  ![image](https://github.com/user-attachments/assets/90a833e5-3342-46f1-89d4-2b4d8e6057df)

So, it looks like the issue occurs because we're using a larger text size. And, we're using a larger text size because the canvas is larger too, and this was the output of the Keynote -> Slides conversion

**Comment by joshuacwnewton** [comment]
I hoped to be able to fix this on the template by changing the indentation settings, however for some silly reason, the settings are [entirely greyed out](https://echosvoice.com/creating-google-templates/).

![image](https://github.com/user-attachments/assets/f3066289-5fd4-4a20-995b-b404cc2c2641)

So it seems like the only way to fix this is to:

- Decrease the canvas size + text size + resize all of our images (not very feasible)
- Add left-padding to each slide (better, but still not perfect)
  ![image](https://github.com/user-attachments/assets/38523f29-9d8a-45c2-b611-c8c4d101870e)
- Manually indent lists on each new slide (doable, but disappointing)
  ![image](https://github.com/user-attachments/assets/532c38b8-8d57-4669-90c5-367de3f5ecdf)

It's a shame there isn't a cleaner solution, but alas. Closing this issue as completed, as I think this is the best we can hope for.
