### ISSUE TITLE
Warping of `PAM50_spinal_midpoint` is wrong

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#4280]
### Description

going through the SCT course-- i ran the warping of the template and got this:

~~~
julien-macbook:~/sct_course_data/single_subject/data/fmri $ sct_label_utils -i label/template/PAM50_spinal_midpoint.nii.gz -display

--
Spinal Cord Toolbox (git-master-2f402110657afb6c4266e65b852b1958a054c1b6)

sct_label_utils -i label/template/PAM50_spinal_midpoint.nii.gz -display
--

Position=(67,10,6) -- Value= 0.0019879301918479053
All labels (useful syntax):
67,10,6,0.0019879301918479053
~~~

which is unexpected-- i expected values 2, 3, 4, etc.

i think this is related to a wrong interpolation used when warping the template-- 

instructions: https://docs.google.com/presentation/d/1t40Fd0fS0SwWR5FU_GWKEvHkB9d96LVddLQW6L3QAx0/edit#slide=id.p115

This is HIGH PRIORITY-- sorry i have no time to look into this

**Comment by jcohenadad** [comment]
Indeed, when warping the template, i notice the interpolation is linear:
~~~
/Users/julien/code/spinalcordtoolbox/bin/isct_antsApplyTransforms -d 3 -i /Users/julien/code/spinalcordtoolbox/data/PAM50/template/PAM50_spinal_midpoint.nii.gz -o label/template/PAM50_spinal_midpoint.nii.gz -t warp_template2fmri.nii.gz -r fmri_moco_mean.nii.gz -n Linear # in /Users/julien/sct_course_data/single_subject/data/fmri
~~~

but, strangely, the other pointwise labels are _also_ linearly interpolated:
~~~
/Users/julien/code/spinalcordtoolbox/bin/isct_antsApplyTransforms -d 3 -i /Users/julien/code/spinalcordtoolbox/data/PAM50/template/PAM50_label_body.nii.gz -o label/template/PAM50_label_body.nii.gz -t warp_template2fmri.nii.gz -r fmri_moco_mean.nii.gz -n Linear # in /Users/julien/sct_course_data/single_subject/data/fmri
/Users/julien/code/spinalcordtoolbox/bin/isct_antsApplyTransforms -d 3 -i /Users/julien/code/spinalcordtoolbox/data/PAM50/template/PAM50_label_disc.nii.gz -o label/template/PAM50_label_disc.nii.gz -t warp_template2fmri.nii.gz -r fmri_moco_mean.nii.gz -n Linear # in /Users/julien/sct_course_data/single_subject/data/fmri
~~~

**Comment by jcohenadad** [comment]
ah! sh... the other labels are also wrong!

~~~
julien-macbook:~/sct_course_data/single_subject/data/fmri $ sct_label_utils -i label/template/PAM50_label_disc.nii.gz -display

--
Spinal Cord Toolbox (git-master-2f402110657afb6c4266e65b852b1958a054c1b6)

sct_label_utils -i label/template/PAM50_label_disc.nii.gz -display
--

Position=(67,10,6) -- Value= 0.001656608493206588
Position=(64,9,18) -- Value= 0.008945407693736357
All labels (useful syntax):
67,10,6,0.001656608493206588:64,9,18,0.008945407693736357
~~~

something was introduced that must have changed that behaviour-- we need to fix it asap

**Comment by jcohenadad** [comment]
and we also need to add a test for it (lower priority)

**Comment by joshuacwnewton** [comment]
The interpolation type is determined by this function: 

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/2f402110657afb6c4266e65b852b1958a054c1b6/spinalcordtoolbox/scripts/sct_warp_template.py#L131-L138

`list_labels_nn` is determined here:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/2f402110657afb6c4266e65b852b1958a054c1b6/spinalcordtoolbox/scripts/sct_warp_template.py#L34-L35

Given that the point label files do not match any of these patterns, `linear` interpolation is used by default.

----

> something was introduced that must have changed that behaviour-- we need to fix it asap

Looking at the history of `sct_warp_template`, the list of `nn` files has seemingly been the same since 2016: https://github.com/spinalcordtoolbox/spinalcordtoolbox/commit/c99041e992ee5878120c12c25c9665bb12bc906a. So, I'm not sure if there actually has been a behavior change?

Still, assuming `nn` is the desired interpolation, this should be a very easy fix.

**Comment by joshuacwnewton** [comment]
The current test suite is not suited for testing this condition:

- The only tests we perform for sct_warp_template use a pre-commited warping field from the `mt/` folder:
  https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/2f402110657afb6c4266e65b852b1958a054c1b6/testing/cli/test_cli_sct_warp_template.py#L14
- The destination file is a 5-slice MTI image, and the template is the resampled `PAM50_small`. When the template is warped to the MTI image, all labels are lost, presumably due to the lack of resolution of the destination image.
- This means that, with the current images, we can't test the label-warping behavior at all.

So, I will need to write a new test that uses e.g. the `t2.nii.gz` file, then invoke `sct_register_to_template` beforehand. Should still be very quick to test.

**Comment by joshuacwnewton** [comment]
One other way that a behavior change could have been introduced is when we switched from a direct `antsApplyTransform` call to an `sct_apply_transo` call: #3272

However, even during that PR, the only changes were turning the interpolation type from an ants-compatible string to an SCT-compatible string:

![image](https://github.com/spinalcordtoolbox/spinalcordtoolbox/assets/16181459/09182526-c2f9-45a8-9aff-cb470953a68c)

The choices were still only `nn` and `linear`, neither of which are appropriate for point labels.

**Comment by jcohenadad** [comment]
> Still, I presume that nn isn't even the desired interpolation, since sct_apply_transfo has a dedicated label interpolation that preserves point labels.

yes, exactly
