### ISSUE TITLE
Manual correction not working properly on SCT course

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#4284]
### Description

While going through the course:

![image](https://github.com/spinalcordtoolbox/spinalcordtoolbox/assets/2482071/795d64d2-33dc-4c5c-90d3-2469d3dcef9c)

![image](https://github.com/spinalcordtoolbox/spinalcordtoolbox/assets/2482071/65b4a320-5cfc-4580-ae55-a68d52a425b5)

I corrected `sub-05_acq-MTon_MTS.nii.gz`: [qc_fail.yml.zip](https://github.com/spinalcordtoolbox/spinalcordtoolbox/files/13233557/qc_fail.yml.zip)

However when re-running the scan that image was not picked up:
![Screenshot 2023-11-01 at 10 30 52 PM](https://github.com/spinalcordtoolbox/spinalcordtoolbox/assets/2482071/71b9a56c-c7f9-4476-9e8b-3cc258ffe9c1)

[process_data_sub-05.log.zip](https://github.com/spinalcordtoolbox/spinalcordtoolbox/files/13233562/process_data_sub-05.log.zip)

**Comment by valosekj** [comment]
I believe the corrected label was not picked up because the [manual_correction.py](https://github.com/spinalcordtoolbox/manual-correction/blob/r20231101/manual_correction.py) does **_not_** add `-manual` anymore. Instead, the corrected label is named `derivatives/labels/sub-05/anat/sub-05_acq-MTon_MTS_seg.nii.gz` (ie without `-manual`). The label provenance is tracked in the JSON sidecar.

The reason why we do not use the `-manual` suffix anymore is described in [this issue](https://github.com/spinalcordtoolbox/manual-correction/issues/70):
> - no -manual suffix is used - to be in line with our [convention](https://intranet.neuro.polymtl.ca/data/dataset-curation.html#derivatives-structure), we do not use the -manual suffix anymore -- the information about the label provenance is stored in the JSON sidecar

To fix this issue, we can:
1. update the SCT course `process_data.sh` to **_not_** add `-manual` when looking for the labels under `derivatives/labels` (lines 52 and 77 in `sct_course_data/multi_subject/process_data.sh`)
2. modify [manual_correction.py](https://github.com/spinalcordtoolbox/manual-correction/blob/r20231101/manual_correction.py) to include `-manual` again

**Comment by jcohenadad** [comment]
I would go with "1", if not too late @joshuacwnewton

**Comment by joshuacwnewton** [comment]
It's not too late! (I named the `sct_tutorial_data` release with the general name "SCT-Course-20231120". This means that as long as we continue to use this name, no updates are needed on SCT's end, which means that any changes to `sct_tutorial_data` will not block SCT v6.1.)

Right now, the script relies on the "-manual" suffix to distinguish between normal segs and corrected segs. Based on the above info, it seems that we would need to change the script to instead look for the presence of a `.json` sidecar file? (Presuming that non-corrected segs will NOT have the sidecar file.)

**Comment by jcohenadad** [comment]
> Based on the above info, it seems that we would need to change the script to instead look for the presence of a .json sidecar file?

No, I _think_ the difference between a manual and an automatic segmentation is the physical location of the file: a manually corrected file would be located under `derivatives/.../`. @valosekj can confirm

**Comment by valosekj** [comment]
> > Based on the above info, it seems that we would need to change the script to instead look for the presence of a .json sidecar file?
> 
> No, I _think_ the difference between a manual and an automatic segmentation is the physical location of the file: a manually corrected file would be located under `derivatives/.../`. @valosekj can confirm

Exactly! The automatically generated files (e.g., by `sct_deepseg`) are located in the `output/data_processed` folder, while the manually corrected files are stored under `derivatives/labels/`.

So, I believe that the only modification of the `process_data.sh` script is to remove `-manual` from lines 52 and 77.

**Comment by joshuacwnewton** [comment]
Oh, oops! My apologies, I definitely skimmed. Thank you for the correction. I'll update the script accordingly, then. :)

**Comment by joshuacwnewton** [comment]
Script updated! Please try redownloading the course data by running:

```
sct_download_data -d sct_course_data -o {path_to_working_directory}
```

**Comment by valosekj** [comment]
Working after the latest fixes!

<img width="887" alt="image" src="https://github.com/spinalcordtoolbox/spinalcordtoolbox/assets/39456460/e1eaa3c5-77b0-487e-b9c3-f9eb2bf82523">

**Comment by jcohenadad** [comment]
Also working on my end-- thank you for the fix! ❤️
