### ISSUE TITLE
Add color to sct_run_batch output

### ISSUE THREAD

**Issue by NathanMolinier** [spinalcordtoolbox/spinalcordtoolbox#4287]
## Description

I just ran the command `sct_run_batch -script process_data.sh -path-data data/ -path-output output -jobs 3` when testing the course and I noticed that the output given was not as colorful as other sct functions:
<img width="569" alt="Screenshot 2023-11-04 at 5 03 36 PM" src="https://github.com/spinalcordtoolbox/spinalcordtoolbox/assets/68945192/1f0d042b-7e31-4d3e-b0a5-c35e7fe251e9">

I believe we could be more consistent and print the open command in green !

**Comment by joshuacwnewton** [comment]
For other SCT functions, we call the `generate_sc()` function, which in turn calls the `display_open` function, which in turn calls `printv()` with `type='info'` (which triggers the LightGreen color).

Color will only get applied if `isatty()` is true:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/7c1085297d7c53e3316c497b20e536d0ff182432/spinalcordtoolbox/utils/sys.py#L379-L382

So, presumably `isatty()` is returning false for `sct_run_batch`. Strange! (And, we can double-check this by removing the `isatty()` check.)

----

To debug this, I print `file` and `file.isatty()`, then compare:

```python
# Other SCT scripts (e.g. sct_deepseg_sc)
File: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
File is atty: True

# sct_run_batch
File: <spinalcordtoolbox.utils.fs.Tee object at 0x7f35e202bf70>
File is atty: False
```

Aha! There's our smoking gun:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/7c1085297d7c53e3316c497b20e536d0ff182432/spinalcordtoolbox/scripts/sct_run_batch.py#L432-L437

----

There are a number of potential fixes here (restoring the original stdout, making sure `Tee` returns `True` for `isatty()` , etc.) I think I like modifying Tee, because it preserves the Tee functionality throughout all of sct_run_batch, while also having a minimal effect on SCT as a whole (Tee is currently only ever used in the context of sct_run_batch).

**Comment by joshuacwnewton** [comment]
> Since this is a last minute (tiny) fix, and since it's a Sunday before the SCT v6.1 release, I think this is safe to commit directly to master, as to not block the release through reviews/revisions. But, I'd be happy to discuss alternate solutions for 6.2?

My apologies for this. This was not an appropriate reason to push a last minute fix without review. Thankfully, @mguaypaq was online to catch this, and is taking a second look at the changes I've made. :heart:

**Comment by mguaypaq** [comment]
I'm going to close this again, because I thought this change _introduced_ color codes into the text log files, but it looks like they've always been there, so there's no real problem here. Let's go ahead with the release! :rocket:
