### ISSUE TITLE
Update forum post once rootlet segmentation model is out

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#4301]
forum post: https://forum.spinalcordmri.org/t/automatic-segmentation-of-the-proximal-spinal-nerve-roots/1012/2

project: https://github.com/ivadomed/model-spinal-rootlets#model-overview

**Comment by joshuacwnewton** [comment]
Closing this issue as duplicate, because updating forum posts is already [a task in the release procedures](https://github.com/spinalcordtoolbox/spinalcordtoolbox/wiki/Packaging%3A-How-to-create-a-new-SCT-release#step-4-inform-users-that-their-requests-have-been-addressed).

In other words, I will mark the original nnUNet issue as "`user requested`", which will make sure it shows up in the `user requested` issue filter. Then, I will follow up when I release 6.2 on Thursday. :)
