### ISSUE TITLE
Angle correction is performed incorrectly when segmentation does not begin at `z=0`, causing `nan` lengths

### ISSUE THREAD

**Issue by valosekj** [spinalcordtoolbox/spinalcordtoolbox#4315]
### Description

When running `sct_analyze_lesion` on a subject (`sub-zh98_ses-01`) from the `sci-zurich` dataset:

```console
sct_analyze_lesion -m sub-zh98_ses-01_acq-sag_T2w_lesion-manual_bin.nii.gz -s sub-zh98_ses-01_acq-sag_T2w_seg-manual.nii.gz
```

The lesion length is `nan`:

```
(S-I) length : nan mm
```

### Steps to Reproduce

```console
cd ~/data/data.neuro.polymtl.ca/sci-zurich/derivatives/labels/sub-zh98/ses-01/anat
# download images
git annex get .
# binarize the lesion mask (sct_analyze_lesion needs a binary mask)
sct_maths -i sub-zh98_ses-01_acq-sag_T2w_lesion-manual.nii.gz -bin 0 -o sub-zh98_ses-01_acq-sag_T2w_lesion-manual_bin.nii.gz
sct_analyze_lesion -m sub-zh98_ses-01_acq-sag_T2w_lesion-manual_bin.nii.gz -s sub-zh98_ses-01_acq-sag_T2w_seg-manual.nii.gz
```

<details><summary>Output (notice `nan` for `(S-I) length`):</summary>

```console
--
Spinal Cord Toolbox (git-master-365651dbd7d31b909b7ec85844b0e6492a4649ca)

sct_analyze_lesion -m sub-zh98_ses-01_acq-sag_T2w_lesion-manual_bin.nii.gz -s sub-zh98_ses-01_acq-sag_T2w_seg-manual.nii.gz
--

Creating temporary folder (/var/folders/w6/bnzr2qls11l69w0_8q95ghtr0000gn/T/sct_2023-12-06_08-37-55_analyze-lesion_nmrcsfmu)
cp sub-zh98_ses-01_acq-sag_T2w_lesion-manual_bin.nii.gz /var/folders/w6/bnzr2qls11l69w0_8q95ghtr0000gn/T/sct_2023-12-06_08-37-55_analyze-lesion_nmrcsfmu
cp sub-zh98_ses-01_acq-sag_T2w_seg-manual.nii.gz /var/folders/w6/bnzr2qls11l69w0_8q95ghtr0000gn/T/sct_2023-12-06_08-37-55_analyze-lesion_nmrcsfmu

Orient input image(s) to RPI orientation...
File sub-zh98_ses-01_acq-sag_T2w_lesion-manual_bin.nii.gz already exists. Will overwrite it.
File sub-zh98_ses-01_acq-sag_T2w_seg-manual.nii.gz already exists. Will overwrite it.

Label connected regions of the masked image...
Image header specifies datatype 'uint8', but array is of type 'int64'. Header metadata will be overwritten to use 'int64'.
Lesion count = 1

Measures on lesion #1...
  (S-I) length : nan mm
  Max. equivalent diameter : 0.0 mm
  Maximum axial damage ratio : 1.0
  Volume : 1089.84 mm^3

Orient output image to initial orientation...
File sub-zh98_ses-01_acq-sag_T2w_lesion-manual_bin_label.nii.gz already exists. Will overwrite it.


Averaged measures...
  volume [mm3] = 1089.84 +/- 0.0
  length [mm] = nan +/- nan
  max_equivalent_diameter [mm] = 0.0 +/- 0.0
  max_axial_damage_ratio [] = 1.0 +/- 0.0

Total volume = 1089.84 mm^3
Lesion count = 1
```

</details>

### My Observation

It seems that the problem is related to lumbar lesions. Besides `sub-zh98_ses-01`, I encountered the same issue also for `sub-zh78_ses-01` and `sub-zh04_ses-01` (all lumbar).

Note that both lesion and SC masks were manually QCed anc corrected, i.e. the issue should not originate from the segmentation quality.

---

Since @naga-karthik and I are currently working on a lesion analysis for the SCIseg project, the issue has a relatively high priority. (unfortunately I do not have time to debug it more right now)

**Comment by joshuacwnewton** [comment]
> Since @naga-karthik and I are currently working on a lesion analysis for the SCIseg project, the issue has a relatively high priority. (unfortunately I do not have time to debug it more right now)

Thank you for reporting this! I would be happy to investigate. :)

**Comment by joshuacwnewton** [comment]
Lengths are computed here:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/365651dbd7d31b909b7ec85844b0e6492a4649ca/spinalcordtoolbox/scripts/sct_analyze_lesion.py#L312

Working backwards:

- We sum over 36 different `zz` slices, from `293` to `328`, corresponding to the lesion (`im_data`).
- The sum is `nan` is because `self.angles[zz]` are `nan` for all 36 `zz` slices.
- `self.angles` is created in the [`self.angle_correction`](https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/365651dbd7d31b909b7ec85844b0e6492a4649ca/spinalcordtoolbox/scripts/sct_analyze_lesion.py#L493-L510) method.
- In this method, we first [initialize the array with nans](https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/365651dbd7d31b909b7ec85844b0e6492a4649ca/spinalcordtoolbox/scripts/sct_analyze_lesion.py#L501), then compute the angle [for each slice in the centerline derivative](https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/365651dbd7d31b909b7ec85844b0e6492a4649ca/spinalcordtoolbox/scripts/sct_analyze_lesion.py#L504C1-L504C1).
- For this subject, the centerline slices (`iz`) run from `0` to `118`, because we use a `range` object that begins with `0`.
- Because of this, the initialized `nan` values for slices `293` to `328` are never overwritten.

However, this is weird -- we _know_ the centerline (i.e. the segmentation) overlaps with the lesion:

![image](https://github.com/spinalcordtoolbox/spinalcordtoolbox/assets/16181459/553c4750-d32b-45c2-9aec-ec54fdd5ac09)

So, the issue here is that, during angle correction, we're assigning values to the wrong slices, due to using a 0-based `range` object. Meaning, any subjects with a segmentation that doesn't start at slice `z=0` will be incorrect.

----

This should be a relatively easy fix? 

However, this bug makes me _very_ concerned about past results from `sct_analyze_lesion`; for any subjects where the segmentation does not start at slice `0`, the angle correction has likely been wrong. 

This bug was introduced 5 years ago in https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/2147. Before this refactor, the iteration was [performed across the entire segmentation image](https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/2147/files#diff-1843e73aa50472f955aad5fce4c0580c4e0b826b147b723b25c3c1ce50b2e3d2).

**Comment by joshuacwnewton** [comment]
Side note: I think maybe the pitfall here was the `get_centerline` function, called here:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/365651dbd7d31b909b7ec85844b0e6492a4649ca/spinalcordtoolbox/scripts/sct_analyze_lesion.py#L497-L499

`get_centerline` has the following inputs and outputs:

- It takes in an `im_seg` object with `data` of size `[18, 384, 384]`
- It returns an `arr_ctl_der` object of size `[3, 118]`, because the centerline function [crops the image](https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/365651dbd7d31b909b7ec85844b0e6492a4649ca/spinalcordtoolbox/centerline/core.py#L137-L141) to the extents of the centerline (in this case, `minmax=True`).

This was bound to cause confusion, because the dimensions are different -- we lose the relative positioning of the centerline _within_ `im_seg`, and the slice numbers can no longer be trusted.

If, on the other hand, `get_centerline` returned an `arr_ctr_der` object of size `[3, 384]`, with `nan` values where the centerline did not exist, then there would have been much less ambiguity when the surrounding code was refactored.

**Comment by joshuacwnewton** [comment]
It turns out that, during the original refactor in https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/2147, `minmax=False` by default, meaning that `get_centerline` would have returned the full 384 slices. Then, at some point, `minmax=True` became the default instead.

So, it's a bit less clear when this bug was actually introduced...
