### ISSUE TITLE
Discussing strategies to backup IDE-related config files

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#4320]
For developers using IDE, config files are useful to keep and backup. Eg: `.vscode/launch.json` for VScode (to test CLI), `.idea/` for Pycharm. I see such files in other repos sometimes. Is that a bad thing? I assume it is, because it is quite customized to every dev's need. If so, what alternative is recommended? It is more convenient (at least for me) to have these files physically located under the project's directory (which is version-tracked with git). I'm curious to hear what other devs do.

**Comment by joshuacwnewton** [comment]
> I see such files in other repos sometimes. Is that a bad thing? I assume it is, because it is quite customized to every dev's need.

Indeed! I often see IDE-specific files in sample `.gitignore` files. For example, GitHub's [`Python.gitignore`](https://github.com/github/gitignore/blob/main/Python.gitignore) template mentions [`.idea`](https://github.com/github/gitignore/blob/4488915eec0b3a45b5c63ead28f286819c0917de/Python.gitignore#L155-L160) (though it includes a caveat).

Most of the time, these files feel like unnecessary clutter to me. I can only imagine wanting to sync these files if A) the repo is only used by one person, or B) if the team decides to unify project settings for every member of the team ([example here](https://stackoverflow.com/a/44690814)).

> It is more convenient (at least for me) to have these files physically located under the project's directory (which is version-tracked with git). I'm curious to hear what other devs do.

I personally add the entirety of `.idea/` to my `.gitignore`. I am okay with starting fresh every time I `git clone` a project on a new workstation.

But, perhaps there are still ways to keep individual IDE settings backed up. Here is some brainstorming:

- **Global IDE Settings**: Many IDEs have their own methods for exporting/importing/syncing global IDE settings. PyCharm has [several options](https://www.jetbrains.com/help/pycharm/sharing-your-ide-settings.html), while VSCode has [Settings Sync](https://code.visualstudio.com/docs/editor/settings-sync).
- **Project-specific IDE Settings**: This is a bit trickier, given that (as you mention) the settings are stored in the same directory as project files.
  - `git`: Since we're trying to avoid using the project's own git repository, we would need to use some other sort of git repository, either separate from the project folder, or nested outside of the project's folder. 
    - Separate: This avoids the complications of nested git folders, but would require manualy copying and pasting periodically from the project folder to this separate settings repo. 
      Maybe using something like SyncThing to automatically sync the project-specific folders to this separate repository would make this easier? There is a [macOS bundle](https://github.com/syncthing/syncthing-macos) to make using SyncThing easier, too. 
      Alternatively, maybe a simple script could be written to automate the backup process, too ([example](https://gist.github.com/jimzhan/529aa82465549043d883f739e9e93701)).
    - Nested: I'm imagining setting up a git repository for the entire `code`/`repos` folder, such that all projects are tracked using this "parent" git repository. Then, the person would set up a [global `.gitignore`](https://docs.github.com/en/get-started/getting-started-with-git/ignoring-files#configuring-ignored-files-for-all-repositories-on-your-computer) to ignore all project files. Lastly, the person would create another `.gitignore` specifically for the `code`/`repos` git repository, ignoring _all_ files but adding [exclusions](https://stackoverflow.com/questions/3001888/how-do-gitignore-exclusion-rules-actually-work) specifically for project-specific configs. 
      Though, setting up on a new workstation would require A) cloning the settings repo first, then B) [cloning into non-empty repos](https://stackoverflow.com/questions/2411031/how-do-i-clone-into-a-non-empty-directory) (since the settings would already be present), which is a little awkward.
  - Some other non-git backup service? e.g. SyncThing again + a cloud backup service, but this time used on the entire `code`/`repos` folder, with patterns to only ever sync project settings. Or, using a cloud backup service like Google Drive? Though, it seems like using pattern-based rules [is tricky for Google Drive](https://support.google.com/drive/thread/2319794/how-to-prevent-a-folder-subfolder-to-be-synced-avoid-a-subfolder-upload?hl=en).
  - Configuring the IDE such that it reads the project-specific `.idea`/`.vscode` folders from outside of a given project's folder? I'm not sure if this is even possible, but perhaps it could be an alternative solution...

Given the complexity of these solutions, my gut is that it would take more effort to back up the settings than it would to start fresh each time. Plus, I feel like it would be pretty easy to set one of these solutions up, then forget how it works after a few month's time when you actually need to setup a new workstation. :laughing: 

> Side note: I came across [this resource on `.idea` folders](https://bootcamptoprod.com/intellij-idea-folder/) in my travels. Maybe I should take a few minutes to better understand my IDE's settings. There could be some usefulness to syncing settings that I hadn't considered before that would convince me to back up my project settings? :thinking:

**Comment by jcohenadad** [comment]
Thank you so much for the thorough analysis @joshuacwnewton ! This is very helpful, and it somewhat comforts me about going with the 'starting fresh' alternative 😅

**Comment by jcohenadad** [comment]
We can probably close this issue
