### ISSUE TITLE
Adding QC feature for full inferior-superior view of spinal cord

### ISSUE THREAD

**Issue by plbenveniste** [spinalcordtoolbox/spinalcordtoolbox#4362]
I would like to suggest an improvement of sct_qc. 

I have been QC-ing spinal cord segmentation. When I do it, I feel that it is easier to view on the sagittal plane. This feature is not available with `sct_deepseg_sc`but it is with `sct_deepseg_lesion`.  (Maybe adding it to the first one could be useful)
The problem with this, is that the image is cropped around the segmentation when displayed on the html QC giving the following result : 
<img width="1512" alt="image" src="https://github.com/spinalcordtoolbox/spinalcordtoolbox/assets/67429280/486a58b9-9c56-40ff-9cb5-689f330e0056">

However, this is not ideal as I cannot see that a chunk is missing (which I can see easily when I open fsleyes) : 

<img width="594" alt="image" src="https://github.com/spinalcordtoolbox/spinalcordtoolbox/assets/67429280/b001a8ef-4c07-4e24-a8b9-8d5b691615af">

Also, in the case of lesion segmentation, if a lesion is missed in a part of the image which is cut out then, it's harder to verify manually. 

Do you think it would be useful to add a flag --full-image (or --full-inf-sup-axis) to display the entirety of the spinal cord without missing some chunks ? 

Happy to help if needed, 

Thanks

**Comment by mguaypaq** [comment]
This comment is just to add a cross-reference to #4204, to keep in mind this feature request while doing the refactor.

**Comment by joshuacwnewton** [comment]
Currently, the sagittal mosaic gets the bounding box for the crop from the spinal cord mask, determined in [this section of code](https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/764aa9a3313b5d949b5117ed05b3b84a06737066/spinalcordtoolbox/reports/slice.py#L458-L468).

So, one thing you can do right now to get around this limitation is:

- Create a padded mask around the spinal cord using `sct_create_mask`
- Pass the padded mask to the `-s` argument of `sct_qc`, and pass the _unpadded_ SC segmentation to the `-d` argument (or is it the other way around? :thinking:). But, that way, you get a larger crop, but still display the original SC within.

But, to comment on making this change in SCT's code: I think for its original purpose (displaying lesion segmentations), cropping around the spinal cord was... maybe sufficient? (Since the lesions would largely exist within the SC seg bounding box.) But, for QC'ing the spinal cord segmentation itself, I agree that the sagittal view does not show enough of the surrounding content.

**Comment by plbenveniste** [comment]
Thanks for the feedback @joshuacwnewton ! :)

**Comment by jcohenadad** [comment]
> I added the full SI axis

I'm afraid in other situation this will be sub-optimal. Eg: for brain/cspine scans, where half of the image will be occupied by the brain. How about we add padding on the SI instead of showing the full SI?

and the 20% width: what is this percentage from (ie: is it 20% of the min-max segmentation voxel in a given dimension?)

**Comment by joshuacwnewton** [comment]
> and the 20% width: what is this percentage from (ie: is it 20% of the min-max segmentation voxel in a given dimension?)

20% of the width of the bounding box. :slightly_smiling_face:

**Comment by jcohenadad** [comment]
> 20% of the width of the bounding box surrounding the entire segmentation

Sounds reasonable, but I would not make it relative to the box. Instead, I would suggest a fixed padding, eg: 10 mm? what do you think?

**Comment by joshuacwnewton** [comment]
> > 20% of the width of the bounding box surrounding the entire segmentation
> 
> Sounds reasonable, but I would not make it relative to the box. Instead, I would suggest a fixed padding, eg: 10 mm? what do you think?

I think I had been concerned about size differences between images, but I had forgotten that we resample slicewise to 0.6mm, so yes I agree, using a hardcoded pixel value should be OK. :)
