### ISSUE TITLE
Newly-updated `checkout@v4` action requires additional dependencies for (Debian 9/CentOS 7/WSL) runners

### ISSUE THREAD

**Issue by joshuacwnewton** [spinalcordtoolbox/spinalcordtoolbox#4382]
PR #4353 passed for our PR runners, but failed for some of the runners that only run on schedule/pushes to `master`: https://github.com/spinalcordtoolbox/spinalcordtoolbox/actions/runs/8024513196/job/21924760735

**Comment by mguaypaq** [comment]
Given that Debian 9 (stretch) is [no longer under LTS](https://www.debian.org/releases/stretch/) as of July 2022, and only gets [paid support](https://wiki.debian.org/LTS/Extended) now, maybe it's time to let it go. The oldest release that's even listed on packages.debian.org is Debian 10 (buster), aka [oldoldstable](https://packages.debian.org/oldoldstable/).

As for CentOS 7, it seems to only have a few more months of maintenance updates (until end of June 2024, [according to Wikipedia](https://en.wikipedia.org/wiki/CentOS#End-of-support_schedule)). And it looks like it only ships with glibc-2.17, according to [this package list](http://mirror.centos.org/centos/7/os/x86_64/Packages/), whereas node20 seems to require glibc-2.28 or above. Maybe it's also time to let it go.

For WSL, the problem seems different, but I'm not sure what it is, because I don't see any error messages.

**Comment by mguaypaq** [comment]
Slightly more info for WSL: I think it's unrelated to the node20 dependencies, because the error happens after the SCT installer has started running.

The last few lines of output from [this test run](https://github.com/spinalcordtoolbox/spinalcordtoolbox/actions/runs/8101090495/job/22142993227#step:7:182) are from conda:
```
Extracting : zstandard-0.19.0-py312h5eee18b_0.conda:  95%|█████████▍| 69/73 [00:27<00:01,  2.32it/s]
Extracting : zstd-1.5.5-hc292b87_0.conda:  96%|█████████▌| 70/73 [00:27<00:01,  2.32it/s]           
Extracting : _libgcc_mutex-0.1-main.conda:  97%|█████████▋| 71/73 [00:27<00:00,  2.32it/s]
Extracting : _openmp_mutex-5.1-1_gnu.conda:  99%|█████████▊| 72/73 [00:27<00:00,  2.32it/s]
                                                                                           
Installing base environment...
Downloading and Extracting Packages: ...working... done
Downloading and Extracting Packages: ...working... done
Preparing transaction: ...working... done
```
I think I saw these lines of output after only ~2 minutes of the test run. But then there was no further output for ~20 minutes, and possibly the test run was killed for getting stuck, because [the summary page](https://github.com/spinalcordtoolbox/spinalcordtoolbox/actions/runs/8101090495) has the following annotation for the test run:
```
The hosted runner encountered an error while running your job. (Error Type: Disconnect).
```

**Comment by joshuacwnewton** [comment]
Back from being sick! I'm happy to take over the investigation. Thank you for kickstarting things, @mguaypaq. :heart:

**Comment by joshuacwnewton** [comment]
> Slightly more info for WSL: I think it's unrelated to the node20 dependencies, because the error happens after the SCT installer has started running.

The [catalyst PR](https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/4353) changed both the underlying Windows OS (`windows-2019` -> `windows-2022`) and the Setup-WSL action (`v2` -> `v3`). So, I can definitely test both changes in isolation, then go from there. :)
