### ISSUE TITLE
Image contrast not appropriately set for some contrast

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#4389]
### Description

Here is how a QC report with PSIR looks like:

![ezgif-4-3ce917b49a](https://github.com/spinalcordtoolbox/spinalcordtoolbox/assets/2482071/1064f840-bb51-48ea-a627-10519d97aa9e)

Context/data: https://github.com/neuropoly/data-management/issues/303

**Comment by joshuacwnewton** [comment]
This is due to a mistaken assumption I made in #4345 when determining image types:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/2f5105bca62df5e65d1c997692f5053c1bed8f99/spinalcordtoolbox/image.py#L1863-L1869

I assumed that if an image was entirely whole values (e.g. 1.0, 2.0, 3.0) and is not binary, then it must be a label image, and thus should be treated like a segmentation when resampling (i.e. linear resampling + thresholding).

But, PSIR data is not binary and is represented using whole values, yet it is an anat image. :sweat: 

If I correct the method to identity PSIR data as anat, then the QC is displayed correctly:

![image](https://github.com/spinalcordtoolbox/spinalcordtoolbox/assets/16181459/e6448969-8e72-4d8f-b179-1d3b057cb744)

I will try to think of a way to accurately identify labeled segs and PSIR data such that they are both correctly resampled for display in QC reports.
