### ISSUE TITLE
What colormap should be used for soft segmentation QCs? (single color vs. gradient)

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#4457]
While playing with the new QC sct_deepseg feature (yay!), I noticed the segmentations are soft:

![image](https://github.com/spinalcordtoolbox/spinalcordtoolbox/assets/2482071/c58cc130-8519-4597-ab33-01c0e99b2597)

Is this desirable?

**Comment by joshuacwnewton** [comment]
So sorry! I think I misunderstood your [earlier review comment](https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/4446#issuecomment-2066864527) on the PR. I thought you suggested binary segs to address the [colormap issues](https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/4446#issuecomment-2066897412) in the first draft of the PR. I didn't realize that you wanted to universally show binary segs. 

-----

> Is this desirable?

I think my goal with this was to allow the user to vary the `-thr` parameter, and thus more easily see which voxels would be affected by `-thr`. But, if users will largely ignore `-thr` and simply binarize the soft output, then maybe a soft QC is unnecessary.

It is also worth nothing that this "soft" behavior was present in the old QC reports, too. It will also be used if softsegs are passed to any of the existing QC segmentation options for `sct_qc -p` that use "listed_seg" under the hood. For example: 

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/8f2b0e0eb956cbd12d1cabdfbee34e1ca8d99c34/spinalcordtoolbox/reports/qc.py#L686-L689

This is because `listed_seg` uses the exact same two-tone colormap.

**Comment by jcohenadad** [comment]
Yes, in the past we introduced softseg because we needed to review it (i can't remember exactly the context)-- here, the black borders are problemmatic (maybe it's just a question of colormap)-- but in any case it is more precise to do qc with binarized outputs in this context-- inputs from @naga-karthik  and others appreciated--

**Comment by joshuacwnewton** [comment]
> black borders are problemmatic (maybe it's just a question of colormap)

Ahhh, I see. Yes, any feedback regarding a more useful colormap would be much appreciated, as it would benefit both the new QC and the existing QCs.

**Comment by jcohenadad** [comment]
just to clarify, seeing soft seg in the QC is sometimes desirable, eg, for this scenario (warping seg using linear interp on B1+ maps):

![image](https://github.com/spinalcordtoolbox/spinalcordtoolbox/assets/2482071/564ff7f7-c95e-48f3-b2e3-0dd60fe83cad)

**Comment by joshuacwnewton** [comment]
Is the main problem with the first example that the black outline is too thick, due to a low resolution? (Whereas, with your second example, the soft outline is very small, so it is not too distracting.)

Or is it more to do with the visual contrast against the background image? (Dark on dark vs. dark on light?)

I guess I'm not too sure I understand the difference between the two cases based on screenshots alone.

**Comment by jcohenadad** [comment]
in the first scenario, i want to assess the quality of the seg on the image where the seg is run, so looking at the border is important--

in teh 2nd scenario, i am warping an existing seg onto another image, with the goal to extract qMRI values while accounting for partial volume information provided by the linearly-interpolated warped segmentation, hence having some idea about the partial volume is important, and so i am not so much assessing the quality of the seg in this case-- i am more assessing how the extracted values will look within the soft mask--

hope that makes sense

**Comment by joshuacwnewton** [comment]
> in the first scenario, i want to assess the quality of the seg on the image where the seg is run, so looking at the border is important--

So, if QC'ing the border is important, then I'm guessing the problem is that the dark red makes it difficult to see the border for slices such as the bottom row in your first example:

![image](https://github.com/spinalcordtoolbox/spinalcordtoolbox/assets/16181459/60d44b26-4350-40ee-a2dd-ef0e2de318b1)

But bright red has good contrast against pretty much all grayscale backgrounds, making it easier to see the quality of the segmentation?

**Comment by naga-karthik** [comment]
bit of a wild suggestion but what do you think about a red-yellow colormap for the qc report? FSLeyes has it and it has also gives a good idea about the boundary (in cases where the segmentation is boundary-sensitive)

<img width="245" alt="Screenshot 2024-04-24 at 5 47 52 PM" src="https://github.com/spinalcordtoolbox/spinalcordtoolbox/assets/53445351/9e340c04-407f-4c16-81ab-22d6f3dce04e">

**Comment by jcohenadad** [comment]
> bit of a wild suggestion but what do you think about a red-yellow colormap for the qc report? FSLeyes has it and it has also gives a good idea about the boundary (in cases where the segmentation is boundary-sensitive)

hum, i'm not sure. Maybe we should try. But i'm not a fan of using another colormap for the same value (1: yellow here vs. 1: red elsewhere). 

 > (we can also invert the colormap shown here and use red for the cord and yellow for the boundary to keep in line with the current colormap )

no, too confusing for ppl (not intuitive)

**Comment by joshuacwnewton** [comment]
> i think red-to-transparent should be the way to go, but i'm not sure if that's easily possible.

I think it should be? At least, with the new qc2.py refactor, there's a lot more flexibility when it comes to image generation.

I can imagine masking the image into two, one for arr==1 and one for arr<1. Then, using the same solid color for both, but tweaking the alpha for the second.

I'll take a look tomorrow. I don't want to over promise given the tight deadline, but I can definitely try to see if I can get it working for sct_deepseg prior to the ISMRM release.

At the very least, reverting to a single-color color map would be extremely easy and wouldn't require any troubleshooting, so we can definitely do that by tomorrow.

**Comment by joshuacwnewton** [comment]
Adding transparency easier than I expected. Since we already have a (binary or soft) image that ranges from [0.0, 1.0], we can use the image values directly for the alpha (1.0 == opaque, 0.0 == transparent):

![image](https://github.com/spinalcordtoolbox/spinalcordtoolbox/assets/16181459/13100566-e338-4424-81a1-376bc9473c6a)

![image](https://github.com/spinalcordtoolbox/spinalcordtoolbox/assets/16181459/48a89916-4848-41be-b2c0-d4453b5e8241)

![ezgif com-animated-gif-maker](https://github.com/spinalcordtoolbox/spinalcordtoolbox/assets/16181459/09849548-b6a9-4a1b-b9fc-8cea7b607716)

**Comment by joshuacwnewton** [comment]
The screenshots from https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/4457#issuecomment-2077628138 were taken from a zoomed-in version of the QC report generated by this test:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/269b004c68ee394823d0b2ba1063354342695e20/testing/cli/test_sct_deepseg.py#L46-L50

Here is the "before" for the same output for comparison:

![image](https://github.com/spinalcordtoolbox/spinalcordtoolbox/assets/16181459/dfcbb4b1-d376-4b5d-921c-6396487c30dd)

**Comment by jcohenadad** [comment]
> I'm wondering if it's just the interpolation or the actual model prediction or the GT mask is like that!

Right, we need to keep in mind that the QC report does interpolate the images (to 0.6mm IIRC)--

**Comment by naga-karthik** [comment]
yeah, I think it's all good, I checked a few other soft QCs on my end at they (i.e. the boundaries) all looked similar.
