### ISSUE TITLE
Sagittal mosaic QC report is tiny for 1.0mm istropic image with 75 slices

### ISSUE THREAD

**Issue by NathanMolinier** [spinalcordtoolbox/spinalcordtoolbox#4458]
## Description

I was experimenting with QC generation on spine segmentation and figured that I could use the flag `-p sct_deepseg_lesion` to quality control my data.

<details>
<summary>Example</summary>
<img src=https://github.com/spinalcordtoolbox/spinalcordtoolbox/assets/68945192/e0c10cc6-582c-4f40-885d-dbf8fa96b00b alt="drawing" width="100"/>

```python
subprocess.check_call([
                            "sct_qc", 
                            "-i", img_path,
                            "-s", spine_path,
                            "-d", spine_path,
                            "-p", "sct_deepseg_lesion",
                            "-plane", "sagittal",
                            "-qc", qc_path
                        ])
```

</details>

But then I wanted to use the same trick on another image with a bigger field of view and got this results:

<img width="1504" alt="Screenshot 2024-04-24 at 16 08 30" src="https://github.com/spinalcordtoolbox/spinalcordtoolbox/assets/68945192/da70cf9c-26f3-4505-bcf8-f7ce0b9288c2">

Would it be possible to optimize the image disposition used in the QC ? Or at least allow the user to specify a different matrix ?

In this case I would like to have more than 3 columns

**Comment by joshuacwnewton** [comment]
> But then I wanted to use the same trick on another image with a bigger field of view and got this results:

I'm wondering if this is a bug of some sort? It reminds me of the issue I encountered with mouse data having a very small resolution.

I'm curious why the images are simultaneously A) tiny but B) do not span the full width of the 600px display window... that smells like a bug to me.

**Comment by joshuacwnewton** [comment]
Hi @NathanMolinier! Could you please share the data used to generate this QC report? :)

**Comment by NathanMolinier** [comment]
I got this same problem with most of the subjects from the dataset `whole-spine`. I will send you an example using our slack !

**Comment by joshuacwnewton** [comment]
The bug occurs because of the following logic:

- In `slice.py :: Sagittal.mosaic()`:
   - We use the segmentation image as the bounding box.
   - The bounding box is very large (864x213), meaning only 3 images fit in the ~600pix width.
   - Because only 3 images fit, the total mosaic extends VERY far down. (array size: 639 * 21600).
- In `qc.py :: _make_QC_image_for_3d_volumes()`:
   - For the matplotlib image plot, the canvas size is `[5, 5]` by default (5 inches x 5 inches)
      - Note: This default made sense before we implemented sagittal mosaics, because normally Sagittal QCs were just a single image. 
   - Because the matrix is so long, it exceeds the canvas size, and thus the whole image gets scaled down to fit.
   - We can easily fix this by doing exactly what we do for axial mosaics: scale the height of the figure based on the ratio between height and width.

![Image](https://github.com/spinalcordtoolbox/spinalcordtoolbox/assets/16181459/9556c94d-3b82-4bc2-8125-215f22ca72a9)

However, while better, the image is still not spanning the full width of the QC report. This time, the limitation is not matplotlib -- if we check the files saved in the QC directory, we can see that the full-size image is created on disk.

Instead, the limitation is the browser. The images are _huge_ in size (1500px * 50704px). But, our `style.css` has the following `max_height` set:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/e7b25df6a5e3ecd379427a19e576ea2386cb43f2/spinalcordtoolbox/reports/assets/_assets/css/style.css#L61-L65

If I remove this limitation, we can see the full QC:

![Image](https://github.com/spinalcordtoolbox/spinalcordtoolbox/assets/16181459/ad545ed2-d768-4a82-a67d-5ee6f81d9275)

The question I have now is: Why are these images so big in the first place? ANS:

- The images are 1mm isotropic.
- When the images are resampled to 0.6mm isotropic, they get scaled up!
- There are also 75 sagittal slices that need to be displayed, so the mosaic is naturally *many* rows long (25).

With some further tweaking (skipping resampling, changing the image width from 600 to 1000), I can get a mosaic that's 7*11:

![Image](https://github.com/spinalcordtoolbox/spinalcordtoolbox/assets/16181459/1c129b0f-015b-47b4-ba35-c4498928d007)

Still huge, but not as huge!

-----

I'm not 100% sure how we would tweak the knobs (pixel dimensions, DPI, canvas size, resampling) so that we support this use case, but not mess up other images. I'll have to think about this and test some other images. 🤔 

But, in the short term, to fix the QCs for you can try checking out this branch with my fixes: [`jn/4458-fix-bad-sagiital-mosaic`](https://github.com/spinalcordtoolbox/spinalcordtoolbox/compare/master...jn/4458-fix-bad-sagiital-mosaic)

**Comment by joshuacwnewton** [comment]
> I'm not 100% sure how we would tweak the knobs (pixel dimensions, DPI, canvas size, resampling) so that we support this use case, but not mess up other images.

One thing we could pretty easily do is expose some of the parameters as CLI args. (I think that's what @NathanMolinier was suggesting with "customize image disposition", too.)
