### ISSUE TITLE
Indicate versions of `sct_deepseg` models

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#4465]
## Related issues

- https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/1572
- https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/2489
- https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/2788
- https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/2959

## Context

As we are more actively training and updating models for `sct_deepseg`, the question of versioning becomes important.

Example: When listing a task, there is a link to the GitHub repository of the model, but no information about the model version:

```console
sct_deepseg -list-tasks

--
Spinal Cord Toolbox (git-master-72ff27030efda92431ee831b45f31e2858b8552d)

sct_deepseg -list-tasks
--

[...]

TASK:             seg_sc_contrast_agnostic
CONTRAST:         any            
MODELS:           model_seg_sc_contrast_agnostic_softseg_monai
LONG_DESCRIPTION: This model for contrast agnostic spinal cord segmentation uses an nnUNet architecture, and was created with
                  the MONAI package. Training data consists of healthy controls from the open-source Spine Generic Multi Subject
                  database and pathologies from private datasets including DCM and MS patients. Segmentation has been tested
                  with the following contrasts: [T1w, T2w, T2star, MTon_MTS, GRE_T1w, DWI, mp2rage_UNIT1], but other contrasts
                  that are close visual matches may also work well with this model.
URL:              https://github.com/sct-pipeline/contrast-agnostic-softseg-spinalcord/
INSTALLED:        Yes
```

Even more confusing: from SCT's git SHA (72ff27030efda92431ee831b45f31e2858b8552d), I see that v2.3 of the model is supposed to be installed:
https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/72ff27030efda92431ee831b45f31e2858b8552d/spinalcordtoolbox/deepseg/models.py#L141-L143

However, because I updated SCT without re-installing the model, the model could in fact be from an older version.

I verified I had the latest version by comparing the training logs:
```console
julien-macbook:~/code/spinalcordtoolbox/data/deepseg_models/model_seg_sc_contrast_agnostic_softseg_monai $ cat logs.txt 
[...]
2024-04-12 04:51:55.513 | INFO     | __main__:on_test_epoch_end:477 - Test (Soft) Dice: 0.8189144134521484
2024-04-12 04:51:55.513 | INFO     | __main__:on_test_epoch_end:478 - Test (Hard) Dice: 0.9547366771735345
2024-04-12 04:51:56.887 | INFO     | __main__:main:787 - TESTING DONE!
```

vs. freshly downloaded `model_soft_bin_20240410-1136`:
```console
julien-macbook:~/code/spinalcordtoolbox/data/deepseg_models/model_seg_sc_contrast_agnostic_softseg_monai $ cat /Users/julien/Desktop/model_soft_bin_20240410-1136/logs.txt 
[...]
2024-04-12 04:51:55.513 | INFO     | __main__:on_test_epoch_end:477 - Test (Soft) Dice: 0.8189144134521484
2024-04-12 04:51:55.513 | INFO     | __main__:on_test_epoch_end:478 - Test (Hard) Dice: 0.9547366771735345
2024-04-12 04:51:56.887 | INFO     | __main__:main:787 - TESTING DONE!
```

But we cannot ask our users to go through this verification step 😅.

## Solution

Display the model version in the list (and with https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3394, also output that info in the JSON)

**Comment by jcohenadad** [comment]
Thank you for drafting this excellent plan @joshuacwnewton ! My only comment would be:

> If the model is out of date (e.g. SCT is updated but sct_deepseg -install-task has not been run yet), then emit a warning.

people tend to ignore warnings, so I would suggest to instead do a brute-force reinstallation of the model if it does not match the model that should be installed with the current version of SCT (if ppl want to run an older model they can install an older version of SCT)

**Comment by mguaypaq** [comment]
Storing _some_ token inside a `source.txt` and checking it against the `MODELS` dict is a nice simple design. As for the warning vs forced installation, I would suggest:
* It would be good if `sct_deepseg -list-tasks` showed both the expected version and the detected version.
* But for every other action (including running the model), we should consider a _mismatched version_ of the model to be the same as a _not installed_ model. (Maybe this check could be incorporated into [`models.is_valid()`](https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/72ff27030efda92431ee831b45f31e2858b8552d/spinalcordtoolbox/deepseg/models.py#L423-L435)?)

If we want to use the URL as the version token, there are some pros and cons:
* (pro) It's human-readable, which is very nice.
* (con) There can be more than one mirror listed in `MODELS`, so we'd need to be careful with the validation logic: _any_ URL listed in the `MODELS` entry should be considered valid in `source.txt`.
* (con) This difference would also show up in logs, sidecars, etc., and might lead people to wonder if they have the same model. And it's only buried in (each version of) `MODELS` that the correspondence between the various URLs for the same version of a model is written down.
* (pro) This is maybe good for provenance/reproducibility, since it's arguably closer to the truth. In case one of the URLs points to the wrong file, it will be easier to track down which real version was used.
* (neutral) In addition to multiple model URLs, we also have a mechanism for having a separate URL for each model seed. It shouldn't be hard to put a `{seed_name: url}` dict in `source.txt`, just something we need to be aware of. As a multi-line thing, this might also affect the formatting of `sct_deepseg -list-tasks`.

**Comment by joshuacwnewton** [comment]
> * (con) There can be more than one mirror listed in `MODELS`, so we'd need to be careful with the validation logic: _any_ URL listed in the `MODELS` entry should be considered valid in `source.txt`.
> * (con) This difference would also show up in logs, sidecars, etc., and might lead people to wonder if they have the same model. And it's only buried in (each version of) `MODELS` that the correspondence between the various URLs for the same version of a model is written down.

Since you already mention needing to display multiple model seeds, we could always store/display all of the mirrors, too? 

Though, things get a little tricky when considering whether to display only the URL that was used to actually download the model, or to display all mirrors['](https://en.wikipedia.org/wiki/All_Mirrors) at once. :thinking: 

Another quick sketch of what `sources.txt` (`sources.json`?) could look like:

```json
// option 1: list just the URL that was actually used 
{
    "model_urls": {
        "mice_uqueensland_sc": "https://github.com/ivadomed/mice_uqueensland_gm/releases/download/r20200622/r20200622_mice_uqueensland_gm.zip",
    }
}

// option 2: list all sources at once
{
    "model_urls": {
        "mice_uqueensland_sc": [
            "https://github.com/ivadomed/mice_uqueensland_gm/releases/download/r20200622/r20200622_mice_uqueensland_gm.zip",
            "https://osf.io/mfxwg/download?version=6",
        ],
    }
}

// multi-model tasks (only 'seg_tumor-edema-cavity_t1-t2' and 'seg_tumor_t2')
{
    "model_urls": {
        "findcord_tumor": ["https://github.com/ivadomed/findcord_tumor/archive/r20201215.zip"],
        "t2_tumor": ["https://github.com/ivadomed/t2_tumor/archive/r20201215.zip"],
    },
}

// multi-seed tasks (only 'model_seg_ms_lesion_mp2rage')
{
    "model_urls": {
        "model_seg_ms_lesion_mp2rage": {
            "seed1": ["https://github.com/ivadomed/model_seg_ms_mp2rage/releases/download/r20230210/model_seg_lesion_mp2rage_r20230210_dil32_seed01.zip"],
            "seed2": ["https://github.com/ivadomed/model_seg_ms_mp2rage/releases/download/r20230210/model_seg_lesion_mp2rage_r20230210_dil32_seed02.zip"],
            "seed3": ["https://github.com/ivadomed/model_seg_ms_mp2rage/releases/download/r20230210/model_seg_lesion_mp2rage_r20230210_dil32_seed03.zip"],
            "seed4": ["https://github.com/ivadomed/model_seg_ms_mp2rage/releases/download/r20230210/model_seg_lesion_mp2rage_r20230210_dil32_seed04.zip"],
            "seed5": ["https://github.com/ivadomed/model_seg_ms_mp2rage/releases/download/r20230210/model_seg_lesion_mp2rage_r20230210_dil32_seed05.zip"],
        },
    },
}
```

Sidecar .json sample (this is a bit trickier, since the allowable fields for `GeneratedBy` [are limited](https://bids-specification.readthedocs.io/en/stable/modality-agnostic-files.html)):

```json
{
  "GeneratedBy": [
    {
      "Name": "sct_deepseg -task seg_sc_epi",
      "Version": "6.3.0",
      "CodeURL": "https://github.com/sct-pipeline/fmri-segmentation/releases/download/v0.2/model-fmri-segmentation-v0.2.zip"
    },
  ],
}
```

Or, alternatively:

```json
{
  "GeneratedBy": [
    {
      "Name": "sct",
      "Version": "6.3.0",
      "CodeURL": "https://github.com/spinalcordtoolbox/spinalcordtoolbox"
    },
    {
      "Name": "sct_deepseg -task seg_sc_epi",
      "Version": "https://github.com/sct-pipeline/fmri-segmentation/releases/download/v0.2/model-fmri-segmentation-v0.2.zip",
      "CodeURL": "https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/72ff27030efda92431ee831b45f31e2858b8552d/spinalcordtoolbox/scripts/sct_deepseg.py"
    },
  ],
}
```

**Comment by jcohenadad** [comment]
do we really need to consider mirrors? if it simplify things, maybe we can ignore them (URL's from github assets seems to be fetchable from everywhere in the world, so far...)
