### ISSUE TITLE
qc report to display manual segmentation

### ISSUE THREAD

**Issue by maxradx** [spinalcordtoolbox/spinalcordtoolbox#4488]
Hi,

**Feature justification: Is your feature request related to a problem? Please describe.**
_I want to use the sct_qc function to generate a qc report that displays manual segmentations after completing manual segmentation tasks._

**Describe the solution you'd like***
_If it does not already exist, I think it would be great to have a function like sct_qc -i _source_image.nii.gz_ -mask _mask.nii.gz_ (where _source_image.nii.gz_ is the source image from a dataset and _mask.nii.gz_ the mask that has been obtained with manual segmentation) that generate a qc report making able to navigate through the images for quick assessment of the accuracy of manual segmentations._

**Describe alternatives you've considered**
_How can we easily qc manual segmentation images? (instead of using manual correction script and iterate through cases, for example....)_

**Additional context**
N/A.

Thanks.

**Comment by valosekj** [comment]
You can use `sct_qc` with the following syntax:

```console
sct_qc -i ${file}.nii.gz -s ${file_seg}.nii.gz -d ${file_lesion}.nii.gz -p sct_deepseg_lesion -plane sagittal -qc ${PATH_QC} -qc-subject ${SUBJECT}
```

- `-i` -  background image, e.g., T2w
- `-s` - spinal cord segmentation used to crop the QC around the spinal cord (because there is no need to show slices outside of the spinal cord)
- `-d` - binary lesion segmentation

Example: https://github.com/ivadomed/model_seg_sci/blob/392a88ab3dc1cbc2f2f5ef1fe5ba7217a216a825/create_manual_sc_seg/generate_qc.sh#L88C1-L88C187

**Comment by maxradx** [comment]
Ok thanks! 1- But is there a way to generate the sct qc report from manual segmentation that is not on spinal cord images (I really like the interface and think from a more general perspective e.g. manual segmentation of brain tumors)? 2- Also, in this command line, I must have processed the images using sct (sct_deepseg_lesion) : is there a way to generate the qc report without image processing in sct? (e.g. just to overlay the manual segmentation mask with the image?)

**Comment by maxradx** [comment]
Ok great! It works (to display manual segmentation). Thanks!
Other question: 
If I want to include all slices of the study (not just the ones with the SC), how may I proceed? (script provides the error below when I try to not use the argument -s : TypeError: Image constructor takes at least one argument.
<img width="1255" alt="image" src="https://github.com/spinalcordtoolbox/spinalcordtoolbox/assets/142258732/fbd86599-673d-41b8-8179-794e6756990e">

**Comment by valosekj** [comment]
> If I want to include all slices of the study (not just the ones with the SC), how may I proceed? 

Hmm, good question. Maybe you can try to dilate (`sct_maths -dilate`) the SC mask to cover also slices outside of the SC.

> (script provides the error below when I try to not use the argument -s : TypeError: Image constructor takes at least one argument.

Yes, this is expected because `sct_qc -p sct_deepseg_lesion` requires both `-s` and `-d` arguments.

You can try to check [this issue](https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/4166) and [this PR](https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/4479) and try to do some experiments with `sct_qc` to achieve the QC you need.

**Comment by joshuacwnewton** [comment]
Given that the scope of this issue is covered by:

- https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/4166

I think we can close this issue?
