### ISSUE TITLE
Flattening changes the image intensity value

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#4548]
### Description

Full description here: https://github.com/spinal-cord-7t/coil-qc-code/issues/83

**Comment by joshuacwnewton** [comment]
Thank you for reporting this!

> > it appears that sct_flatten_sagittal changes the dynamic range of the image. Is this normal?
> 
> Oops! not normal (I think).

It turns out that this issue is already known! See: 

- https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3737

I had already done the investigation and proposed a fix, but I think I may have forgotten to open a PR at the time. :sweat:

(Anyway, closing as a duplicate. And, I'll self-assign the other issue so it doesn't get forgotten.)
