### ISSUE TITLE
Tiny QC for `sct -p sct_label_vertebrae`

### ISSUE THREAD

**Issue by valosekj** [spinalcordtoolbox/spinalcordtoolbox#4563]
I wanted to generate QC for T2w labeling brought to T2s space:

<img width="700" alt="image" src="https://github.com/user-attachments/assets/3d2567a0-1726-4cd3-8d78-8923663dd155">

But, when using the following command, the QC is super tiny.

```bash
sct_qc -i sub-001_T2star.nii.gz -s sub-001_T2w_seg_labeled2sub-001_T2star.nii.gz -p sct_label_vertebrae -qc ./qc
```

<img width="1484" alt="image" src="https://github.com/user-attachments/assets/e5f655c5-efb2-4c8a-bc63-533f79aa13f2">

[Link](https://www.dropbox.com/scl/fo/ijnp2xwaj2qohsb34e6ng/ANbHzD4oYimuIkxqMWvEn5E?rlkey=q8yi2z2ssblgw63xom7594tbg&dl=0) to the data (including QC).

**Comment by joshuacwnewton** [comment]
It looks like the `sct_label_vertebrae` QC wasn't designed for highly anisotropic images in mind:

- The resolution of a single sagittal slice is `[512, 42]`
- The slices are thick, with resolution `[0.35, 2.46]` mm respectively.
- FSLeyes (and other viewers) stretch the thick slices vertically so that each voxel is proportional to its resolution:
![image](https://github.com/user-attachments/assets/50a1064c-699a-42e8-8bfa-b56ad417f666)
- For matplotlib, this "stretching" is handled by the `aspect` parameter of `imshow`:
https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/a631c4d978cbd1d8a5e14da4b7a30e244eca2f9c/spinalcordtoolbox/reports/qc.py#L322
- And, we can see that the aspect ratio actually does get properly fixed! 
![image](https://github.com/user-attachments/assets/3aab0536-d432-4898-a0a5-8269014bb42a)
- The problem is that the canvas size is far too small, causing the image to get squished. Note that we do try to adjust the height of the canvas size to match the size of the image:
https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/a631c4d978cbd1d8a5e14da4b7a30e244eca2f9c/spinalcordtoolbox/reports/qc.py#L311-L316
- However, the bug here is that we use the **original dimensions** of the image (512x42) to perform this height adjustment. Instead, we need to use the *resolution-adjusted* dimensions of the image to calculate the size of the canvas. 
   - 512x42 leads to a canvas size of 5" x 0.41" (tiny height)
   - However, the ratio between resolutions (2.46/0.35) is ~7.11. Adjusting the canvas height by this aspect ratio gives a canvas size of 5" x 2.917", which actually matches the image!

![image](https://github.com/user-attachments/assets/6acc4eba-3c0c-442f-817f-0ad6b1feb5c7)

I'll open a PR ASAP. :)
