### ISSUE TITLE
`sct_register_multimodal` is changing the data type when using nearest neighbours interpolation

### ISSUE THREAD

**Issue by NathanMolinier** [spinalcordtoolbox/spinalcordtoolbox#4572]
## Description

I needed to use `sct_register_multimodal -identity 1 -x nn` to put segmentation masks in the same orientation/space as my images and I noticed that the function was changing the type of my output label. Is it normal ?

## Example

The type of my input label is `INT16` before using the function and the type of my image is `FLOAT64`.

After running
```
sct_register_multimodal -i labelsTr/sub-amuAL_T1w_label.nii.gz -d imagesTr/sub-amuAL_T1w.nii.gz -o reg/sub-amuAL_T1w.nii.gz -identity 1 -x nn
```

The type of my output label is `FLOAT64` even though I used nearest neighbour interpolation. Is it what I should expect ?

**Comment by joshuacwnewton** [comment]
Some notes:

- `-identity 1` still performs registration + warping, but it replaces the steps with only a very basic step 0. :
    https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/d151cc390a088bbc3251cc1a3086abd602b24dfd/spinalcordtoolbox/registration/core.py#L112-L115
    Meaning, I don't think `-identity 1` is related to the datatype issue.
- The `-x` argument then gets supplied to `sct_apply_transfo` as `interp` when applying the warping fields, done here:
    https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/d151cc390a088bbc3251cc1a3086abd602b24dfd/spinalcordtoolbox/registration/core.py#L232-L239
- `nn` is mapped to `-n NearestNeighbor` and passed to `isct_antsApplyTransform` here:
    https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/9ce98c23708e45a350e034af7e738e02163e1819/spinalcordtoolbox/scripts/sct_apply_transfo.py#L209-L214
- Checking `Image(fname_src).data.dtype` and `Image(fname_out).data.dtype` before and after this step shows `<i2` dtype for the former and `<f8` for the latter, meaning that the datatype change was caused by ANTs.

We could check to see if ANTs has any method to preserve the datatype, or perhaps add a case saying something like "if input datatype is integer and interpolation is nn, preserve the integer datatype". But for now, I hope that explains the source of the datatype change.
