### ISSUE TITLE
Verbose CLI arg (`sct_apply_transfo -v`) is not passed to the subprocess call to `antsApplyTransforms`

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#4581]
My suggestion would be to _also_ change the verbose logic of the "Apply moco" section, and when verbose=1 is specified, silence the call to `isct_antsApplyTransforms`:

~~~
-------------------------------------------------------------------------------
  Apply moco
-------------------------------------------------------------------------------

Input parameters:
  Input file ............ data.nii
  Reference file ........ datasub_0_mean.nii.gz
  Polynomial degree ..... 0
  Smoothing kernel ...... 0
  Gradient step ......... 1
  Metric ................ MeanSquares
  Sampling .............. None
  Todo .................. apply
  Mask  ................. mask.nii
  Output mat folder ..... mat_final

Data dimensions:
  96 x 50 x 25 x 60

Copy file_target to a temporary file...

Register. Loop across Z (note: there is only one Z if orientation is axial)
Z=0/0:   0%|                                           | 0/60 [00:00<?, ?iter/s]/Users/julien/code/spinalcordtoolbox/bin/isct_antsApplyTransforms -d 3 -i /private/var/folders/5f/6n99hhyj5_g5cv_1bbx1q7cr0000gn/T/sct_2024-07-29_15-46-43_moco-wrapper_v0_qq83w/data_T0000.nii -o /private/var/folders/5f/6n99hhyj5_g5cv_1bbx1q7cr0000gn/T/sct_2024-07-29_15-46-43_moco-wrapper_v0_qq83w/data_T0000_moco.nii -t mat_final/mat.Z0000T0000Warp.nii.gz -r datasub_0_mean.nii.gz -n Linear # in /private/var/folders/5f/6n99hhyj5_g5cv_1bbx1q7cr0000gn/T/sct_2024-07-29_15-46-43_moco-wrapper_v0_qq83w
Z=0/0:   2%|▌                                  | 1/60 [00:00<00:15,  3.78iter/s]/Users/julien/code/spinalcordtoolbox/bin/isct_antsApplyTransforms -d 3 -i /private/var/folders/5f/6n99hhyj5_g5cv_1bbx1q7cr0000gn/T/s
~~~

Interestingly the output should already be silenced:
https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/682a6dcfa72010406f8f1a2cf8485f3d758eadb6/spinalcordtoolbox/moco.py#L755-L761

I see, the problem is that verbose is never passed to `run_proc()` within the class `Transform`:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/682a6dcfa72010406f8f1a2cf8485f3d758eadb6/spinalcordtoolbox/scripts/sct_apply_transfo.py#L209-L214

This is out of scope (large repercussion if I change the logic here) so I will open another issue.

_Originally posted by @jcohenadad in https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/4580#issuecomment-2256791486_

**Comment by joshuacwnewton** [comment]
> This is out of scope (large repercussion if I change the logic here) so I will open another issue.

Just to verify this, I checked all calls to `sct_apply_transfo`, and it turns out that *every single call* specifies `-v 0` across all CLI scripts (moco, registration, etc.). Which means that if we propagate the status to `run_proc`, then we would change the logging output for every sub-call to `sct_apply_transfo` in SCT.

That said, oddly enough the 4D case _does_ properly specify verbose:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/a866fc666681eca5e7e075b2f6174be0d670f6dd/spinalcordtoolbox/scripts/sct_apply_transfo.py#L253-L260

So there is already precedent for silencing the logging messages. Plus, in many cases, there are logging messages already printed to the console right before the call to `sct_apply_transfo`, meaning there will still be feedback for the user. So, I think it makes sense to propagate the verbose status (to silence the logging messages).
