### ISSUE TITLE
`matplotlib==3.9.1` no longer installs wheels, instead tries to build on Windows (but fails in CI)

### ISSUE THREAD

**Issue by joshuacwnewton** [spinalcordtoolbox/spinalcordtoolbox#4590]
Looking at the matplotlib repo, I see:

- https://github.com/matplotlib/matplotlib/issues/28660

> these were deliberately deleted due to a bug which only affected Windows.

- https://github.com/matplotlib/matplotlib/issues/28551#issuecomment-2267223102

> Deleting the wheels without also deleting the sdist or yanking the whole version has made the situation worse. Now matplotlib silently builds from source which results in more confusing issues.

I've reported our specific error upstream. Hopefully they yank the release or reinstate the wheels. I have a feeling this will be resolved by tomorrow, though, so we probably won't have to do anything on our end.

**Comment by tacaswell** [comment]
We deleted the bad wheels to avoid segfaults (which seemed like a good idea) but failed to anticipate that this would cause downstream projects to start trying to build mpl from source instead of pulling the 3.9.0 wheel.

Sorry for the trouble.

----

Independent of what we do upstream, I suggest you exclude 3.9.1 on windows and add a `--only-binary` flag for Matplotlib.
