### ISSUE TITLE
`sct_analyze_lesion` -  pandas warnings are mixing with the function output

### ISSUE THREAD

**Issue by valosekj** [spinalcordtoolbox/spinalcordtoolbox#4591]
### Description

When running `sct_analyze_lesion` on `sub-zh102` from `sci-zurich` using:

```console
sct_analyze_lesion -m derivatives/labels/sub-zh102/ses-01/anat/sub-zh102_ses-01_acq-sag_T2w_lesion-manual.nii.gz -s derivatives/labels/sub-zh102/ses-01/anat/sub-zh102_ses-01_acq-sag_T2w_seg-manual.nii.gz -qc qc
```

The CLI output contains `SettingWithCopyWarning` warnings, making the output difficult to follow:

<img width="988" alt="image" src="https://github.com/user-attachments/assets/7a756d04-09f4-4cc5-acfb-e5e9a5430ed8">

**Comment by valosekj** [comment]
We could either fix the code that raises the warnings (by using `.loc` as suggested in the screenshot above) or we can try to suppress the warning, as done similarly in https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/4595/commits/a4bdbc7c9ba88e3ff3e9360c0a5e245103a20d9d.

**Comment by joshuacwnewton** [comment]
I'm reading up on some threads discussing this warning, trying to figure out if there's a better pattern we can use. Will respond in a sec. :)

**Comment by joshuacwnewton** [comment]
The relevant section of code is:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/7b863f3eb3600d98a0f6525fc6dea56f5f5ede23/spinalcordtoolbox/scripts/sct_analyze_lesion.py#L486-L492

Reading through https://stackoverflow.com/a/38835530, it seems like the issue is that we try to create `df_temp` earlier on:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/7b863f3eb3600d98a0f6525fc6dea56f5f5ede23/spinalcordtoolbox/scripts/sct_analyze_lesion.py#L470-L471

But we are not explicit about whether we want a "view" (i.e. changes the original dataframe) or a "copy" (independent of the original dataframe). Because we are not explicit, there is potential ambiguity, hence why pandas throws this warning. To fix this warning, we just need to be explicit about what we want, and there are multiple ways to do this (not just `.loc`).

I think in this case, because we only ever access the newly-added columns from `df_temp` and not from the original `tissue_bridges_df` DataFrame, we don't need a "view", and so I think it should be fine to denote `df_temp` as a copy:

```diff
-             df_temp = tissue_bridges_df[tissue_bridges_df['sagittal_slice'] == sagittal_slice]
+             df_temp = tissue_bridges_df[tissue_bridges_df['sagittal_slice'] == sagittal_slice].copy()
```
