### ISSUE TITLE
`sct_maths -add` fails when masks have different dtype

### ISSUE THREAD

**Issue by valosekj** [spinalcordtoolbox/spinalcordtoolbox#4652]
Our collaborator @dpfyffer ran into the following issue with the `sct_maths -add` command for SCT 6.4 when two masks (attached) have different dtypes:

```console
/home/dpfyffer/sct_6.4/bin/sct_maths -i sub-374_ses-01spinalcord_task-MP_bold_mean_seg.nii.gz -add sub-374_ses-01spinalcord_task-MP_bold_mean_CSF_seg.nii.gz -o sub-374_ses-01spinalcord_task-MP_bold_mean_SC_canal_seg_test.nii.gz

--
Spinal Cord Toolbox (git-HEAD-06cceb585baacccff0385324f69a637b2dde65ab)

sct_maths -i sub-374_ses-01spinalcord_task-MP_bold_mean_seg.nii.gz -add sub-374_ses-01spinalcord_task-MP_bold_mean_CSF_seg.nii.gz -o sub-374_ses-01spinalcord_task-MP_bold_mean_SC_canal_seg_test.nii.gz
--

Traceback (most recent call last):
  File "/home/dpfyffer/sct_6.4/spinalcordtoolbox/scripts/sct_maths.py", line 621, in <module>
    main(sys.argv[1:])
  File "/home/dpfyffer/sct_6.4/spinalcordtoolbox/scripts/sct_maths.py", line 443, in main
    data += np.sum(list_data, axis=0)
numpy.core._exceptions._UFuncOutputCastingError: Cannot cast ufunc 'add' output from dtype('float64') to dtype('int8') with casting rule 'same_kind'
```

I can reproduce the bug with the SCT master. Interestingly, the command works fine for v6.3. 

[sub-374_ses-01spinalcord_task-MP_bold_mean_CSF_seg.nii.gz](https://github.com/user-attachments/files/17439681/sub-374_ses-01spinalcord_task-MP_bold_mean_CSF_seg.nii.gz)
[sub-374_ses-01spinalcord_task-MP_bold_mean_seg.nii.gz](https://github.com/user-attachments/files/17439682/sub-374_ses-01spinalcord_task-MP_bold_mean_seg.nii.gz)

---

A side question: Dario and I installed SCT v6.4 using the following commands:

```console
git clone https://github.com/spinalcordtoolbox/spinalcordtoolbox sct_6.4
cd sct_6.4
git checkout 6.4
./install_sct
```

Why the SCT version shown in the terminal when running `sct_maths` is `git-HEAD-06cceb585baacccff0385324f69a637b2dde65ab` and not `6.4`?

**Comment by mguaypaq** [comment]
For the side question: I think the following code determines that your checkout has a `.git` folder, so the installation type is `git` rather than `package`.

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/f5d774187486e4c61773d3f082ec35a37981da5a/spinalcordtoolbox/utils/sys.py#L437-L446

And then the following code decides to use the git commit info, rather than the file `spinalcordtoolbox/version.txt` (which contains `6.4` in your checkout).

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/f5d774187486e4c61773d3f082ec35a37981da5a/spinalcordtoolbox/utils/sys.py#L429-L432

If you instead download and run the install script from [the release page](https://github.com/spinalcordtoolbox/spinalcordtoolbox/releases/tag/6.4), then the installation is _not_ a git repo, and it's considered a `package` installation type, and the version should be shown as 6.4.

**Comment by mguaypaq** [comment]
For the main question: I think the bug is my fault, introduced in #4485. I tried to use in-place addition/subtraction/multiplication/division of the numpy arrays when possible, but this doesn't work when the data types have to be promoted (for example, from integer to floating point).
