### ISSUE TITLE
QC of sct_deepseg displays "soft" segmentations

### ISSUE THREAD

**Issue by sandrinebedard** [spinalcordtoolbox/spinalcordtoolbox#4735]
## Description

When running the Qc report in `sct_deepseg` function, the segmentation ouput in the QC report is soft, but when rerunning the command with `sct_qc -p sct_deepseg_sc`, the ouput in the QC is binarized. I know it can be useful to have it soft if the flag `-thr 0` is used, but the visual is a bit weird.

I would suggest to binarize also the `sct_deepseg` QC if the flag `-thr 0` is not there? 

### `sct_deepseg` QC
![Capture d’écran, le 2024-12-02 à 11 34 47](https://github.com/user-attachments/assets/655b5a90-962c-42d3-995d-90781c5afff1)

### `sct_deepseg_sc` QC
![Capture d’écran, le 2024-12-02 à 11 35 09](https://github.com/user-attachments/assets/16ff1b12-fa9b-4e9c-b165-1270b18df56c)

**Comment by joshuacwnewton** [comment]
What `sct_deepseg` command did you run?

**Comment by joshuacwnewton** [comment]
It turns out that this is not actually the fault of the colormap, but instead due to the transparency (alpha). I had set it so that softsegs would have some transparency for their soft regions. I don't really know why I did this, but I'll revert it so that there is consistent transparency and a single colormap, even for softsegs:

Before: 

![image](https://github.com/user-attachments/assets/5c8b6819-ac93-4377-9556-f85b4d624954)

After: 

![image](https://github.com/user-attachments/assets/af33225f-47b2-4e35-af57-032c62282552)

**Comment by sandrinebedard** [comment]
Great thanks! I was doing the course and noticed it for all sct_deepseg commands!
