### ISSUE TITLE
account for all vertebral levels and pontomedullary junction in registration to template to account for subject lordosis

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#949]
data: @jcohen (private data): 20160727_sct318_sct313

below an example of the same subject, scanned at two different time, showing cord-to-spine discrepancies, which then reflected in the registration to template.

however, already accounting for all vertebral levels (instead of doing an affine on only two levels) should improve a lot.

![site100](https://cloud.githubusercontent.com/assets/2482071/17188883/113eb0fc-540d-11e6-9f98-16b032f0db80.png)
![site200](https://cloud.githubusercontent.com/assets/2482071/17188884/11455826-540d-11e6-8360-ebb1f12c0b23.png)

**Comment by jcohenadad** [comment]
With #2102, the PAM50 template does not include the PMJ anymore, so this issue is a bit out of context. Reducing the priority for now.

**Comment by joshuacwnewton** [comment]
> however, already accounting for all vertebral levels (instead of doing an affine on only two levels) should improve a lot.

Given that `sct_register_to_template` is capable of using more than 1/2 labels for registration (possibly because of #1669), I believe this issue has been resolved (to the extent that it can be, given https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/949#issuecomment-449852954.)

From the "[How many vertebral labels should I use for registration](https://spinalcordtoolbox.com/user_section/tutorials/registration-to-template/vertebral-labeling/how-many-labels-for-registration.html)" page:

> **3+ labels**
> This is the most accurate method for matching the vertebral levels of the anatomical image to the levels of the template. However, there is a key downside to this approach: Because more than two points must be matched, the level-matching transformation cannot be affine. As a result, the output warping field will be undefined for regions above the top label and below the bottom label.

If I've misunderstood in some way, though, feel free to re-open.
